# Reddit Ticker Matching

將 01 階段清理後的 6 份 CSV 分塊處理，依 ticker 字典比對留言中的股票代碼，未匹配成功的留言刪除。

## 比對規則

- 使用成功的 00 階段 ticker 字典。
- 比對不區分大小寫。
- Token 定義為連續的 Unicode `\w+`：
  - `$AAPL`、`AAPL,`、`AAPL.` 可匹配。
  - `XAAPL`、`AAPL2`、`AAPL_test` 不匹配。
- 同一留言中的同一 ticker 只記錄一次，並按字母排序。
- 不對留言去重，即使 `id` 重複也保留。

## 資料處理

- 全程分塊處理。
- 跨 chunk 的唯一值統計使用 SQLite。
- 不使用逐列 × ticker dictionary 的 Python 迴圈。
- Unix timestamp 以 UTC 轉換日期相關欄位。
- 無法解析的日期保留並計入診斷，不直接刪除。

## Comment Enrichment

從原始 cleaned CSV 保留並整理：

- `id`
- `comment_id`
- `parent_id`
- `thread_id`
- UTC timestamp / date
- `year_month`
- `matched_tickers`

空白 thread 或無效日期維持 null，不額外過濾。

## 輸出

- 有匹配 ticker 的 comment-level Parquet
- ticker mention / pair Parquet
- `run_summary.json`

未匹配留言不寫入 Parquet，但納入 diagnostics。

每次執行建立新的 UTC 時間戳資料夾；成功後更新 `pipeline_runs.json`，失敗則不覆蓋既有 pointer。舊輸出保留。

In [3]:
from pathlib import Path
from datetime import datetime, timezone
from collections import Counter
import csv, hashlib, importlib.metadata, json, platform, re, sqlite3, statistics, time, uuid
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import ahocorasick
from IPython.display import display

ROOT = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p / 'Data/process').is_dir())

import sys
sys.path.insert(0,str(ROOT/'Notebook'))
from pipeline_io import new_run, publish, input_run, remove_work_database

INPUT_DIR = input_run(ROOT,'cleaned',ROOT/'Data/process')
UNIVERSE_DIR = input_run(ROOT,'universe',ROOT/'Data/process/universe_review')
DICTIONARY = UNIVERSE_DIR/('approx_common_stock_tickers.txt' if (UNIVERSE_DIR/'run_summary.json').exists() else 'approx_SHRCD_10_11_tickers.txt')
SOURCES = [INPUT_DIR / f'wallstreetbets_comment_part{i}.csv' for i in range(1, 7)]
assert all(p.is_file() for p in SOURCES), 'Expected exactly six named input files'
CHUNK_SIZE = 50_000
BENCHMARK_ROWS = 100_000
BENCHMARK_REPEATS = 3
COLUMNS = ['id', 'parent_id', 'author', 'created_utc', 'link_id', 'body']
RUN_DIR = new_run(ROOT,'matching')
INPUT_STATS = {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in SOURCES}
VERSIONS = {p: importlib.metadata.version(p) for p in ['pandas', 'pyarrow', 'pyahocorasick']}
print('Output:', RUN_DIR)
print('Versions:', VERSIONS)
display(pd.DataFrame([{'file': p.name, 'bytes': p.stat().st_size} for p in SOURCES]))

def read_chunks(path, nrows=None):
    return pd.read_csv(path, usecols=COLUMNS, dtype=str, keep_default_na=False,
                       na_filter=False, encoding='utf-8-sig', chunksize=CHUNK_SIZE,
                       nrows=nrows, on_bad_lines='error')

tickers = sorted({s.strip().upper() for s in DICTIONARY.read_text(encoding='utf-8-sig').splitlines() if s.strip()})
assert tickers and all(re.fullmatch(r'[A-Z]+', t) for t in tickers), 'Review tokenizer for a non-alphabetic dictionary'
TICKER_SET = frozenset(tickers)
print({'dictionary_rows': len(tickers), 'unique_tickers': len(TICKER_SET),
       'date_range': 'N/A: dictionary has no dates', 'unique_authors': 'N/A', 'unique_threads': 'N/A'})

Output: c:\Users\eagle\RedditStock\Data\process\02_ticker_matching\2026-09-22_03-52-09_UTC
Versions: {'pandas': '3.0.5', 'pyarrow': '22.0.0', 'pyahocorasick': '2.3.1'}

                               file      bytes
0  wallstreetbets_comment_part1.csv   63729671
1  wallstreetbets_comment_part2.csv   97837151
2  wallstreetbets_comment_part3.csv  364124678
3  wallstreetbets_comment_part4.csv  544503864
4  wallstreetbets_comment_part5.csv  680250712
5  wallstreetbets_comment_part6.csv  358353292

{'dictionary_rows': 9804, 'unique_tickers': 9804, 'date_range': 'N/A: dictionary has no dates', 'unique_authors': 'N/A', 'unique_threads': 'N/A'}

## Matching Engine 與邊界檢查

提供兩種 matching engine：

- **Token + Hash Set**：先切分 token，再以 hash set 進行常數時間查找。
- **Aho–Corasick**：一次掃描全文搜尋所有 ticker，只有當匹配前後字元都不是 Unicode word character 時才接受。

兩種方法皆輸出排序後且不重複的 ticker 清單。

In [4]:
TOKEN_RE = re.compile(r'\w+', re.UNICODE)

def make_token_matcher(words):
    words = frozenset(words)
    def match(text):
        return sorted({token for token in TOKEN_RE.findall(text.upper()) if token in words})
    return match

def is_word(c):
    return c == '_' or c.isalnum()

def make_aho_matcher(words):
    automaton = ahocorasick.Automaton()
    for word in words:
        automaton.add_word(word, word)
    automaton.make_automaton()
    def match(text):
        text = text.upper()
        found = set()
        for end, word in automaton.iter(text):
            start = end - len(word) + 1
            if (start == 0 or not is_word(text[start-1])) and (end+1 == len(text) or not is_word(text[end+1])):
                found.add(word)
        return sorted(found)
    return match

build_times = {}
MATCHERS = {}
for name, factory in [('token_hash_set', make_token_matcher), ('aho_corasick', make_aho_matcher)]:
    started = time.perf_counter()
    MATCHERS[name] = factory(TICKER_SET)
    build_times[name] = time.perf_counter() - started

cases = {
    '$AAPL AAPL, AAPL.': ['AAPL'],
    'aapl / MsFt': ['AAPL', 'MSFT'],
    'XAAPL AAPLX AAPL2 2AAPL AAPL_test _AAPL': [],
    '中AAPL AAPLé': [],
    '($AAPL), MSFT. AAPL': ['AAPL', 'MSFT'],
    '': [], 'nothing here': [], 'AAPL\nMSFT': ['AAPL', 'MSFT'],
    'AA AAA AAAA': ['AAA'],
}
for factory in [make_token_matcher, make_aho_matcher]:
    test_match = factory({'AAPL', 'MSFT', 'AAA'})
    for body, expected in cases.items():
        assert test_match(body) == expected, (factory.__name__, body, test_match(body))
print('Boundary, case, repeated mention, multi-ticker and empty-body checks passed.')

Boundary, case, repeated mention, multi-ticker and empty-body checks passed.

## Benchmark

使用第一個輸入檔的前 100,000 筆資料測試 matching engine。

- 分塊讀取，僅保留單一 chunk 與兩組比對結果。
- 比較完整的逐列 matching 結果，確認兩者輸出一致。
- 選擇標準：3 次完整 100,000-row matching 時間。

In [5]:
def date_info(series):
    dt = pd.to_datetime(pd.to_numeric(series, errors='coerce'), unit='s', utc=True, errors='coerce')
    return {'date_min': None if dt.dropna().empty else dt.min().isoformat(),
            'date_max': None if dt.dropna().empty else dt.max().isoformat(),
            'invalid_date_count': int(dt.isna().sum())}

def local_diagnostics(frame):
    return {'row_count': len(frame), **date_info(frame['created_utc']),
            'unique_authors': int(frame.loc[frame.author.ne(''), 'author'].nunique()),
            'unique_threads': int(frame.loc[frame.link_id.ne(''), 'link_id'].nunique()),
            'missing_comment_id_count': int(frame.id.eq('').sum())}

timings = {name: [0.0] * BENCHMARK_REPEATS for name in MATCHERS}
benchmark_count = benchmark_matched = benchmark_multi = 0
benchmark_started = time.perf_counter()
for chunk_no, chunk in enumerate(read_chunks(SOURCES[0], nrows=BENCHMARK_ROWS), 1):
    bodies = chunk.body.tolist()
    for repeat in range(BENCHMARK_REPEATS):
        results = {}
        order = list(MATCHERS)
        if (repeat + chunk_no) % 2: order.reverse()
        for name in order:
            start = time.perf_counter()
            results[name] = [MATCHERS[name](body) for body in bodies]
            timings[name][repeat] += time.perf_counter() - start
        assert results['token_hash_set'] == results['aho_corasick'], 'Engines disagree; stop before formal run'
    matches = results['token_hash_set']
    mask = [bool(m) for m in matches]
    benchmark_count += len(chunk)
    benchmark_matched += sum(mask)
    benchmark_multi += sum(len(m) >= 2 for m in matches)
    print({'benchmark_chunk': chunk_no, 'input': local_diagnostics(chunk),
           'matched': local_diagnostics(chunk.loc[mask])}, flush=True)
    del bodies, results, matches, mask, chunk
assert benchmark_count == BENCHMARK_ROWS
benchmark_table = pd.DataFrame([{'method': name, 'rows': benchmark_count,
    'build_seconds': build_times[name], 'repeat_seconds': times,
    'median_seconds': statistics.median(times),
    'rows_per_second': benchmark_count / statistics.median(times)} for name, times in timings.items()])
SELECTED_METHOD = min(timings, key=lambda name: statistics.median(timings[name]))
match = MATCHERS[SELECTED_METHOD]
display(benchmark_table)
print({'selected_method': SELECTED_METHOD, 'matched_comments': benchmark_matched,
       'comments_with_ge2_tickers': benchmark_multi, 'exact_result_agreement': True})
# Benchmark is retained in notebook output and run_summary.json.

{'benchmark_chunk': 1, 'input': {'row_count': 50000, 'date_min': '1970-01-01T00:00:01+00:00', 'date_max': '2015-04-28T13:33:04+00:00', 'invalid_date_count': 13, 'unique_authors': 4300, 'unique_threads': 4247, 'missing_comment_id_count': 13}, 'matched': {'row_count': 39254, 'date_min': '2012-04-11T16:46:43+00:00', 'date_max': '2015-04-28T13:18:59+00:00', 'invalid_date_count': 9, 'unique_authors': 3857, 'unique_threads': 4108, 'missing_comment_id_count': 9}}
{'benchmark_chunk': 2, 'input': {'row_count': 50000, 'date_min': '1970-01-01T00:00:03+00:00', 'date_max': '2015-08-26T20:23:11+00:00', 'invalid_date_count': 1, 'unique_authors': 3727, 'unique_threads': 3675, 'missing_comment_id_count': 1}, 'matched': {'row_count': 35864, 'date_min': '2015-04-28T13:38:35+00:00', 'date_max': '2015-08-26T20:23:11+00:00', 'invalid_date_count': 1, 'unique_authors': 3210, 'unique_threads': 3510, 'missing_comment_id_count': 1}}

,method,rows,build_seconds,repeat_seconds,median_seconds,rows_per_second
0,token_hash_set,100000,0.000003,"[0.971318700001575, 0.8678123999852687, 0.8448...",0.867812,115232.278315
1,aho_corasick,100000,0.004082,"[1.122967200120911, 1.125861500040628, 1.21414...",1.125862,88820.871836

{'selected_method': 'token_hash_set', 'matched_comments': 75118, 'comments_with_ge2_tickers': 51480, 'exact_result_agreement': True}

## Parquet 輸出

每個輸入檔會產生：

- `*.comments.parquet`
- `*.mentions.parquet`

每處理完一個 chunk，就立即將匹配到的留言與 ticker mention 寫入 Parquet row group，並使用 Zstandard 壓縮。

- `matched_tickers` 儲存為字串列表。
- `created_utc` 保留原始字串格式。
- 寫入時先使用 `.partial` 暫存檔，成功關閉並驗證後才視為完成。
- 執行中斷則該次 run 不算完成，需在新目錄重新執行。
- 即使某輸入檔沒有任何匹配，也會建立有效的空 Parquet 檔。

## 統計

使用暫存 SQLite 計算每個輸入檔與各處理階段中的唯一值：

- 非空白 `author`
- 非空白 `thread`
- `ticker`

整體唯一值數量採跨檔案聯集計算，而不是直接加總各檔結果。

### 缺失 Comment ID

原始空白 comment ID 仍保留，並納入 diagnostics 統計。

兩種輸出都額外加入：

- `source_file`
- `source_row`：從 1 開始的原始 CSV 邏輯列號，不含 header

這兩個欄位只用於追溯來源，不會取代或虛構 Reddit ID。

In [6]:
def utc_datetimes(values):
    return pd.to_datetime(pd.to_numeric(values, errors='coerce'), unit='s', utc=True, errors='coerce').dt.as_unit('ns')

def thread_ids(values):
    normalized = values.fillna('').str.strip().str.lower().str.replace(r'^t3_', '', regex=True)
    return normalized.mask(normalized.eq(''), None)

test = utc_datetimes(pd.Series(['0', '1609459199', '1609459200', '0.5', 'bad', '']))
assert test.iloc[0].isoformat() == '1970-01-01T00:00:00+00:00'
assert test.iloc[1].strftime('%Y-%m') == '2020-12'
assert test.iloc[2].strftime('%Y-%m-%d') == '2021-01-01'
assert test.iloc[3].microsecond == 500000
assert test.iloc[4:].isna().all()
assert thread_ids(pd.Series(['t3_abc123', ' ABC123 ', '', None])).fillna('<null>').tolist() == ['abc123', 'abc123', '<null>', '<null>']
print('UTC and thread-normalization checks passed.')


COMMENT_SCHEMA = pa.schema([(c, pa.string()) for c in ['comment_id', 'author', 'created_utc', 'link_id', 'body']] +
                           [('matched_tickers', pa.list_(pa.string())), ('matched_ticker_count', pa.int32()), ('source_file', pa.string()), ('source_row', pa.int64())])
COMMENT_SCHEMA = pa.schema(list(COMMENT_SCHEMA) + [pa.field('id',pa.string()),pa.field('parent_id',pa.string()),pa.field('thread_id',pa.string()),pa.field('created_datetime_utc',pa.timestamp('ns',tz='UTC')),pa.field('created_date',pa.date32()),pa.field('year_month',pa.string())])
MENTION_SCHEMA = pa.schema([('comment_id', pa.string()), ('ticker', pa.string()), ('source_file', pa.string()), ('source_row', pa.int64())])
WORK_DB = RUN_DIR/'_work/diagnostics.sqlite'
WORK_DB.parent.mkdir()
db = sqlite3.connect(WORK_DB)
db.execute('PRAGMA cache_size=-32768')
db.execute('PRAGMA temp_store=FILE')
db.execute('CREATE TABLE uniques (file TEXT, stage TEXT, kind TEXT, value TEXT, PRIMARY KEY(file,stage,kind,value)) WITHOUT ROWID')

def record_uniques(file, stage, frame, ticker_values=()):
    for kind, values in [('authors', frame.author.unique()), ('threads', frame.link_id.unique()), ('tickers', ticker_values)]:
        db.executemany('INSERT OR IGNORE INTO uniques VALUES (?,?,?,?)',
                       ((file, stage, kind, str(value)) for value in values if value != ''))

def unique_count(stage, kind, file=None):
    if file is None:
        return db.execute('SELECT COUNT(DISTINCT value) FROM uniques WHERE stage=? AND kind=?', (stage, kind)).fetchone()[0]
    return db.execute('SELECT COUNT(*) FROM uniques WHERE file=? AND stage=? AND kind=?', (file, stage, kind)).fetchone()[0]

def merge_dates(stats, info, prefix):
    for suffix, func in [('date_min', min), ('date_max', max)]:
        key = prefix + suffix
        vals = [x for x in [stats.get(key), info[suffix]] if x is not None]
        stats[key] = func(vals) if vals else None
    key = prefix + 'invalid_date_count'
    stats[key] = stats.get(key, 0) + info['invalid_date_count']

def process_file(source):
    started = time.perf_counter()
    stats = {'file': source.name, 'raw_row_count': 0, 'matched_comment_count': 0,
             'comments_with_ge2_tickers': 0, 'mention_row_count': 0, 'raw_missing_comment_id_count': 0, 'matched_missing_comment_id_count': 0}
    comments_path = RUN_DIR / (source.stem + '.comments.parquet')
    mentions_path = RUN_DIR / (source.stem + '.mentions.parquet')
    cp = comments_path.with_suffix('.parquet.partial')
    mp = mentions_path.with_suffix('.parquet.partial')
    with pq.ParquetWriter(cp, COMMENT_SCHEMA, compression='zstd') as cw, pq.ParquetWriter(mp, MENTION_SCHEMA, compression='zstd') as mw:
        for chunk_no, chunk in enumerate(read_chunks(source), 1):
            chunk_started = time.perf_counter()
            hits = chunk.body.map(match)
            keep = hits.map(bool)
            matched = chunk.loc[keep].copy()
            matched['matched_tickers'] = hits.loc[keep]
            matched['matched_ticker_count'] = matched.matched_tickers.map(len)
            matched['source_file'] = source.name
            matched['source_row'] = matched.index.to_numpy() + 1
            matched['thread_id'] = thread_ids(matched.link_id)
            matched['created_datetime_utc'] = utc_datetimes(matched.created_utc)
            matched['created_date'] = matched.created_datetime_utc.dt.date
            matched['year_month'] = matched.created_datetime_utc.dt.strftime('%Y-%m')
            chunk_tickers = set(t for values in matched.matched_tickers for t in values)
            raw_diag = local_diagnostics(chunk)
            matched_diag = local_diagnostics(matched)
            enriched_diag = {'unique_threads':int(matched.thread_id.nunique()), 'missing_thread_count':int(matched.thread_id.isna().sum()), 'missing_parent_id_count':int(matched.parent_id.eq('').sum()), 'invalid_timestamp_count':int(matched.created_datetime_utc.isna().sum()), **date_info(matched.created_utc), 'row_count':len(matched), 'unique_authors':matched_diag['unique_authors']}
            stats['raw_missing_comment_id_count'] += raw_diag['missing_comment_id_count']
            stats['matched_missing_comment_id_count'] += matched_diag['missing_comment_id_count']
            stats['raw_row_count'] += len(chunk)
            stats['matched_comment_count'] += len(matched)
            stats['comments_with_ge2_tickers'] += int(matched.matched_ticker_count.ge(2).sum())
            merge_dates(stats, raw_diag, 'raw_')
            merge_dates(stats, matched_diag, 'matched_')
            record_uniques(source.name, 'raw', chunk)
            record_uniques(source.name, 'matched', matched, chunk_tickers)
            db.commit()
            if len(matched):
                output = matched.copy()
                output['comment_id'] = output['id']
                table = pa.Table.from_pandas(output, schema=COMMENT_SCHEMA, preserve_index=False)
                cw.write_table(table, row_group_size=CHUNK_SIZE)
                mentions = output[['comment_id', 'matched_tickers', 'source_file', 'source_row']].explode('matched_tickers').rename(columns={'matched_tickers': 'ticker'})
                assert len(mentions) == int(matched.matched_ticker_count.sum())
                mw.write_table(pa.Table.from_pandas(mentions, schema=MENTION_SCHEMA, preserve_index=False), row_group_size=CHUNK_SIZE)
                stats['mention_row_count'] += len(mentions)
                del output, table, mentions
            diagnostic = {'file': source.name, 'chunk': chunk_no, 'raw': raw_diag,
                          'matched': matched_diag, 'enriched':enriched_diag, 'unique_matched_tickers': len(chunk_tickers),
                          'seconds': round(time.perf_counter() - chunk_started, 3)}
            print(diagnostic, flush=True)
            del chunk, matched, hits, keep, chunk_tickers
    assert pq.read_metadata(cp).num_rows == stats['matched_comment_count']
    assert pq.read_metadata(mp).num_rows == stats['mention_row_count']
    cp.replace(comments_path)
    mp.replace(mentions_path)
    stats['match_rate'] = stats['matched_comment_count'] / stats['raw_row_count'] if stats['raw_row_count'] else 0.0
    for stage in ['raw', 'matched']:
        for kind in ['authors', 'threads']:
            stats[f'unique_{stage}_{kind}'] = unique_count(stage, kind, source.name)
    stats['unique_matched_tickers'] = unique_count('matched', 'tickers', source.name)
    stats['processing_seconds'] = time.perf_counter() - started
    display(pd.DataFrame([stats]))
    return stats

UTC and thread-normalization checks passed.

## Formal run: six files
The selected method processes all input rows, including the benchmark portion. Per-chunk diagnostics are printed and retained in notebook output. Per-file summaries are displayed immediately and consolidated in run_summary.json after success.

In [7]:
formal_started = time.perf_counter()
summaries = []
for source in SOURCES:
    print('Processing:', source.name, flush=True)
    summaries.append(process_file(source))
formal_seconds = time.perf_counter() - formal_started

Processing: wallstreetbets_comment_part1.csv
{'file': 'wallstreetbets_comment_part1.csv', 'chunk': 1, 'raw': {'row_count': 50000, 'date_min': '1970-01-01T00:00:01+00:00', 'date_max': '2015-04-28T13:33:04+00:00', 'invalid_date_count': 13, 'unique_authors': 4300, 'unique_threads': 4247, 'missing_comment_id_count': 13}, 'matched': {'row_count': 39254, 'date_min': '2012-04-11T16:46:43+00:00', 'date_max': '2015-04-28T13:18:59+00:00', 'invalid_date_count': 9, 'unique_authors': 3857, 'unique_threads': 4108, 'missing_comment_id_count': 9}, 'enriched': {'unique_threads': 4108, 'missing_thread_count': 9, 'missing_parent_id_count': 9, 'invalid_timestamp_count': 9, 'date_min': '2012-04-11T16:46:43+00:00', 'date_max': '2015-04-28T13:18:59+00:00', 'invalid_date_count': 9, 'row_count': 39254, 'unique_authors': 3857}, 'unique_matched_tickers': 1449, 'seconds': 0.852}
{'file': 'wallstreetbets_comment_part1.csv', 'chunk': 2, 'raw': {'row_count': 50000, 'date_min': '1970-01-01T00:00:03+00:00', 'date_max': '2015-08-26T20:23:11+00:00', 'invalid_date_count': 1, 'unique_authors': 3727, 'unique_threads': 3675, 'missing_comment_id_count': 1}, 'matched': {'row_count': 35864, 'date_min': '2015-04-28T13:38:35+00:00', 'date_max': '2015-08-26T20:23:11+00:00', 'invalid_date_count': 1, 'unique_authors': 3210, 'unique_threads': 3510, 'missing_comment_id_count': 1}, 'enriched': {'unique_threads': 3510, 'missing_thread_count': 1, 'missing_parent_id_count': 1, 'invalid_timestamp_count': 1, 'date_min': '2015-04-28T13:38:35+00:00', 'date_max': '2015-08-26T20:23:11+00:00', 'invalid_date_count': 1, 'row_count': 35864, 'unique_authors': 3210}, 'unique_matched_tickers': 1301, 'seconds': 0.957}
{'file': 'wallstreetbets_comment_part1.csv', 'chunk': 3, 'raw': {'row_count': 50000, 'date_min': '2015-08-26T20:23:26+00:00', 'date_max': '2015-11-09T22:36:04+00:00', 'invalid_date_count': 0, 'unique_authors': 4033, 'unique_threads': 3323, 'missing_comment_id_count': 0}, 'matched': {'row_count': 35659, 'date_min': '2015-08-26T20:23:26+00:00', 'date_max': '2015-11-09T22:36:04+00:00', 'invalid_date_count': 0, 'unique_authors': 3436, 'unique_threads': 3175, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 3175, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2015-08-26T20:23:26+00:00', 'date_max': '2015-11-09T22:36:04+00:00', 'invalid_date_count': 0, 'row_count': 35659, 'unique_authors': 3436}, 'unique_matched_tickers': 1329, 'seconds': 0.703}
{'file': 'wallstreetbets_comment_part1.csv', 'chunk': 4, 'raw': {'row_count': 50000, 'date_min': '1970-01-01T00:00:03+00:00', 'date_max': '2016-01-15T23:19:30+00:00', 'invalid_date_count': 4, 'unique_authors': 4243, 'unique_threads': 2864, 'missing_comment_id_count': 4}, 'matched': {'row_count': 34539, 'date_min': '2015-11-09T22:40:18+00:00', 'date_max': '2016-01-15T23:19:30+00:00', 'invalid_date_count': 2, 'unique_authors': 3650, 'unique_threads': 2691, 'missing_comment_id_count': 2}, 'enriched': {'unique_threads': 2691, 'missing_thread_count': 2, 'missing_parent_id_count': 2, 'invalid_timestamp_count': 2, 'date_min': '2015-11-09T22:40:18+00:00', 'date_max': '2016-01-15T23:19:30+00:00', 'invalid_date_count': 2, 'row_count': 34539, 'unique_authors': 3650}, 'unique_matched_tickers': 1283, 'seconds': 0.718}
{'file': 'wallstreetbets_comment_part1.csv', 'chunk': 5, 'raw': {'row_count': 50000, 'date_min': '1970-01-01T00:00:01+00:00', 'date_max': '2016-03-07T02:09:30+00:00', 'invalid_date_count': 4, 'unique_authors': 4827, 'unique_threads': 2991, 'missing_comment_id_count': 4}, 'matched': {'row_count': 34289, 'date_min': '2016-01-15T23:19:52+00:00', 'date_max': '2016-03-07T02:09:30+00:00', 'invalid_date_count': 2, 'unique_authors': 3999, 'unique_threads': 2824, 'missing_comment_id_count': 2}, 'enriched': {'unique_threads': 2824, 'missing_thread_count': 2, 'missing_parent_id_count': 2, 'invalid_timestamp_count': 2, 'date_min': '2016-01-15T23:19:52+00:00', 'date_max': '2016-03-07T02:09:30+00:00', 'invalid_date_count': 2, 'row_count': 34289, 'unique_authors': 3999}, 'unique_matched_tickers': 1188, 'seconds': 0.708}
{'file': 'wallstreetbets_comment_part1.csv', 'chunk': 6, 'raw': {'row_count': 50000, 'date_min': '1970-01-01T00:00:03+00:00', 'date_max': '2016-04-18T03:03:10+00:00', 'invalid_date_count': 1, 'unique_authors': 4979, 'unique_threads': 3094, 'missing_comment_id_count': 1}, 'matched': {'row_count': 34701, 'date_min': '2016-03-07T02:12:50+00:00', 'date_max': '2016-04-18T03:02:08+00:00', 'invalid_date_count': 0, 'unique_authors': 4187, 'unique_threads': 2924, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2924, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-03-07T02:12:50+00:00', 'date_max': '2016-04-18T03:02:08+00:00', 'invalid_date_count': 0, 'row_count': 34701, 'unique_authors': 4187}, 'unique_matched_tickers': 1313, 'seconds': 0.741}
{'file': 'wallstreetbets_comment_part1.csv', 'chunk': 7, 'raw': {'row_count': 10753, 'date_min': '2016-04-18T03:04:24+00:00', 'date_max': '2016-04-25T12:28:09+00:00', 'invalid_date_count': 0, 'unique_authors': 2049, 'unique_threads': 774, 'missing_comment_id_count': 0}, 'matched': {'row_count': 7210, 'date_min': '2016-04-18T03:04:24+00:00', 'date_max': '2016-04-25T12:28:09+00:00', 'invalid_date_count': 0, 'unique_authors': 1645, 'unique_threads': 707, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 707, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-04-18T03:04:24+00:00', 'date_max': '2016-04-25T12:28:09+00:00', 'invalid_date_count': 0, 'row_count': 7210, 'unique_authors': 1645}, 'unique_matched_tickers': 707, 'seconds': 0.185}

,file,raw_row_count,matched_comment_count,comments_with_ge2_tickers,mention_row_count,raw_missing_comment_id_count,matched_missing_comment_id_count,raw_date_min,raw_date_max,raw_invalid_date_count,matched_date_min,matched_date_max,matched_invalid_date_count,match_rate,unique_raw_authors,unique_raw_threads,unique_matched_authors,unique_matched_threads,unique_matched_tickers,processing_seconds
0,wallstreetbets_comment_part1.csv,310753,221516,145852,660525,23,14,1970-01-01T00:00:01+00:00,2016-04-25T12:28:09+00:00,23,2012-04-11T16:46:43+00:00,2016-04-25T12:28:09+00:00,14,0.712836,16596,20315,14439,19409,2615,5.871178

Processing: wallstreetbets_comment_part2.csv
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 1, 'raw': {'row_count': 50000, 'date_min': '2016-04-25T12:29:23+00:00', 'date_max': '2016-06-04T23:33:04+00:00', 'invalid_date_count': 0, 'unique_authors': 4924, 'unique_threads': 2994, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33890, 'date_min': '2016-04-25T12:29:23+00:00', 'date_max': '2016-06-04T23:33:04+00:00', 'invalid_date_count': 0, 'unique_authors': 4128, 'unique_threads': 2804, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2804, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-04-25T12:29:23+00:00', 'date_max': '2016-06-04T23:33:04+00:00', 'invalid_date_count': 0, 'row_count': 33890, 'unique_authors': 4128}, 'unique_matched_tickers': 1296, 'seconds': 0.687}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 2, 'raw': {'row_count': 50000, 'date_min': '2016-06-04T23:37:41+00:00', 'date_max': '2016-07-11T14:56:17+00:00', 'invalid_date_count': 0, 'unique_authors': 5394, 'unique_threads': 3306, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33510, 'date_min': '2016-06-04T23:37:45+00:00', 'date_max': '2016-07-11T14:55:40+00:00', 'invalid_date_count': 0, 'unique_authors': 4390, 'unique_threads': 3103, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 3103, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-06-04T23:37:45+00:00', 'date_max': '2016-07-11T14:55:40+00:00', 'invalid_date_count': 0, 'row_count': 33510, 'unique_authors': 4390}, 'unique_matched_tickers': 1206, 'seconds': 0.65}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 3, 'raw': {'row_count': 50000, 'date_min': '2016-07-11T14:56:28+00:00', 'date_max': '2016-08-06T21:34:09+00:00', 'invalid_date_count': 0, 'unique_authors': 5315, 'unique_threads': 3143, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33497, 'date_min': '2016-07-11T14:56:28+00:00', 'date_max': '2016-08-06T21:33:58+00:00', 'invalid_date_count': 0, 'unique_authors': 4388, 'unique_threads': 2977, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2977, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-07-11T14:56:28+00:00', 'date_max': '2016-08-06T21:33:58+00:00', 'invalid_date_count': 0, 'row_count': 33497, 'unique_authors': 4388}, 'unique_matched_tickers': 1242, 'seconds': 0.682}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 4, 'raw': {'row_count': 50000, 'date_min': '2016-08-06T21:35:09+00:00', 'date_max': '2016-09-06T21:42:37+00:00', 'invalid_date_count': 0, 'unique_authors': 5545, 'unique_threads': 3477, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32331, 'date_min': '2016-08-06T21:39:06+00:00', 'date_max': '2016-09-06T21:42:37+00:00', 'invalid_date_count': 0, 'unique_authors': 4519, 'unique_threads': 3244, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 3244, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-08-06T21:39:06+00:00', 'date_max': '2016-09-06T21:42:37+00:00', 'invalid_date_count': 0, 'row_count': 32331, 'unique_authors': 4519}, 'unique_matched_tickers': 1168, 'seconds': 0.704}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 5, 'raw': {'row_count': 50000, 'date_min': '2016-09-06T21:42:46+00:00', 'date_max': '2016-10-06T00:47:51+00:00', 'invalid_date_count': 0, 'unique_authors': 5498, 'unique_threads': 3202, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31441, 'date_min': '2016-09-06T21:43:10+00:00', 'date_max': '2016-10-06T00:47:51+00:00', 'invalid_date_count': 0, 'unique_authors': 4428, 'unique_threads': 3003, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 3003, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-09-06T21:43:10+00:00', 'date_max': '2016-10-06T00:47:51+00:00', 'invalid_date_count': 0, 'row_count': 31441, 'unique_authors': 4428}, 'unique_matched_tickers': 1134, 'seconds': 0.7}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 6, 'raw': {'row_count': 50000, 'date_min': '2016-10-06T00:47:52+00:00', 'date_max': '2016-11-09T21:47:12+00:00', 'invalid_date_count': 0, 'unique_authors': 5597, 'unique_threads': 3328, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31955, 'date_min': '2016-10-06T00:47:52+00:00', 'date_max': '2016-11-09T21:47:06+00:00', 'invalid_date_count': 0, 'unique_authors': 4503, 'unique_threads': 3091, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 3091, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-10-06T00:47:52+00:00', 'date_max': '2016-11-09T21:47:06+00:00', 'invalid_date_count': 0, 'row_count': 31955, 'unique_authors': 4503}, 'unique_matched_tickers': 1140, 'seconds': 0.644}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 7, 'raw': {'row_count': 50000, 'date_min': '2016-11-09T21:47:21+00:00', 'date_max': '2016-12-11T19:10:16+00:00', 'invalid_date_count': 0, 'unique_authors': 6132, 'unique_threads': 3587, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32288, 'date_min': '2016-11-09T21:47:21+00:00', 'date_max': '2016-12-11T19:08:45+00:00', 'invalid_date_count': 0, 'unique_authors': 4885, 'unique_threads': 3351, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 3351, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-11-09T21:47:21+00:00', 'date_max': '2016-12-11T19:08:45+00:00', 'invalid_date_count': 0, 'row_count': 32288, 'unique_authors': 4885}, 'unique_matched_tickers': 1218, 'seconds': 0.759}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 8, 'raw': {'row_count': 50000, 'date_min': '2016-12-11T19:10:26+00:00', 'date_max': '2017-01-12T17:39:26+00:00', 'invalid_date_count': 0, 'unique_authors': 6123, 'unique_threads': 3262, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31188, 'date_min': '2016-12-11T19:10:26+00:00', 'date_max': '2017-01-12T17:37:22+00:00', 'invalid_date_count': 0, 'unique_authors': 4935, 'unique_threads': 3036, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 3036, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2016-12-11T19:10:26+00:00', 'date_max': '2017-01-12T17:37:22+00:00', 'invalid_date_count': 0, 'row_count': 31188, 'unique_authors': 4935}, 'unique_matched_tickers': 1196, 'seconds': 0.676}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 9, 'raw': {'row_count': 50000, 'date_min': '2017-01-12T17:39:52+00:00', 'date_max': '2017-02-06T05:23:15+00:00', 'invalid_date_count': 0, 'unique_authors': 9330, 'unique_threads': 2486, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32023, 'date_min': '2017-01-12T17:39:52+00:00', 'date_max': '2017-02-06T05:22:40+00:00', 'invalid_date_count': 0, 'unique_authors': 6987, 'unique_threads': 2286, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2286, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-01-12T17:39:52+00:00', 'date_max': '2017-02-06T05:22:40+00:00', 'invalid_date_count': 0, 'row_count': 32023, 'unique_authors': 6987}, 'unique_matched_tickers': 1261, 'seconds': 0.603}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 10, 'raw': {'row_count': 50000, 'date_min': '2017-02-06T05:23:58+00:00', 'date_max': '2017-02-28T16:09:12+00:00', 'invalid_date_count': 0, 'unique_authors': 6154, 'unique_threads': 2815, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32929, 'date_min': '2017-02-06T05:23:58+00:00', 'date_max': '2017-02-28T16:09:12+00:00', 'invalid_date_count': 0, 'unique_authors': 5019, 'unique_threads': 2620, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2620, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-02-06T05:23:58+00:00', 'date_max': '2017-02-28T16:09:12+00:00', 'invalid_date_count': 0, 'row_count': 32929, 'unique_authors': 5019}, 'unique_matched_tickers': 1166, 'seconds': 0.783}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 11, 'raw': {'row_count': 50000, 'date_min': '2017-02-28T16:09:23+00:00', 'date_max': '2017-03-21T11:45:51+00:00', 'invalid_date_count': 0, 'unique_authors': 5908, 'unique_threads': 2469, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32128, 'date_min': '2017-02-28T16:09:23+00:00', 'date_max': '2017-03-21T11:45:51+00:00', 'invalid_date_count': 0, 'unique_authors': 4871, 'unique_threads': 2276, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2276, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-02-28T16:09:23+00:00', 'date_max': '2017-03-21T11:45:51+00:00', 'invalid_date_count': 0, 'row_count': 32128, 'unique_authors': 4871}, 'unique_matched_tickers': 1092, 'seconds': 0.667}
{'file': 'wallstreetbets_comment_part2.csv', 'chunk': 12, 'raw': {'row_count': 25124, 'date_min': '2017-03-21T11:45:56+00:00', 'date_max': '2017-04-01T06:13:54+00:00', 'invalid_date_count': 0, 'unique_authors': 3673, 'unique_threads': 1178, 'missing_comment_id_count': 0}, 'matched': {'row_count': 16176, 'date_min': '2017-03-21T11:48:29+00:00', 'date_max': '2017-04-01T06:13:54+00:00', 'invalid_date_count': 0, 'unique_authors': 3002, 'unique_threads': 1091, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1091, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-03-21T11:48:29+00:00', 'date_max': '2017-04-01T06:13:54+00:00', 'invalid_date_count': 0, 'row_count': 16176, 'unique_authors': 3002}, 'unique_matched_tickers': 866, 'seconds': 0.462}

,file,raw_row_count,matched_comment_count,comments_with_ge2_tickers,mention_row_count,raw_missing_comment_id_count,matched_missing_comment_id_count,raw_date_min,raw_date_max,raw_invalid_date_count,matched_date_min,matched_date_max,matched_invalid_date_count,match_rate,unique_raw_authors,unique_raw_threads,unique_matched_authors,unique_matched_threads,unique_matched_tickers,processing_seconds
0,wallstreetbets_comment_part2.csv,575124,373356,229841,983294,0,0,2016-04-25T12:29:23+00:00,2017-04-01T06:13:54+00:00,0,2016-04-25T12:29:23+00:00,2017-04-01T06:13:54+00:00,0,0.649175,31225,33094,25508,31185,2883,9.919673

Processing: wallstreetbets_comment_part3.csv
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 1, 'raw': {'row_count': 50000, 'date_min': '2017-04-01T05:41:35+00:00', 'date_max': '2017-04-27T20:07:06+00:00', 'invalid_date_count': 0, 'unique_authors': 6592, 'unique_threads': 2561, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31658, 'date_min': '2017-04-01T05:41:35+00:00', 'date_max': '2017-04-27T20:07:06+00:00', 'invalid_date_count': 0, 'unique_authors': 5293, 'unique_threads': 2337, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2337, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-04-01T05:41:35+00:00', 'date_max': '2017-04-27T20:07:06+00:00', 'invalid_date_count': 0, 'row_count': 31658, 'unique_authors': 5293}, 'unique_matched_tickers': 1135, 'seconds': 0.646}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 2, 'raw': {'row_count': 50000, 'date_min': '2017-04-27T20:07:26+00:00', 'date_max': '2017-05-24T16:22:12+00:00', 'invalid_date_count': 0, 'unique_authors': 6179, 'unique_threads': 2612, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30830, 'date_min': '2017-04-27T20:07:26+00:00', 'date_max': '2017-05-24T16:22:12+00:00', 'invalid_date_count': 0, 'unique_authors': 4914, 'unique_threads': 2383, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2383, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-04-27T20:07:26+00:00', 'date_max': '2017-05-24T16:22:12+00:00', 'invalid_date_count': 0, 'row_count': 30830, 'unique_authors': 4914}, 'unique_matched_tickers': 1119, 'seconds': 0.608}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 3, 'raw': {'row_count': 50000, 'date_min': '2017-05-24T16:22:14+00:00', 'date_max': '2017-06-21T16:22:27+00:00', 'invalid_date_count': 0, 'unique_authors': 5867, 'unique_threads': 2868, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32105, 'date_min': '2017-05-24T16:22:14+00:00', 'date_max': '2017-06-21T16:22:27+00:00', 'invalid_date_count': 0, 'unique_authors': 4737, 'unique_threads': 2670, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2670, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-05-24T16:22:14+00:00', 'date_max': '2017-06-21T16:22:27+00:00', 'invalid_date_count': 0, 'row_count': 32105, 'unique_authors': 4737}, 'unique_matched_tickers': 1078, 'seconds': 0.654}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 4, 'raw': {'row_count': 50000, 'date_min': '2017-06-21T16:22:39+00:00', 'date_max': '2017-07-13T02:21:25+00:00', 'invalid_date_count': 0, 'unique_authors': 6374, 'unique_threads': 2278, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32292, 'date_min': '2017-06-21T16:22:39+00:00', 'date_max': '2017-07-13T02:21:13+00:00', 'invalid_date_count': 0, 'unique_authors': 5151, 'unique_threads': 2095, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2095, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-06-21T16:22:39+00:00', 'date_max': '2017-07-13T02:21:13+00:00', 'invalid_date_count': 0, 'row_count': 32292, 'unique_authors': 5151}, 'unique_matched_tickers': 1044, 'seconds': 0.776}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 5, 'raw': {'row_count': 50000, 'date_min': '2017-07-13T02:21:29+00:00', 'date_max': '2017-08-03T17:59:04+00:00', 'invalid_date_count': 0, 'unique_authors': 7251, 'unique_threads': 2728, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32620, 'date_min': '2017-07-13T02:21:29+00:00', 'date_max': '2017-08-03T17:59:04+00:00', 'invalid_date_count': 0, 'unique_authors': 5705, 'unique_threads': 2518, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2518, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-07-13T02:21:29+00:00', 'date_max': '2017-08-03T17:59:04+00:00', 'invalid_date_count': 0, 'row_count': 32620, 'unique_authors': 5705}, 'unique_matched_tickers': 1323, 'seconds': 0.668}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 6, 'raw': {'row_count': 50000, 'date_min': '2017-08-03T17:59:07+00:00', 'date_max': '2017-08-29T11:49:07+00:00', 'invalid_date_count': 0, 'unique_authors': 7350, 'unique_threads': 2590, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30883, 'date_min': '2017-08-03T17:59:07+00:00', 'date_max': '2017-08-29T11:49:07+00:00', 'invalid_date_count': 0, 'unique_authors': 5734, 'unique_threads': 2387, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2387, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-08-03T17:59:07+00:00', 'date_max': '2017-08-29T11:49:07+00:00', 'invalid_date_count': 0, 'row_count': 30883, 'unique_authors': 5734}, 'unique_matched_tickers': 1082, 'seconds': 0.665}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 7, 'raw': {'row_count': 50000, 'date_min': '2017-08-29T11:52:32+00:00', 'date_max': '2017-09-27T22:28:40+00:00', 'invalid_date_count': 0, 'unique_authors': 7332, 'unique_threads': 2909, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31923, 'date_min': '2017-08-29T11:52:42+00:00', 'date_max': '2017-09-27T22:28:40+00:00', 'invalid_date_count': 0, 'unique_authors': 5782, 'unique_threads': 2716, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2716, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-08-29T11:52:42+00:00', 'date_max': '2017-09-27T22:28:40+00:00', 'invalid_date_count': 0, 'row_count': 31923, 'unique_authors': 5782}, 'unique_matched_tickers': 1188, 'seconds': 0.669}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 8, 'raw': {'row_count': 50000, 'date_min': '2017-09-27T22:28:42+00:00', 'date_max': '2017-10-22T22:35:46+00:00', 'invalid_date_count': 0, 'unique_authors': 6932, 'unique_threads': 2851, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31731, 'date_min': '2017-09-27T22:30:09+00:00', 'date_max': '2017-10-22T22:35:46+00:00', 'invalid_date_count': 0, 'unique_authors': 5473, 'unique_threads': 2655, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2655, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-09-27T22:30:09+00:00', 'date_max': '2017-10-22T22:35:46+00:00', 'invalid_date_count': 0, 'row_count': 31731, 'unique_authors': 5473}, 'unique_matched_tickers': 1224, 'seconds': 0.622}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 9, 'raw': {'row_count': 50000, 'date_min': '2017-10-22T22:38:14+00:00', 'date_max': '2017-11-14T04:02:28+00:00', 'invalid_date_count': 0, 'unique_authors': 7154, 'unique_threads': 2906, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31636, 'date_min': '2017-10-22T22:42:51+00:00', 'date_max': '2017-11-14T03:59:18+00:00', 'invalid_date_count': 0, 'unique_authors': 5614, 'unique_threads': 2659, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2659, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-10-22T22:42:51+00:00', 'date_max': '2017-11-14T03:59:18+00:00', 'invalid_date_count': 0, 'row_count': 31636, 'unique_authors': 5614}, 'unique_matched_tickers': 1137, 'seconds': 0.747}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 10, 'raw': {'row_count': 50000, 'date_min': '2017-11-14T04:03:29+00:00', 'date_max': '2017-12-07T03:26:49+00:00', 'invalid_date_count': 0, 'unique_authors': 7511, 'unique_threads': 2756, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31518, 'date_min': '2017-11-14T04:03:29+00:00', 'date_max': '2017-12-07T03:25:35+00:00', 'invalid_date_count': 0, 'unique_authors': 5923, 'unique_threads': 2527, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2527, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-11-14T04:03:29+00:00', 'date_max': '2017-12-07T03:25:35+00:00', 'invalid_date_count': 0, 'row_count': 31518, 'unique_authors': 5923}, 'unique_matched_tickers': 1073, 'seconds': 0.648}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 11, 'raw': {'row_count': 50000, 'date_min': '2017-12-07T03:27:12+00:00', 'date_max': '2018-01-08T03:57:24+00:00', 'invalid_date_count': 0, 'unique_authors': 7846, 'unique_threads': 2458, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30673, 'date_min': '2017-12-07T03:27:12+00:00', 'date_max': '2018-01-08T03:57:13+00:00', 'invalid_date_count': 0, 'unique_authors': 6177, 'unique_threads': 2244, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2244, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2017-12-07T03:27:12+00:00', 'date_max': '2018-01-08T03:57:13+00:00', 'invalid_date_count': 0, 'row_count': 30673, 'unique_authors': 6177}, 'unique_matched_tickers': 1188, 'seconds': 0.631}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 12, 'raw': {'row_count': 50000, 'date_min': '2018-01-08T03:57:43+00:00', 'date_max': '2018-01-30T04:52:44+00:00', 'invalid_date_count': 0, 'unique_authors': 7022, 'unique_threads': 2686, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31388, 'date_min': '2018-01-08T03:59:34+00:00', 'date_max': '2018-01-30T04:52:38+00:00', 'invalid_date_count': 0, 'unique_authors': 5500, 'unique_threads': 2487, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2487, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-01-08T03:59:34+00:00', 'date_max': '2018-01-30T04:52:38+00:00', 'invalid_date_count': 0, 'row_count': 31388, 'unique_authors': 5500}, 'unique_matched_tickers': 1136, 'seconds': 0.67}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 13, 'raw': {'row_count': 50000, 'date_min': '2018-01-30T04:53:17+00:00', 'date_max': '2018-02-12T01:13:45+00:00', 'invalid_date_count': 0, 'unique_authors': 7606, 'unique_threads': 3403, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30665, 'date_min': '2018-01-30T04:53:19+00:00', 'date_max': '2018-02-12T01:13:45+00:00', 'invalid_date_count': 0, 'unique_authors': 5830, 'unique_threads': 3113, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 3113, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-01-30T04:53:19+00:00', 'date_max': '2018-02-12T01:13:45+00:00', 'invalid_date_count': 0, 'row_count': 30665, 'unique_authors': 5830}, 'unique_matched_tickers': 1009, 'seconds': 0.644}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 14, 'raw': {'row_count': 50000, 'date_min': '2018-02-12T01:14:01+00:00', 'date_max': '2018-03-02T15:46:35+00:00', 'invalid_date_count': 0, 'unique_authors': 7101, 'unique_threads': 2929, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31195, 'date_min': '2018-02-12T01:14:01+00:00', 'date_max': '2018-03-02T15:46:35+00:00', 'invalid_date_count': 0, 'unique_authors': 5505, 'unique_threads': 2712, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2712, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-02-12T01:14:01+00:00', 'date_max': '2018-03-02T15:46:35+00:00', 'invalid_date_count': 0, 'row_count': 31195, 'unique_authors': 5505}, 'unique_matched_tickers': 1109, 'seconds': 0.674}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 15, 'raw': {'row_count': 50000, 'date_min': '2018-03-02T15:46:37+00:00', 'date_max': '2018-03-21T03:47:20+00:00', 'invalid_date_count': 0, 'unique_authors': 7546, 'unique_threads': 2875, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31452, 'date_min': '2018-03-02T15:46:48+00:00', 'date_max': '2018-03-21T03:47:20+00:00', 'invalid_date_count': 0, 'unique_authors': 5805, 'unique_threads': 2642, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2642, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-03-02T15:46:48+00:00', 'date_max': '2018-03-21T03:47:20+00:00', 'invalid_date_count': 0, 'row_count': 31452, 'unique_authors': 5805}, 'unique_matched_tickers': 1107, 'seconds': 0.717}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 16, 'raw': {'row_count': 50000, 'date_min': '2018-03-21T03:47:41+00:00', 'date_max': '2018-04-05T03:21:01+00:00', 'invalid_date_count': 0, 'unique_authors': 7301, 'unique_threads': 2878, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31973, 'date_min': '2018-03-21T03:47:41+00:00', 'date_max': '2018-04-05T03:21:01+00:00', 'invalid_date_count': 0, 'unique_authors': 5778, 'unique_threads': 2630, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2630, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-03-21T03:47:41+00:00', 'date_max': '2018-04-05T03:21:01+00:00', 'invalid_date_count': 0, 'row_count': 31973, 'unique_authors': 5778}, 'unique_matched_tickers': 1024, 'seconds': 0.668}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 17, 'raw': {'row_count': 50000, 'date_min': '2018-04-05T03:21:12+00:00', 'date_max': '2018-04-21T04:19:29+00:00', 'invalid_date_count': 0, 'unique_authors': 7177, 'unique_threads': 2452, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32073, 'date_min': '2018-04-05T03:21:45+00:00', 'date_max': '2018-04-21T04:18:31+00:00', 'invalid_date_count': 0, 'unique_authors': 5603, 'unique_threads': 2247, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2247, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-04-05T03:21:45+00:00', 'date_max': '2018-04-21T04:18:31+00:00', 'invalid_date_count': 0, 'row_count': 32073, 'unique_authors': 5603}, 'unique_matched_tickers': 998, 'seconds': 0.702}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 18, 'raw': {'row_count': 50000, 'date_min': '2018-04-21T04:19:55+00:00', 'date_max': '2018-05-07T21:09:17+00:00', 'invalid_date_count': 0, 'unique_authors': 7045, 'unique_threads': 2807, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32538, 'date_min': '2018-04-21T04:19:55+00:00', 'date_max': '2018-05-07T21:09:17+00:00', 'invalid_date_count': 0, 'unique_authors': 5596, 'unique_threads': 2592, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2592, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-04-21T04:19:55+00:00', 'date_max': '2018-05-07T21:09:17+00:00', 'invalid_date_count': 0, 'row_count': 32538, 'unique_authors': 5596}, 'unique_matched_tickers': 1048, 'seconds': 0.697}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 19, 'raw': {'row_count': 50000, 'date_min': '2018-05-07T21:09:22+00:00', 'date_max': '2018-05-23T03:51:01+00:00', 'invalid_date_count': 0, 'unique_authors': 6737, 'unique_threads': 2778, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32641, 'date_min': '2018-05-07T21:09:53+00:00', 'date_max': '2018-05-23T03:51:01+00:00', 'invalid_date_count': 0, 'unique_authors': 5375, 'unique_threads': 2603, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2603, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-05-07T21:09:53+00:00', 'date_max': '2018-05-23T03:51:01+00:00', 'invalid_date_count': 0, 'row_count': 32641, 'unique_authors': 5375}, 'unique_matched_tickers': 1011, 'seconds': 0.706}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 20, 'raw': {'row_count': 50000, 'date_min': '2018-05-23T03:51:17+00:00', 'date_max': '2018-06-06T15:02:44+00:00', 'invalid_date_count': 0, 'unique_authors': 6941, 'unique_threads': 2632, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32337, 'date_min': '2018-05-23T03:52:03+00:00', 'date_max': '2018-06-06T15:02:41+00:00', 'invalid_date_count': 0, 'unique_authors': 5522, 'unique_threads': 2444, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2444, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-05-23T03:52:03+00:00', 'date_max': '2018-06-06T15:02:41+00:00', 'invalid_date_count': 0, 'row_count': 32337, 'unique_authors': 5522}, 'unique_matched_tickers': 1055, 'seconds': 0.726}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 21, 'raw': {'row_count': 50000, 'date_min': '2018-06-06T15:02:58+00:00', 'date_max': '2018-06-18T00:51:23+00:00', 'invalid_date_count': 0, 'unique_authors': 7258, 'unique_threads': 2983, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31979, 'date_min': '2018-06-06T15:02:58+00:00', 'date_max': '2018-06-18T00:51:23+00:00', 'invalid_date_count': 0, 'unique_authors': 5685, 'unique_threads': 2785, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2785, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-06-06T15:02:58+00:00', 'date_max': '2018-06-18T00:51:23+00:00', 'invalid_date_count': 0, 'row_count': 31979, 'unique_authors': 5685}, 'unique_matched_tickers': 1069, 'seconds': 0.684}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 22, 'raw': {'row_count': 50000, 'date_min': '2018-06-18T00:51:26+00:00', 'date_max': '2018-06-27T14:48:18+00:00', 'invalid_date_count': 0, 'unique_authors': 6754, 'unique_threads': 3012, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31187, 'date_min': '2018-06-18T00:51:26+00:00', 'date_max': '2018-06-27T14:47:10+00:00', 'invalid_date_count': 0, 'unique_authors': 5335, 'unique_threads': 2794, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2794, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-06-18T00:51:26+00:00', 'date_max': '2018-06-27T14:47:10+00:00', 'invalid_date_count': 0, 'row_count': 31187, 'unique_authors': 5335}, 'unique_matched_tickers': 1058, 'seconds': 0.669}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 23, 'raw': {'row_count': 50000, 'date_min': '2018-06-27T14:48:32+00:00', 'date_max': '2018-07-10T23:27:56+00:00', 'invalid_date_count': 0, 'unique_authors': 7407, 'unique_threads': 2698, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31974, 'date_min': '2018-06-27T14:48:32+00:00', 'date_max': '2018-07-10T23:27:56+00:00', 'invalid_date_count': 0, 'unique_authors': 5834, 'unique_threads': 2494, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2494, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-06-27T14:48:32+00:00', 'date_max': '2018-07-10T23:27:56+00:00', 'invalid_date_count': 0, 'row_count': 31974, 'unique_authors': 5834}, 'unique_matched_tickers': 1080, 'seconds': 0.745}
{'file': 'wallstreetbets_comment_part3.csv', 'chunk': 24, 'raw': {'row_count': 50000, 'date_min': '2018-07-10T23:27:58+00:00', 'date_max': '2018-07-23T21:35:55+00:00', 'invalid_date_count': 0, 'unique_authors': 7006, 'unique_threads': 2637, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32264, 'date_min': '2018-07-10T23:27:58+00:00', 'date_max': '2018-07-23T21:35:52+00:00', 'invalid_date_count': 0, 'unique_authors': 5548, 'unique_threads': 2439, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 2439, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-07-10T23:27:58+00:00', 'date_max': '2018-07-23T21:35:52+00:00', 'invalid_date_count': 0, 'row_count': 32264, 'unique_authors': 5548}, 'unique_matched_tickers': 1037, 'seconds': 0.682}

,file,raw_row_count,matched_comment_count,comments_with_ge2_tickers,mention_row_count,raw_missing_comment_id_count,matched_missing_comment_id_count,raw_date_min,raw_date_max,raw_invalid_date_count,matched_date_min,matched_date_max,matched_invalid_date_count,match_rate,unique_raw_authors,unique_raw_threads,unique_matched_authors,unique_matched_threads,unique_matched_tickers,processing_seconds
0,wallstreetbets_comment_part3.csv,2218513,1437717,856162,3538335,0,0,2017-04-01T05:41:35+00:00,2018-12-31T00:05:11+00:00,0,2017-04-01T05:41:35+00:00,2018-12-31T00:05:03+00:00,0,0.648054,95173,98161,77224,92081,3720,37.491929

Processing: wallstreetbets_comment_part4.csv
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 1, 'raw': {'row_count': 50000, 'date_min': '2018-12-31T00:00:33+00:00', 'date_max': '2019-01-07T16:42:29+00:00', 'invalid_date_count': 0, 'unique_authors': 8334, 'unique_threads': 1323, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32913, 'date_min': '2018-12-31T00:00:33+00:00', 'date_max': '2019-01-07T16:42:29+00:00', 'invalid_date_count': 0, 'unique_authors': 6392, 'unique_threads': 1183, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1183, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2018-12-31T00:00:33+00:00', 'date_max': '2019-01-07T16:42:29+00:00', 'invalid_date_count': 0, 'row_count': 32913, 'unique_authors': 6392}, 'unique_matched_tickers': 974, 'seconds': 0.65}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 2, 'raw': {'row_count': 50000, 'date_min': '2019-01-07T16:42:37+00:00', 'date_max': '2019-01-14T10:32:16+00:00', 'invalid_date_count': 0, 'unique_authors': 7847, 'unique_threads': 1140, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32334, 'date_min': '2019-01-07T16:42:37+00:00', 'date_max': '2019-01-14T10:32:16+00:00', 'invalid_date_count': 0, 'unique_authors': 5842, 'unique_threads': 1029, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1029, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-01-07T16:42:37+00:00', 'date_max': '2019-01-14T10:32:16+00:00', 'invalid_date_count': 0, 'row_count': 32334, 'unique_authors': 5842}, 'unique_matched_tickers': 978, 'seconds': 0.658}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 3, 'raw': {'row_count': 50000, 'date_min': '2019-01-14T10:32:35+00:00', 'date_max': '2019-01-19T23:48:22+00:00', 'invalid_date_count': 0, 'unique_authors': 8179, 'unique_threads': 1201, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33073, 'date_min': '2019-01-14T10:32:51+00:00', 'date_max': '2019-01-19T23:47:30+00:00', 'invalid_date_count': 0, 'unique_authors': 6227, 'unique_threads': 1079, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1079, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-01-14T10:32:51+00:00', 'date_max': '2019-01-19T23:47:30+00:00', 'invalid_date_count': 0, 'row_count': 33073, 'unique_authors': 6227}, 'unique_matched_tickers': 937, 'seconds': 0.647}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 4, 'raw': {'row_count': 50000, 'date_min': '2019-01-19T23:48:48+00:00', 'date_max': '2019-01-28T14:10:46+00:00', 'invalid_date_count': 0, 'unique_authors': 9538, 'unique_threads': 1237, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33486, 'date_min': '2019-01-19T23:48:48+00:00', 'date_max': '2019-01-28T14:10:38+00:00', 'invalid_date_count': 0, 'unique_authors': 7372, 'unique_threads': 1080, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1080, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-01-19T23:48:48+00:00', 'date_max': '2019-01-28T14:10:38+00:00', 'invalid_date_count': 0, 'row_count': 33486, 'unique_authors': 7372}, 'unique_matched_tickers': 1030, 'seconds': 0.62}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 5, 'raw': {'row_count': 50000, 'date_min': '2019-01-28T14:10:53+00:00', 'date_max': '2019-02-03T06:05:50+00:00', 'invalid_date_count': 0, 'unique_authors': 8595, 'unique_threads': 1164, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33733, 'date_min': '2019-01-28T14:10:57+00:00', 'date_max': '2019-02-03T06:05:50+00:00', 'invalid_date_count': 0, 'unique_authors': 6825, 'unique_threads': 1047, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1047, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-01-28T14:10:57+00:00', 'date_max': '2019-02-03T06:05:50+00:00', 'invalid_date_count': 0, 'row_count': 33733, 'unique_authors': 6825}, 'unique_matched_tickers': 1048, 'seconds': 0.599}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 6, 'raw': {'row_count': 50000, 'date_min': '2019-02-03T06:08:10+00:00', 'date_max': '2019-02-11T18:16:13+00:00', 'invalid_date_count': 0, 'unique_authors': 8096, 'unique_threads': 1048, 'missing_comment_id_count': 0}, 'matched': {'row_count': 34389, 'date_min': '2019-02-03T06:08:10+00:00', 'date_max': '2019-02-11T18:15:56+00:00', 'invalid_date_count': 0, 'unique_authors': 6487, 'unique_threads': 941, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 941, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-02-03T06:08:10+00:00', 'date_max': '2019-02-11T18:15:56+00:00', 'invalid_date_count': 0, 'row_count': 34389, 'unique_authors': 6487}, 'unique_matched_tickers': 1083, 'seconds': 0.649}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 7, 'raw': {'row_count': 50000, 'date_min': '2019-02-11T18:16:25+00:00', 'date_max': '2019-02-20T13:06:57+00:00', 'invalid_date_count': 0, 'unique_authors': 7943, 'unique_threads': 1130, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33766, 'date_min': '2019-02-11T18:16:25+00:00', 'date_max': '2019-02-20T13:06:38+00:00', 'invalid_date_count': 0, 'unique_authors': 6178, 'unique_threads': 1017, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1017, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-02-11T18:16:25+00:00', 'date_max': '2019-02-20T13:06:38+00:00', 'invalid_date_count': 0, 'row_count': 33766, 'unique_authors': 6178}, 'unique_matched_tickers': 1179, 'seconds': 0.67}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 8, 'raw': {'row_count': 50000, 'date_min': '2019-02-20T13:07:13+00:00', 'date_max': '2019-02-27T22:14:36+00:00', 'invalid_date_count': 0, 'unique_authors': 8124, 'unique_threads': 1175, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33263, 'date_min': '2019-02-20T13:07:13+00:00', 'date_max': '2019-02-27T22:14:36+00:00', 'invalid_date_count': 0, 'unique_authors': 6290, 'unique_threads': 1024, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1024, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-02-20T13:07:13+00:00', 'date_max': '2019-02-27T22:14:36+00:00', 'invalid_date_count': 0, 'row_count': 33263, 'unique_authors': 6290}, 'unique_matched_tickers': 1153, 'seconds': 0.629}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 9, 'raw': {'row_count': 50000, 'date_min': '2019-02-27T22:14:41+00:00', 'date_max': '2019-03-07T19:13:34+00:00', 'invalid_date_count': 0, 'unique_authors': 7274, 'unique_threads': 1089, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33536, 'date_min': '2019-02-27T22:14:41+00:00', 'date_max': '2019-03-07T19:13:34+00:00', 'invalid_date_count': 0, 'unique_authors': 5777, 'unique_threads': 996, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 996, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-02-27T22:14:41+00:00', 'date_max': '2019-03-07T19:13:34+00:00', 'invalid_date_count': 0, 'row_count': 33536, 'unique_authors': 5777}, 'unique_matched_tickers': 1178, 'seconds': 0.694}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 10, 'raw': {'row_count': 50000, 'date_min': '2019-03-07T19:13:47+00:00', 'date_max': '2019-03-15T03:08:15+00:00', 'invalid_date_count': 0, 'unique_authors': 7249, 'unique_threads': 1095, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33280, 'date_min': '2019-03-07T19:14:00+00:00', 'date_max': '2019-03-15T03:08:15+00:00', 'invalid_date_count': 0, 'unique_authors': 5644, 'unique_threads': 980, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 980, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-03-07T19:14:00+00:00', 'date_max': '2019-03-15T03:08:15+00:00', 'invalid_date_count': 0, 'row_count': 33280, 'unique_authors': 5644}, 'unique_matched_tickers': 1074, 'seconds': 0.643}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 11, 'raw': {'row_count': 50000, 'date_min': '2019-03-15T03:08:21+00:00', 'date_max': '2019-03-22T16:09:43+00:00', 'invalid_date_count': 0, 'unique_authors': 7361, 'unique_threads': 1052, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33621, 'date_min': '2019-03-15T03:08:30+00:00', 'date_max': '2019-03-22T16:09:39+00:00', 'invalid_date_count': 0, 'unique_authors': 5834, 'unique_threads': 961, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 961, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-03-15T03:08:30+00:00', 'date_max': '2019-03-22T16:09:39+00:00', 'invalid_date_count': 0, 'row_count': 33621, 'unique_authors': 5834}, 'unique_matched_tickers': 1011, 'seconds': 0.666}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 12, 'raw': {'row_count': 50000, 'date_min': '2019-03-22T16:09:52+00:00', 'date_max': '2019-03-29T17:57:42+00:00', 'invalid_date_count': 0, 'unique_authors': 7508, 'unique_threads': 916, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33576, 'date_min': '2019-03-22T16:09:53+00:00', 'date_max': '2019-03-29T17:57:42+00:00', 'invalid_date_count': 0, 'unique_authors': 5944, 'unique_threads': 818, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 818, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-03-22T16:09:53+00:00', 'date_max': '2019-03-29T17:57:42+00:00', 'invalid_date_count': 0, 'row_count': 33576, 'unique_authors': 5944}, 'unique_matched_tickers': 1013, 'seconds': 0.655}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 13, 'raw': {'row_count': 50000, 'date_min': '2019-03-29T17:57:51+00:00', 'date_max': '2019-04-02T11:49:54+00:00', 'invalid_date_count': 0, 'unique_authors': 35648, 'unique_threads': 469, 'missing_comment_id_count': 0}, 'matched': {'row_count': 21338, 'date_min': '2019-03-29T17:57:51+00:00', 'date_max': '2019-04-02T11:49:49+00:00', 'invalid_date_count': 0, 'unique_authors': 13106, 'unique_threads': 418, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 418, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-03-29T17:57:51+00:00', 'date_max': '2019-04-02T11:49:49+00:00', 'invalid_date_count': 0, 'row_count': 21338, 'unique_authors': 13106}, 'unique_matched_tickers': 834, 'seconds': 0.605}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 14, 'raw': {'row_count': 50000, 'date_min': '2019-04-02T11:49:56+00:00', 'date_max': '2019-04-08T15:33:10+00:00', 'invalid_date_count': 0, 'unique_authors': 14817, 'unique_threads': 987, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30459, 'date_min': '2019-04-02T11:49:56+00:00', 'date_max': '2019-04-08T15:33:07+00:00', 'invalid_date_count': 0, 'unique_authors': 7845, 'unique_threads': 895, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 895, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-04-02T11:49:56+00:00', 'date_max': '2019-04-08T15:33:07+00:00', 'invalid_date_count': 0, 'row_count': 30459, 'unique_authors': 7845}, 'unique_matched_tickers': 982, 'seconds': 0.653}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 15, 'raw': {'row_count': 50000, 'date_min': '2019-04-08T15:33:45+00:00', 'date_max': '2019-04-15T10:48:12+00:00', 'invalid_date_count': 0, 'unique_authors': 7434, 'unique_threads': 1226, 'missing_comment_id_count': 0}, 'matched': {'row_count': 34003, 'date_min': '2019-04-08T15:33:45+00:00', 'date_max': '2019-04-15T10:48:11+00:00', 'invalid_date_count': 0, 'unique_authors': 5857, 'unique_threads': 1102, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1102, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-04-08T15:33:45+00:00', 'date_max': '2019-04-15T10:48:11+00:00', 'invalid_date_count': 0, 'row_count': 34003, 'unique_authors': 5857}, 'unique_matched_tickers': 998, 'seconds': 0.661}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 16, 'raw': {'row_count': 50000, 'date_min': '2019-04-15T10:48:33+00:00', 'date_max': '2019-04-22T21:20:57+00:00', 'invalid_date_count': 0, 'unique_authors': 8008, 'unique_threads': 1258, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33532, 'date_min': '2019-04-15T10:49:21+00:00', 'date_max': '2019-04-22T21:20:57+00:00', 'invalid_date_count': 0, 'unique_authors': 6064, 'unique_threads': 1151, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1151, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-04-15T10:49:21+00:00', 'date_max': '2019-04-22T21:20:57+00:00', 'invalid_date_count': 0, 'row_count': 33532, 'unique_authors': 6064}, 'unique_matched_tickers': 1015, 'seconds': 0.652}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 17, 'raw': {'row_count': 50000, 'date_min': '2019-04-22T21:20:59+00:00', 'date_max': '2019-04-28T12:05:39+00:00', 'invalid_date_count': 0, 'unique_authors': 7610, 'unique_threads': 1310, 'missing_comment_id_count': 0}, 'matched': {'row_count': 34177, 'date_min': '2019-04-22T21:20:59+00:00', 'date_max': '2019-04-28T12:05:39+00:00', 'invalid_date_count': 0, 'unique_authors': 6158, 'unique_threads': 1190, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1190, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-04-22T21:20:59+00:00', 'date_max': '2019-04-28T12:05:39+00:00', 'invalid_date_count': 0, 'row_count': 34177, 'unique_authors': 6158}, 'unique_matched_tickers': 987, 'seconds': 0.661}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 18, 'raw': {'row_count': 50000, 'date_min': '2019-04-28T12:05:44+00:00', 'date_max': '2019-05-03T06:56:41+00:00', 'invalid_date_count': 0, 'unique_authors': 7519, 'unique_threads': 1228, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33403, 'date_min': '2019-04-28T12:05:44+00:00', 'date_max': '2019-05-03T06:56:41+00:00', 'invalid_date_count': 0, 'unique_authors': 5962, 'unique_threads': 1117, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1117, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-04-28T12:05:44+00:00', 'date_max': '2019-05-03T06:56:41+00:00', 'invalid_date_count': 0, 'row_count': 33403, 'unique_authors': 5962}, 'unique_matched_tickers': 1018, 'seconds': 0.694}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 19, 'raw': {'row_count': 50000, 'date_min': '2019-05-03T06:56:42+00:00', 'date_max': '2019-05-08T18:00:46+00:00', 'invalid_date_count': 0, 'unique_authors': 7141, 'unique_threads': 1220, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33183, 'date_min': '2019-05-03T06:56:42+00:00', 'date_max': '2019-05-08T18:00:46+00:00', 'invalid_date_count': 0, 'unique_authors': 5672, 'unique_threads': 1095, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 1095, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-05-03T06:56:42+00:00', 'date_max': '2019-05-08T18:00:46+00:00', 'invalid_date_count': 0, 'row_count': 33183, 'unique_authors': 5672}, 'unique_matched_tickers': 941, 'seconds': 0.641}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 20, 'raw': {'row_count': 50000, 'date_min': '2019-05-08T18:01:06+00:00', 'date_max': '2019-05-13T22:04:13+00:00', 'invalid_date_count': 0, 'unique_authors': 7434, 'unique_threads': 1085, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33166, 'date_min': '2019-05-08T18:01:06+00:00', 'date_max': '2019-05-13T22:04:13+00:00', 'invalid_date_count': 0, 'unique_authors': 5820, 'unique_threads': 986, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 986, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-05-08T18:01:06+00:00', 'date_max': '2019-05-13T22:04:13+00:00', 'invalid_date_count': 0, 'row_count': 33166, 'unique_authors': 5820}, 'unique_matched_tickers': 978, 'seconds': 0.647}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 21, 'raw': {'row_count': 50000, 'date_min': '2019-05-13T22:04:16+00:00', 'date_max': '2019-05-20T12:42:24+00:00', 'invalid_date_count': 0, 'unique_authors': 6882, 'unique_threads': 1066, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33663, 'date_min': '2019-05-13T22:04:39+00:00', 'date_max': '2019-05-20T12:42:24+00:00', 'invalid_date_count': 0, 'unique_authors': 5524, 'unique_threads': 988, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 988, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-05-13T22:04:39+00:00', 'date_max': '2019-05-20T12:42:24+00:00', 'invalid_date_count': 0, 'row_count': 33663, 'unique_authors': 5524}, 'unique_matched_tickers': 1006, 'seconds': 0.657}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 22, 'raw': {'row_count': 50000, 'date_min': '2019-05-20T12:42:42+00:00', 'date_max': '2019-05-28T03:44:19+00:00', 'invalid_date_count': 0, 'unique_authors': 6851, 'unique_threads': 795, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33643, 'date_min': '2019-05-20T12:43:23+00:00', 'date_max': '2019-05-28T03:44:19+00:00', 'invalid_date_count': 0, 'unique_authors': 5548, 'unique_threads': 729, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 729, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-05-20T12:43:23+00:00', 'date_max': '2019-05-28T03:44:19+00:00', 'invalid_date_count': 0, 'row_count': 33643, 'unique_authors': 5548}, 'unique_matched_tickers': 1043, 'seconds': 0.674}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 23, 'raw': {'row_count': 50000, 'date_min': '2019-05-28T03:44:20+00:00', 'date_max': '2019-06-03T16:27:18+00:00', 'invalid_date_count': 0, 'unique_authors': 7020, 'unique_threads': 694, 'missing_comment_id_count': 0}, 'matched': {'row_count': 34206, 'date_min': '2019-05-28T03:45:30+00:00', 'date_max': '2019-06-03T16:27:18+00:00', 'invalid_date_count': 0, 'unique_authors': 5762, 'unique_threads': 629, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 629, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-05-28T03:45:30+00:00', 'date_max': '2019-06-03T16:27:18+00:00', 'invalid_date_count': 0, 'row_count': 34206, 'unique_authors': 5762}, 'unique_matched_tickers': 1013, 'seconds': 0.71}
{'file': 'wallstreetbets_comment_part4.csv', 'chunk': 24, 'raw': {'row_count': 50000, 'date_min': '2019-06-03T16:27:20+00:00', 'date_max': '2019-06-08T10:42:51+00:00', 'invalid_date_count': 0, 'unique_authors': 6591, 'unique_threads': 818, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33383, 'date_min': '2019-06-03T16:27:29+00:00', 'date_max': '2019-06-08T10:42:31+00:00', 'invalid_date_count': 0, 'unique_authors': 5302, 'unique_threads': 754, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 754, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2019-06-03T16:27:29+00:00', 'date_max': '2019-06-08T10:42:31+00:00', 'invalid_date_count': 0, 'row_count': 33383, 'unique_authors': 5302}, 'unique_matched_tickers': 973, 'seconds': 0.635}

,file,raw_row_count,matched_comment_count,comments_with_ge2_tickers,mention_row_count,raw_missing_comment_id_count,matched_missing_comment_id_count,raw_date_min,raw_date_max,raw_invalid_date_count,matched_date_min,matched_date_max,matched_invalid_date_count,match_rate,unique_raw_authors,unique_raw_threads,unique_matched_authors,unique_matched_threads,unique_matched_tickers,processing_seconds
0,wallstreetbets_comment_part4.csv,3528708,2304903,1328747,5397420,0,0,2018-12-31T00:00:33+00:00,2020-02-01T00:00:15+00:00,0,2018-12-31T00:00:33+00:00,2020-02-01T00:00:15+00:00,0,0.653186,179220,48761,116851,45685,4112,59.876892

Processing: wallstreetbets_comment_part5.csv
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 1, 'raw': {'row_count': 50000, 'date_min': '2020-02-01T00:00:02+00:00', 'date_max': '2020-02-03T23:49:45+00:00', 'invalid_date_count': 0, 'unique_authors': 7556, 'unique_threads': 801, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32604, 'date_min': '2020-02-01T00:00:02+00:00', 'date_max': '2020-02-03T23:49:43+00:00', 'invalid_date_count': 0, 'unique_authors': 6097, 'unique_threads': 723, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 723, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-01T00:00:02+00:00', 'date_max': '2020-02-03T23:49:43+00:00', 'invalid_date_count': 0, 'row_count': 32604, 'unique_authors': 6097}, 'unique_matched_tickers': 923, 'seconds': 0.727}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 2, 'raw': {'row_count': 50000, 'date_min': '2020-02-03T23:49:49+00:00', 'date_max': '2020-02-05T14:44:16+00:00', 'invalid_date_count': 0, 'unique_authors': 9225, 'unique_threads': 825, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32189, 'date_min': '2020-02-03T23:49:49+00:00', 'date_max': '2020-02-05T14:44:09+00:00', 'invalid_date_count': 0, 'unique_authors': 7361, 'unique_threads': 746, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 746, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-03T23:49:49+00:00', 'date_max': '2020-02-05T14:44:09+00:00', 'invalid_date_count': 0, 'row_count': 32189, 'unique_authors': 7361}, 'unique_matched_tickers': 817, 'seconds': 0.698}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 3, 'raw': {'row_count': 50000, 'date_min': '2020-02-05T14:44:17+00:00', 'date_max': '2020-02-07T02:56:56+00:00', 'invalid_date_count': 0, 'unique_authors': 9684, 'unique_threads': 729, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31734, 'date_min': '2020-02-05T14:44:17+00:00', 'date_max': '2020-02-07T02:56:56+00:00', 'invalid_date_count': 0, 'unique_authors': 7646, 'unique_threads': 644, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 644, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-05T14:44:17+00:00', 'date_max': '2020-02-07T02:56:56+00:00', 'invalid_date_count': 0, 'row_count': 31734, 'unique_authors': 7646}, 'unique_matched_tickers': 896, 'seconds': 0.626}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 4, 'raw': {'row_count': 50000, 'date_min': '2020-02-07T02:57:00+00:00', 'date_max': '2020-02-09T21:24:19+00:00', 'invalid_date_count': 0, 'unique_authors': 10003, 'unique_threads': 772, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32118, 'date_min': '2020-02-07T02:57:01+00:00', 'date_max': '2020-02-09T21:24:19+00:00', 'invalid_date_count': 0, 'unique_authors': 7947, 'unique_threads': 693, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 693, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-07T02:57:01+00:00', 'date_max': '2020-02-09T21:24:19+00:00', 'invalid_date_count': 0, 'row_count': 32118, 'unique_authors': 7947}, 'unique_matched_tickers': 946, 'seconds': 0.639}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 5, 'raw': {'row_count': 50000, 'date_min': '2020-02-09T21:24:20+00:00', 'date_max': '2020-02-11T18:24:58+00:00', 'invalid_date_count': 0, 'unique_authors': 9361, 'unique_threads': 665, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32046, 'date_min': '2020-02-09T21:24:33+00:00', 'date_max': '2020-02-11T18:24:58+00:00', 'invalid_date_count': 0, 'unique_authors': 7579, 'unique_threads': 602, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 602, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-09T21:24:33+00:00', 'date_max': '2020-02-11T18:24:58+00:00', 'invalid_date_count': 0, 'row_count': 32046, 'unique_authors': 7579}, 'unique_matched_tickers': 905, 'seconds': 0.606}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 6, 'raw': {'row_count': 50000, 'date_min': '2020-02-11T18:25:02+00:00', 'date_max': '2020-02-13T13:52:42+00:00', 'invalid_date_count': 0, 'unique_authors': 9416, 'unique_threads': 805, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32401, 'date_min': '2020-02-11T18:25:02+00:00', 'date_max': '2020-02-13T13:52:42+00:00', 'invalid_date_count': 0, 'unique_authors': 7685, 'unique_threads': 723, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 723, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-11T18:25:02+00:00', 'date_max': '2020-02-13T13:52:42+00:00', 'invalid_date_count': 0, 'row_count': 32401, 'unique_authors': 7685}, 'unique_matched_tickers': 944, 'seconds': 0.664}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 7, 'raw': {'row_count': 50000, 'date_min': '2020-02-13T13:52:50+00:00', 'date_max': '2020-02-15T19:14:29+00:00', 'invalid_date_count': 0, 'unique_authors': 9518, 'unique_threads': 837, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33102, 'date_min': '2020-02-13T13:52:50+00:00', 'date_max': '2020-02-15T19:14:16+00:00', 'invalid_date_count': 0, 'unique_authors': 7768, 'unique_threads': 749, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 749, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-13T13:52:50+00:00', 'date_max': '2020-02-15T19:14:16+00:00', 'invalid_date_count': 0, 'row_count': 33102, 'unique_authors': 7768}, 'unique_matched_tickers': 946, 'seconds': 0.666}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 8, 'raw': {'row_count': 50000, 'date_min': '2020-02-15T19:14:33+00:00', 'date_max': '2020-02-18T20:41:01+00:00', 'invalid_date_count': 0, 'unique_authors': 9100, 'unique_threads': 788, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32417, 'date_min': '2020-02-15T19:14:33+00:00', 'date_max': '2020-02-18T20:41:00+00:00', 'invalid_date_count': 0, 'unique_authors': 7361, 'unique_threads': 697, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 697, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-15T19:14:33+00:00', 'date_max': '2020-02-18T20:41:00+00:00', 'invalid_date_count': 0, 'row_count': 32417, 'unique_authors': 7361}, 'unique_matched_tickers': 988, 'seconds': 0.654}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 9, 'raw': {'row_count': 50000, 'date_min': '2020-02-18T20:41:06+00:00', 'date_max': '2020-02-20T15:06:15+00:00', 'invalid_date_count': 0, 'unique_authors': 9812, 'unique_threads': 818, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32098, 'date_min': '2020-02-18T20:41:06+00:00', 'date_max': '2020-02-20T15:06:15+00:00', 'invalid_date_count': 0, 'unique_authors': 7922, 'unique_threads': 730, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 730, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-18T20:41:06+00:00', 'date_max': '2020-02-20T15:06:15+00:00', 'invalid_date_count': 0, 'row_count': 32098, 'unique_authors': 7922}, 'unique_matched_tickers': 994, 'seconds': 0.625}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 10, 'raw': {'row_count': 50000, 'date_min': '2020-02-20T15:06:17+00:00', 'date_max': '2020-02-21T21:19:16+00:00', 'invalid_date_count': 0, 'unique_authors': 10191, 'unique_threads': 896, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31488, 'date_min': '2020-02-20T15:06:17+00:00', 'date_max': '2020-02-21T21:19:13+00:00', 'invalid_date_count': 0, 'unique_authors': 8241, 'unique_threads': 802, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 802, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-20T15:06:17+00:00', 'date_max': '2020-02-21T21:19:13+00:00', 'invalid_date_count': 0, 'row_count': 31488, 'unique_authors': 8241}, 'unique_matched_tickers': 944, 'seconds': 0.613}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 11, 'raw': {'row_count': 50000, 'date_min': '2020-02-21T21:19:17+00:00', 'date_max': '2020-02-24T14:57:21+00:00', 'invalid_date_count': 0, 'unique_authors': 9218, 'unique_threads': 728, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30330, 'date_min': '2020-02-21T21:19:17+00:00', 'date_max': '2020-02-24T14:57:21+00:00', 'invalid_date_count': 0, 'unique_authors': 7294, 'unique_threads': 634, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 634, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-21T21:19:17+00:00', 'date_max': '2020-02-24T14:57:21+00:00', 'invalid_date_count': 0, 'row_count': 30330, 'unique_authors': 7294}, 'unique_matched_tickers': 958, 'seconds': 0.663}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 12, 'raw': {'row_count': 50000, 'date_min': '2020-02-24T14:57:24+00:00', 'date_max': '2020-02-25T22:37:42+00:00', 'invalid_date_count': 0, 'unique_authors': 9004, 'unique_threads': 772, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30740, 'date_min': '2020-02-24T14:57:27+00:00', 'date_max': '2020-02-25T22:37:34+00:00', 'invalid_date_count': 0, 'unique_authors': 7307, 'unique_threads': 686, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 686, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-24T14:57:27+00:00', 'date_max': '2020-02-25T22:37:34+00:00', 'invalid_date_count': 0, 'row_count': 30740, 'unique_authors': 7307}, 'unique_matched_tickers': 887, 'seconds': 0.589}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 13, 'raw': {'row_count': 50000, 'date_min': '2020-02-25T22:37:44+00:00', 'date_max': '2020-02-27T04:33:11+00:00', 'invalid_date_count': 0, 'unique_authors': 9064, 'unique_threads': 766, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30801, 'date_min': '2020-02-25T22:37:52+00:00', 'date_max': '2020-02-27T04:33:11+00:00', 'invalid_date_count': 0, 'unique_authors': 7271, 'unique_threads': 660, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 660, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-25T22:37:52+00:00', 'date_max': '2020-02-27T04:33:11+00:00', 'invalid_date_count': 0, 'row_count': 30801, 'unique_authors': 7271}, 'unique_matched_tickers': 848, 'seconds': 0.629}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 14, 'raw': {'row_count': 50000, 'date_min': '2020-02-27T04:33:12+00:00', 'date_max': '2020-02-28T06:15:09+00:00', 'invalid_date_count': 0, 'unique_authors': 9692, 'unique_threads': 942, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31173, 'date_min': '2020-02-27T04:33:12+00:00', 'date_max': '2020-02-28T06:15:08+00:00', 'invalid_date_count': 0, 'unique_authors': 7794, 'unique_threads': 816, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 816, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-27T04:33:12+00:00', 'date_max': '2020-02-28T06:15:08+00:00', 'invalid_date_count': 0, 'row_count': 31173, 'unique_authors': 7794}, 'unique_matched_tickers': 887, 'seconds': 0.631}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 15, 'raw': {'row_count': 50000, 'date_min': '2020-02-28T06:15:10+00:00', 'date_max': '2020-02-29T13:15:30+00:00', 'invalid_date_count': 0, 'unique_authors': 9570, 'unique_threads': 849, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31626, 'date_min': '2020-02-28T06:15:10+00:00', 'date_max': '2020-02-29T13:15:30+00:00', 'invalid_date_count': 0, 'unique_authors': 7804, 'unique_threads': 747, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 747, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-28T06:15:10+00:00', 'date_max': '2020-02-29T13:15:30+00:00', 'invalid_date_count': 0, 'row_count': 31626, 'unique_authors': 7804}, 'unique_matched_tickers': 854, 'seconds': 0.656}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 16, 'raw': {'row_count': 50000, 'date_min': '2020-02-29T13:15:39+00:00', 'date_max': '2020-03-02T02:29:05+00:00', 'invalid_date_count': 0, 'unique_authors': 8470, 'unique_threads': 827, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30842, 'date_min': '2020-02-29T13:15:39+00:00', 'date_max': '2020-03-02T02:29:05+00:00', 'invalid_date_count': 0, 'unique_authors': 6873, 'unique_threads': 743, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 743, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-02-29T13:15:39+00:00', 'date_max': '2020-03-02T02:29:05+00:00', 'invalid_date_count': 0, 'row_count': 30842, 'unique_authors': 6873}, 'unique_matched_tickers': 901, 'seconds': 0.69}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 17, 'raw': {'row_count': 50000, 'date_min': '2020-03-02T02:29:06+00:00', 'date_max': '2020-03-03T05:32:45+00:00', 'invalid_date_count': 0, 'unique_authors': 10552, 'unique_threads': 744, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30722, 'date_min': '2020-03-02T02:29:08+00:00', 'date_max': '2020-03-03T05:32:39+00:00', 'invalid_date_count': 0, 'unique_authors': 8465, 'unique_threads': 646, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 646, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-03-02T02:29:08+00:00', 'date_max': '2020-03-03T05:32:39+00:00', 'invalid_date_count': 0, 'row_count': 30722, 'unique_authors': 8465}, 'unique_matched_tickers': 871, 'seconds': 0.695}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 18, 'raw': {'row_count': 50000, 'date_min': '2020-03-03T05:32:46+00:00', 'date_max': '2020-03-04T14:49:36+00:00', 'invalid_date_count': 0, 'unique_authors': 9916, 'unique_threads': 651, 'missing_comment_id_count': 0}, 'matched': {'row_count': 29833, 'date_min': '2020-03-03T05:32:57+00:00', 'date_max': '2020-03-04T14:49:36+00:00', 'invalid_date_count': 0, 'unique_authors': 7901, 'unique_threads': 566, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 566, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-03-03T05:32:57+00:00', 'date_max': '2020-03-04T14:49:36+00:00', 'invalid_date_count': 0, 'row_count': 29833, 'unique_authors': 7901}, 'unique_matched_tickers': 857, 'seconds': 0.65}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 19, 'raw': {'row_count': 50000, 'date_min': '2020-03-04T14:49:39+00:00', 'date_max': '2020-03-05T19:22:36+00:00', 'invalid_date_count': 0, 'unique_authors': 8871, 'unique_threads': 655, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30297, 'date_min': '2020-03-04T14:49:43+00:00', 'date_max': '2020-03-05T19:22:36+00:00', 'invalid_date_count': 0, 'unique_authors': 7210, 'unique_threads': 578, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 578, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-03-04T14:49:43+00:00', 'date_max': '2020-03-05T19:22:36+00:00', 'invalid_date_count': 0, 'row_count': 30297, 'unique_authors': 7210}, 'unique_matched_tickers': 881, 'seconds': 0.639}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 20, 'raw': {'row_count': 50000, 'date_min': '2020-03-05T19:22:37+00:00', 'date_max': '2020-03-06T21:27:36+00:00', 'invalid_date_count': 0, 'unique_authors': 9137, 'unique_threads': 708, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31192, 'date_min': '2020-03-05T19:22:37+00:00', 'date_max': '2020-03-06T21:27:36+00:00', 'invalid_date_count': 0, 'unique_authors': 7496, 'unique_threads': 560, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 560, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-03-05T19:22:37+00:00', 'date_max': '2020-03-06T21:27:36+00:00', 'invalid_date_count': 0, 'row_count': 31192, 'unique_authors': 7496}, 'unique_matched_tickers': 875, 'seconds': 0.666}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 21, 'raw': {'row_count': 50000, 'date_min': '2020-03-06T21:27:37+00:00', 'date_max': '2020-03-08T20:30:46+00:00', 'invalid_date_count': 0, 'unique_authors': 9399, 'unique_threads': 818, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31557, 'date_min': '2020-03-06T21:27:37+00:00', 'date_max': '2020-03-08T20:30:46+00:00', 'invalid_date_count': 0, 'unique_authors': 7512, 'unique_threads': 717, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 717, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-03-06T21:27:37+00:00', 'date_max': '2020-03-08T20:30:46+00:00', 'invalid_date_count': 0, 'row_count': 31557, 'unique_authors': 7512}, 'unique_matched_tickers': 972, 'seconds': 0.73}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 22, 'raw': {'row_count': 50000, 'date_min': '2020-03-08T20:30:48+00:00', 'date_max': '2020-03-09T19:39:04+00:00', 'invalid_date_count': 0, 'unique_authors': 10510, 'unique_threads': 729, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30709, 'date_min': '2020-03-08T20:30:48+00:00', 'date_max': '2020-03-09T19:39:02+00:00', 'invalid_date_count': 0, 'unique_authors': 8369, 'unique_threads': 635, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 635, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-03-08T20:30:48+00:00', 'date_max': '2020-03-09T19:39:02+00:00', 'invalid_date_count': 0, 'row_count': 30709, 'unique_authors': 8369}, 'unique_matched_tickers': 910, 'seconds': 0.684}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 23, 'raw': {'row_count': 50000, 'date_min': '2020-03-09T19:39:05+00:00', 'date_max': '2020-03-10T20:40:35+00:00', 'invalid_date_count': 0, 'unique_authors': 10434, 'unique_threads': 732, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30881, 'date_min': '2020-03-09T19:39:05+00:00', 'date_max': '2020-03-10T20:40:33+00:00', 'invalid_date_count': 0, 'unique_authors': 8365, 'unique_threads': 637, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 637, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-03-09T19:39:05+00:00', 'date_max': '2020-03-10T20:40:33+00:00', 'invalid_date_count': 0, 'row_count': 30881, 'unique_authors': 8365}, 'unique_matched_tickers': 891, 'seconds': 0.65}
{'file': 'wallstreetbets_comment_part5.csv', 'chunk': 24, 'raw': {'row_count': 50000, 'date_min': '2020-03-10T20:40:37+00:00', 'date_max': '2020-03-11T21:14:48+00:00', 'invalid_date_count': 0, 'unique_authors': 9715, 'unique_threads': 649, 'missing_comment_id_count': 0}, 'matched': {'row_count': 30083, 'date_min': '2020-03-10T20:40:41+00:00', 'date_max': '2020-03-11T21:14:48+00:00', 'invalid_date_count': 0, 'unique_authors': 7876, 'unique_threads': 571, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 571, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-03-10T20:40:41+00:00', 'date_max': '2020-03-11T21:14:48+00:00', 'invalid_date_count': 0, 'row_count': 30083, 'unique_authors': 7876}, 'unique_matched_tickers': 896, 'seconds': 0.669}

,file,raw_row_count,matched_comment_count,comments_with_ge2_tickers,mention_row_count,raw_missing_comment_id_count,matched_missing_comment_id_count,raw_date_min,raw_date_max,raw_invalid_date_count,matched_date_min,matched_date_max,matched_invalid_date_count,match_rate,unique_raw_authors,unique_raw_threads,unique_matched_authors,unique_matched_threads,unique_matched_tickers,processing_seconds
0,wallstreetbets_comment_part5.csv,4458806,2808327,1588204,6396654,0,0,2020-02-01T00:00:02+00:00,2020-06-01T00:00:09+00:00,0,2020-02-01T00:00:02+00:00,2020-06-01T00:00:07+00:00,0,0.629838,159578,53068,128468,49828,4002,94.272795

Processing: wallstreetbets_comment_part6.csv
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 1, 'raw': {'row_count': 50000, 'date_min': '2020-06-01T00:00:01+00:00', 'date_max': '2020-06-02T05:36:27+00:00', 'invalid_date_count': 0, 'unique_authors': 9413, 'unique_threads': 1038, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33101, 'date_min': '2020-06-01T00:00:04+00:00', 'date_max': '2020-06-02T05:36:27+00:00', 'invalid_date_count': 0, 'unique_authors': 7636, 'unique_threads': 967, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 967, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-01T00:00:04+00:00', 'date_max': '2020-06-02T05:36:27+00:00', 'invalid_date_count': 0, 'row_count': 33101, 'unique_authors': 7636}, 'unique_matched_tickers': 1056, 'seconds': 0.913}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 2, 'raw': {'row_count': 50000, 'date_min': '2020-06-02T05:36:28+00:00', 'date_max': '2020-06-03T13:42:54+00:00', 'invalid_date_count': 0, 'unique_authors': 9720, 'unique_threads': 945, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33136, 'date_min': '2020-06-02T05:36:28+00:00', 'date_max': '2020-06-03T13:42:54+00:00', 'invalid_date_count': 0, 'unique_authors': 7812, 'unique_threads': 869, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 869, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-02T05:36:28+00:00', 'date_max': '2020-06-03T13:42:54+00:00', 'invalid_date_count': 0, 'row_count': 33136, 'unique_authors': 7812}, 'unique_matched_tickers': 1055, 'seconds': 0.961}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 3, 'raw': {'row_count': 50000, 'date_min': '2020-06-03T13:42:56+00:00', 'date_max': '2020-06-04T18:13:47+00:00', 'invalid_date_count': 0, 'unique_authors': 9245, 'unique_threads': 604, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33665, 'date_min': '2020-06-03T13:42:56+00:00', 'date_max': '2020-06-04T18:13:47+00:00', 'invalid_date_count': 0, 'unique_authors': 7710, 'unique_threads': 535, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 535, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-03T13:42:56+00:00', 'date_max': '2020-06-04T18:13:47+00:00', 'invalid_date_count': 0, 'row_count': 33665, 'unique_authors': 7710}, 'unique_matched_tickers': 1066, 'seconds': 0.912}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 4, 'raw': {'row_count': 50000, 'date_min': '2020-06-04T18:13:48+00:00', 'date_max': '2020-06-05T21:02:08+00:00', 'invalid_date_count': 0, 'unique_authors': 9521, 'unique_threads': 514, 'missing_comment_id_count': 0}, 'matched': {'row_count': 34184, 'date_min': '2020-06-04T18:13:48+00:00', 'date_max': '2020-06-05T21:02:05+00:00', 'invalid_date_count': 0, 'unique_authors': 8044, 'unique_threads': 450, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 450, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-04T18:13:48+00:00', 'date_max': '2020-06-05T21:02:05+00:00', 'invalid_date_count': 0, 'row_count': 34184, 'unique_authors': 8044}, 'unique_matched_tickers': 1072, 'seconds': 0.903}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 5, 'raw': {'row_count': 50000, 'date_min': '2020-06-05T21:02:09+00:00', 'date_max': '2020-06-07T22:19:49+00:00', 'invalid_date_count': 0, 'unique_authors': 8149, 'unique_threads': 491, 'missing_comment_id_count': 0}, 'matched': {'row_count': 34029, 'date_min': '2020-06-05T21:02:09+00:00', 'date_max': '2020-06-07T22:19:49+00:00', 'invalid_date_count': 0, 'unique_authors': 6760, 'unique_threads': 438, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 438, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-05T21:02:09+00:00', 'date_max': '2020-06-07T22:19:49+00:00', 'invalid_date_count': 0, 'row_count': 34029, 'unique_authors': 6760}, 'unique_matched_tickers': 1189, 'seconds': 0.961}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 6, 'raw': {'row_count': 50000, 'date_min': '2020-06-07T22:19:50+00:00', 'date_max': '2020-06-09T00:48:44+00:00', 'invalid_date_count': 0, 'unique_authors': 9439, 'unique_threads': 517, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33588, 'date_min': '2020-06-07T22:19:53+00:00', 'date_max': '2020-06-09T00:48:42+00:00', 'invalid_date_count': 0, 'unique_authors': 7861, 'unique_threads': 453, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 453, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-07T22:19:53+00:00', 'date_max': '2020-06-09T00:48:42+00:00', 'invalid_date_count': 0, 'row_count': 33588, 'unique_authors': 7861}, 'unique_matched_tickers': 1139, 'seconds': 0.875}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 7, 'raw': {'row_count': 50000, 'date_min': '2020-06-09T00:48:45+00:00', 'date_max': '2020-06-10T00:58:17+00:00', 'invalid_date_count': 0, 'unique_authors': 10078, 'unique_threads': 488, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32332, 'date_min': '2020-06-09T00:48:48+00:00', 'date_max': '2020-06-10T00:58:17+00:00', 'invalid_date_count': 0, 'unique_authors': 8243, 'unique_threads': 435, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 435, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-09T00:48:48+00:00', 'date_max': '2020-06-10T00:58:17+00:00', 'invalid_date_count': 0, 'row_count': 32332, 'unique_authors': 8243}, 'unique_matched_tickers': 1056, 'seconds': 0.905}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 8, 'raw': {'row_count': 50000, 'date_min': '2020-06-10T00:58:19+00:00', 'date_max': '2020-06-11T01:03:45+00:00', 'invalid_date_count': 0, 'unique_authors': 10485, 'unique_threads': 624, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32224, 'date_min': '2020-06-10T00:58:22+00:00', 'date_max': '2020-06-11T01:03:45+00:00', 'invalid_date_count': 0, 'unique_authors': 8572, 'unique_threads': 584, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 584, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-10T00:58:22+00:00', 'date_max': '2020-06-11T01:03:45+00:00', 'invalid_date_count': 0, 'row_count': 32224, 'unique_authors': 8572}, 'unique_matched_tickers': 1038, 'seconds': 0.983}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 9, 'raw': {'row_count': 50000, 'date_min': '2020-06-11T01:03:48+00:00', 'date_max': '2020-06-11T22:19:47+00:00', 'invalid_date_count': 0, 'unique_authors': 11188, 'unique_threads': 955, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32424, 'date_min': '2020-06-11T01:03:53+00:00', 'date_max': '2020-06-11T22:19:46+00:00', 'invalid_date_count': 0, 'unique_authors': 9133, 'unique_threads': 896, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 896, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-11T01:03:53+00:00', 'date_max': '2020-06-11T22:19:46+00:00', 'invalid_date_count': 0, 'row_count': 32424, 'unique_authors': 9133}, 'unique_matched_tickers': 922, 'seconds': 0.891}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 10, 'raw': {'row_count': 50000, 'date_min': '2020-06-11T22:19:48+00:00', 'date_max': '2020-06-12T20:54:22+00:00', 'invalid_date_count': 0, 'unique_authors': 10372, 'unique_threads': 856, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32079, 'date_min': '2020-06-11T22:19:48+00:00', 'date_max': '2020-06-12T20:54:22+00:00', 'invalid_date_count': 0, 'unique_authors': 8364, 'unique_threads': 806, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 806, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-11T22:19:48+00:00', 'date_max': '2020-06-12T20:54:22+00:00', 'invalid_date_count': 0, 'row_count': 32079, 'unique_authors': 8364}, 'unique_matched_tickers': 941, 'seconds': 0.874}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 11, 'raw': {'row_count': 50000, 'date_min': '2020-06-12T20:54:24+00:00', 'date_max': '2020-06-14T12:03:51+00:00', 'invalid_date_count': 0, 'unique_authors': 9879, 'unique_threads': 867, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32313, 'date_min': '2020-06-12T20:54:25+00:00', 'date_max': '2020-06-14T12:03:51+00:00', 'invalid_date_count': 0, 'unique_authors': 7713, 'unique_threads': 810, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 810, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-12T20:54:25+00:00', 'date_max': '2020-06-14T12:03:51+00:00', 'invalid_date_count': 0, 'row_count': 32313, 'unique_authors': 7713}, 'unique_matched_tickers': 1008, 'seconds': 1.023}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 12, 'raw': {'row_count': 50000, 'date_min': '2020-06-14T12:04:06+00:00', 'date_max': '2020-06-15T15:11:36+00:00', 'invalid_date_count': 0, 'unique_authors': 9113, 'unique_threads': 645, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31431, 'date_min': '2020-06-14T12:04:31+00:00', 'date_max': '2020-06-15T15:11:35+00:00', 'invalid_date_count': 0, 'unique_authors': 7326, 'unique_threads': 594, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 594, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-14T12:04:31+00:00', 'date_max': '2020-06-15T15:11:35+00:00', 'invalid_date_count': 0, 'row_count': 31431, 'unique_authors': 7326}, 'unique_matched_tickers': 962, 'seconds': 0.964}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 13, 'raw': {'row_count': 50000, 'date_min': '2020-06-15T15:11:37+00:00', 'date_max': '2020-06-16T14:57:46+00:00', 'invalid_date_count': 0, 'unique_authors': 10216, 'unique_threads': 706, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31953, 'date_min': '2020-06-15T15:11:39+00:00', 'date_max': '2020-06-16T14:57:42+00:00', 'invalid_date_count': 0, 'unique_authors': 8183, 'unique_threads': 646, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 646, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-15T15:11:39+00:00', 'date_max': '2020-06-16T14:57:42+00:00', 'invalid_date_count': 0, 'row_count': 31953, 'unique_authors': 8183}, 'unique_matched_tickers': 1019, 'seconds': 1.019}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 14, 'raw': {'row_count': 50000, 'date_min': '2020-06-16T14:57:47+00:00', 'date_max': '2020-06-17T16:19:59+00:00', 'invalid_date_count': 0, 'unique_authors': 9611, 'unique_threads': 733, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31890, 'date_min': '2020-06-16T14:57:47+00:00', 'date_max': '2020-06-17T16:19:57+00:00', 'invalid_date_count': 0, 'unique_authors': 7812, 'unique_threads': 668, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 668, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-16T14:57:47+00:00', 'date_max': '2020-06-17T16:19:57+00:00', 'invalid_date_count': 0, 'row_count': 31890, 'unique_authors': 7812}, 'unique_matched_tickers': 1011, 'seconds': 1.126}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 15, 'raw': {'row_count': 50000, 'date_min': '2020-06-17T16:20:02+00:00', 'date_max': '2020-06-18T18:07:59+00:00', 'invalid_date_count': 0, 'unique_authors': 10071, 'unique_threads': 747, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32276, 'date_min': '2020-06-17T16:20:02+00:00', 'date_max': '2020-06-18T18:07:54+00:00', 'invalid_date_count': 0, 'unique_authors': 8191, 'unique_threads': 688, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 688, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-17T16:20:02+00:00', 'date_max': '2020-06-18T18:07:54+00:00', 'invalid_date_count': 0, 'row_count': 32276, 'unique_authors': 8191}, 'unique_matched_tickers': 1053, 'seconds': 0.951}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 16, 'raw': {'row_count': 50000, 'date_min': '2020-06-18T18:08:00+00:00', 'date_max': '2020-06-19T21:23:28+00:00', 'invalid_date_count': 0, 'unique_authors': 10148, 'unique_threads': 810, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32159, 'date_min': '2020-06-18T18:08:02+00:00', 'date_max': '2020-06-19T21:23:28+00:00', 'invalid_date_count': 0, 'unique_authors': 8281, 'unique_threads': 732, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 732, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-18T18:08:02+00:00', 'date_max': '2020-06-19T21:23:28+00:00', 'invalid_date_count': 0, 'row_count': 32159, 'unique_authors': 8281}, 'unique_matched_tickers': 1092, 'seconds': 0.952}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 17, 'raw': {'row_count': 50000, 'date_min': '2020-06-19T21:23:29+00:00', 'date_max': '2020-06-21T19:49:10+00:00', 'invalid_date_count': 0, 'unique_authors': 8856, 'unique_threads': 782, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32517, 'date_min': '2020-06-19T21:23:29+00:00', 'date_max': '2020-06-21T19:49:10+00:00', 'invalid_date_count': 0, 'unique_authors': 7078, 'unique_threads': 724, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 724, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-19T21:23:29+00:00', 'date_max': '2020-06-21T19:49:10+00:00', 'invalid_date_count': 0, 'row_count': 32517, 'unique_authors': 7078}, 'unique_matched_tickers': 1043, 'seconds': 1.013}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 18, 'raw': {'row_count': 50000, 'date_min': '2020-06-21T19:49:11+00:00', 'date_max': '2020-06-23T02:36:05+00:00', 'invalid_date_count': 0, 'unique_authors': 9525, 'unique_threads': 660, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31836, 'date_min': '2020-06-21T19:49:13+00:00', 'date_max': '2020-06-23T02:36:04+00:00', 'invalid_date_count': 0, 'unique_authors': 7767, 'unique_threads': 606, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 606, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-21T19:49:13+00:00', 'date_max': '2020-06-23T02:36:04+00:00', 'invalid_date_count': 0, 'row_count': 31836, 'unique_authors': 7767}, 'unique_matched_tickers': 1029, 'seconds': 0.995}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 19, 'raw': {'row_count': 50000, 'date_min': '2020-06-23T02:36:06+00:00', 'date_max': '2020-06-24T12:35:52+00:00', 'invalid_date_count': 0, 'unique_authors': 9361, 'unique_threads': 687, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32499, 'date_min': '2020-06-23T02:36:06+00:00', 'date_max': '2020-06-24T12:35:52+00:00', 'invalid_date_count': 0, 'unique_authors': 7630, 'unique_threads': 635, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 635, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-23T02:36:06+00:00', 'date_max': '2020-06-24T12:35:52+00:00', 'invalid_date_count': 0, 'row_count': 32499, 'unique_authors': 7630}, 'unique_matched_tickers': 1043, 'seconds': 0.968}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 20, 'raw': {'row_count': 50000, 'date_min': '2020-06-24T12:35:54+00:00', 'date_max': '2020-06-25T15:28:42+00:00', 'invalid_date_count': 0, 'unique_authors': 9465, 'unique_threads': 651, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31990, 'date_min': '2020-06-24T12:36:00+00:00', 'date_max': '2020-06-25T15:28:42+00:00', 'invalid_date_count': 0, 'unique_authors': 7678, 'unique_threads': 600, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 600, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-24T12:36:00+00:00', 'date_max': '2020-06-25T15:28:42+00:00', 'invalid_date_count': 0, 'row_count': 31990, 'unique_authors': 7678}, 'unique_matched_tickers': 960, 'seconds': 0.962}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 21, 'raw': {'row_count': 50000, 'date_min': '2020-06-25T15:28:44+00:00', 'date_max': '2020-06-26T19:00:30+00:00', 'invalid_date_count': 0, 'unique_authors': 9773, 'unique_threads': 711, 'missing_comment_id_count': 0}, 'matched': {'row_count': 32354, 'date_min': '2020-06-25T15:28:44+00:00', 'date_max': '2020-06-26T19:00:30+00:00', 'invalid_date_count': 0, 'unique_authors': 7890, 'unique_threads': 647, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 647, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-25T15:28:44+00:00', 'date_max': '2020-06-26T19:00:30+00:00', 'invalid_date_count': 0, 'row_count': 32354, 'unique_authors': 7890}, 'unique_matched_tickers': 1055, 'seconds': 0.97}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 22, 'raw': {'row_count': 50000, 'date_min': '2020-06-26T19:00:31+00:00', 'date_max': '2020-06-28T15:49:24+00:00', 'invalid_date_count': 0, 'unique_authors': 8869, 'unique_threads': 738, 'missing_comment_id_count': 0}, 'matched': {'row_count': 33229, 'date_min': '2020-06-26T19:00:33+00:00', 'date_max': '2020-06-28T15:49:21+00:00', 'invalid_date_count': 0, 'unique_authors': 7121, 'unique_threads': 676, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 676, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-26T19:00:33+00:00', 'date_max': '2020-06-28T15:49:21+00:00', 'invalid_date_count': 0, 'row_count': 33229, 'unique_authors': 7121}, 'unique_matched_tickers': 1086, 'seconds': 1.037}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 23, 'raw': {'row_count': 50000, 'date_min': '2020-06-28T15:49:29+00:00', 'date_max': '2020-06-30T00:13:05+00:00', 'invalid_date_count': 0, 'unique_authors': 9111, 'unique_threads': 642, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31668, 'date_min': '2020-06-28T15:49:29+00:00', 'date_max': '2020-06-30T00:13:05+00:00', 'invalid_date_count': 0, 'unique_authors': 7376, 'unique_threads': 582, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 582, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-28T15:49:29+00:00', 'date_max': '2020-06-30T00:13:05+00:00', 'invalid_date_count': 0, 'row_count': 31668, 'unique_authors': 7376}, 'unique_matched_tickers': 1038, 'seconds': 0.989}
{'file': 'wallstreetbets_comment_part6.csv', 'chunk': 24, 'raw': {'row_count': 50000, 'date_min': '2020-06-30T00:13:06+00:00', 'date_max': '2020-07-01T12:46:58+00:00', 'invalid_date_count': 0, 'unique_authors': 9281, 'unique_threads': 703, 'missing_comment_id_count': 0}, 'matched': {'row_count': 31760, 'date_min': '2020-06-30T00:13:08+00:00', 'date_max': '2020-07-01T12:46:55+00:00', 'invalid_date_count': 0, 'unique_authors': 7465, 'unique_threads': 640, 'missing_comment_id_count': 0}, 'enriched': {'unique_threads': 640, 'missing_thread_count': 0, 'missing_parent_id_count': 0, 'invalid_timestamp_count': 0, 'date_min': '2020-06-30T00:13:08+00:00', 'date_max': '2020-07-01T12:46:55+00:00', 'invalid_date_count': 0, 'row_count': 31760, 'unique_authors': 7465}, 'unique_matched_tickers': 1110, 'seconds': 0.875}

,file,raw_row_count,matched_comment_count,comments_with_ge2_tickers,mention_row_count,raw_missing_comment_id_count,matched_missing_comment_id_count,raw_date_min,raw_date_max,raw_invalid_date_count,matched_date_min,matched_date_max,matched_invalid_date_count,match_rate,unique_raw_authors,unique_raw_threads,unique_matched_authors,unique_matched_threads,unique_matched_tickers,processing_seconds
0,wallstreetbets_comment_part6.csv,2385062,1569148,886697,3580433,0,0,2020-06-01T00:00:01+00:00,2020-08-06T01:41:22+00:00,0,2020-06-01T00:00:04+00:00,2020-08-06T01:41:18+00:00,0,0.657907,97712,23872,79292,22840,3799,56.97965

## Combined statistics and output validation
Match rate is total matched input rows divided by total input rows. Unique authors, threads and tickers use exact unions across the six files. Parquet footer counts validate incremental writing without loading the output dataset into memory. A small preview reads only the first batch.

In [8]:
overall = {'file': 'ALL_FILES', 'processing_seconds': formal_seconds}
for key in ['raw_row_count', 'matched_comment_count', 'comments_with_ge2_tickers', 'mention_row_count',
            'raw_invalid_date_count', 'matched_invalid_date_count', 'raw_missing_comment_id_count', 'matched_missing_comment_id_count']:
    overall[key] = sum(s.get(key, 0) for s in summaries)
overall['match_rate'] = overall['matched_comment_count'] / overall['raw_row_count'] if overall['raw_row_count'] else 0.0
for stage in ['raw', 'matched']:
    for suffix, func in [('date_min', min), ('date_max', max)]:
        vals = [s[stage + '_' + suffix] for s in summaries if s.get(stage + '_' + suffix)]
        overall[stage + '_' + suffix] = func(vals) if vals else None
    for kind in ['authors', 'threads']:
        overall[f'unique_{stage}_{kind}'] = unique_count(stage, kind)
overall['unique_matched_tickers'] = unique_count('matched', 'tickers')
summary_table = pd.DataFrame(summaries + [overall])
display(summary_table)
assert INPUT_STATS == {str(p): (p.stat().st_size, p.stat().st_mtime_ns) for p in SOURCES}, 'Input file metadata changed'
assert sum(pq.read_metadata(RUN_DIR / (s.stem + '.comments.parquet')).num_rows for s in SOURCES) == overall['matched_comment_count']
assert sum(pq.read_metadata(RUN_DIR / (s.stem + '.mentions.parquet')).num_rows for s in SOURCES) == overall['mention_row_count']
manifest = {'status': 'complete', 'schema_version':2, 'comment_enrichment':True, 'selected_method': SELECTED_METHOD, 'chunk_size': CHUNK_SIZE,
            'benchmark_rows': BENCHMARK_ROWS, 'dictionary': str(DICTIONARY),
            'dictionary_sha256': hashlib.sha256(DICTIONARY.read_bytes()).hexdigest(),
            'input_metadata': INPUT_STATS, 'versions': VERSIONS, 'python': platform.python_version(),
            'case_policy': 'uppercase text and dictionary', 'token_policy': 'Unicode word tokens',
            'created_utc_output_type': 'original string', 'run_directory': str(RUN_DIR)}
db.close()
remove_work_database(WORK_DB)
for source in SOURCES:
    preview = next(pq.ParquetFile(RUN_DIR / (source.stem + '.comments.parquet')).iter_batches(batch_size=3), None)
    if preview is not None:
        display(preview.to_pandas())
        break
print('COMPLETE. Input sizes/mtimes unchanged; all Parquet row counts validated.')
print('Output:', RUN_DIR)

publish(ROOT,'matching',RUN_DIR,dict(manifest,files=summaries,overall=overall,benchmark=benchmark_table.to_dict(orient='records')))

,file,raw_row_count,matched_comment_count,comments_with_ge2_tickers,mention_row_count,raw_missing_comment_id_count,matched_missing_comment_id_count,raw_date_min,raw_date_max,raw_invalid_date_count,matched_date_min,matched_date_max,matched_invalid_date_count,match_rate,unique_raw_authors,unique_raw_threads,unique_matched_authors,unique_matched_threads,unique_matched_tickers,processing_seconds
0,wallstreetbets_comment_part1.csv,310753,221516,145852,660525,23,14,1970-01-01T00:00:01+00:00,2016-04-25T12:28:09+00:00,23,2012-04-11T16:46:43+00:00,2016-04-25T12:28:09+00:00,14,0.712836,16596,20315,14439,19409,2615,5.871178
1,wallstreetbets_comment_part2.csv,575124,373356,229841,983294,0,0,2016-04-25T12:29:23+00:00,2017-04-01T06:13:54+00:00,0,2016-04-25T12:29:23+00:00,2017-04-01T06:13:54+00:00,0,0.649175,31225,33094,25508,31185,2883,9.919673
2,wallstreetbets_comment_part3.csv,2218513,1437717,856162,3538335,0,0,2017-04-01T05:41:35+00:00,2018-12-31T00:05:11+00:00,0,2017-04-01T05:41:35+00:00,2018-12-31T00:05:03+00:00,0,0.648054,95173,98161,77224,92081,3720,37.491929
3,wallstreetbets_comment_part4.csv,3528708,2304903,1328747,5397420,0,0,2018-12-31T00:00:33+00:00,2020-02-01T00:00:15+00:00,0,2018-12-31T00:00:33+00:00,2020-02-01T00:00:15+00:00,0,0.653186,179220,48761,116851,45685,4112,59.876892
4,wallstreetbets_comment_part5.csv,4458806,2808327,1588204,6396654,0,0,2020-02-01T00:00:02+00:00,2020-06-01T00:00:09+00:00,0,2020-02-01T00:00:02+00:00,2020-06-01T00:00:07+00:00,0,0.629838,159578,53068,128468,49828,4002,94.272795
5,wallstreetbets_comment_part6.csv,2385062,1569148,886697,3580433,0,0,2020-06-01T00:00:01+00:00,2020-08-06T01:41:22+00:00,0,2020-06-01T00:00:04+00:00,2020-08-06T01:41:18+00:00,0,0.657907,97712,23872,79292,22840,3799,56.979650
6,ALL_FILES,13476966,8714967,5035503,20556661,23,14,1970-01-01T00:00:01+00:00,2020-08-06T01:41:22+00:00,23,2012-04-11T16:46:43+00:00,2020-08-06T01:41:18+00:00,14,0.646656,409612,273994,309073,258609,5682,264.461131

,comment_id,author,created_utc,link_id,body,matched_tickers,matched_ticker_count,source_file,source_row,id,parent_id,thread_id,created_datetime_utc,created_date,year_month
0,c4b0pvu,secondhandsondek,1334162803.0,t3_s4jw1,This is a fantastic idea Ill toss mine up in a...,"[BIT, BMO, JPM]",3,wallstreetbets_comment_part1.csv,1,c4b0pvu,t3_s4jw1,s4jw1,2012-04-11 16:46:43+00:00,2012-04-11,2012-04
1,c4b1fpf,glorysk87,1334165948.0,t3_s4jw1,INTC is on 417,[INTC],1,wallstreetbets_comment_part1.csv,2,c4b1fpf,t3_s4jw1,s4jw1,2012-04-11 17:39:08+00:00,2012-04-11,2012-04
2,c4b1rmm,entsportsjunkie,1334167351.0,t3_s4jw1,straddle call straddle put put put straddle ca...,"[CALL, FOR, MORE, ONE, TECH]",5,wallstreetbets_comment_part1.csv,3,c4b1rmm,t3_s4jw1,s4jw1,2012-04-11 18:02:31+00:00,2012-04-11,2012-04

COMPLETE. Input sizes/mtimes unchanged; all Parquet row counts validated.
Output: c:\Users\eagle\RedditStock\Data\process\02_ticker_matching\2026-09-22_03-52-09_UTC