# Thread 彙整與 Thread-Ticker 匯出

將02階段匹配成功的留言-ticker彙整成thread-month-ticker

使用 `pipeline_runs.json` 指向的成功 02 階段結果。

## 處理規則

- 僅分批讀取已匹配的 comment Parquet。
- 使用既有 UTC datetime 與標準化 `thread_id`。
- 缺少 `thread_id` 的留言不參與 thread 彙整。
- 無效 timestamp 不納入 thread 起訖時間。
- `n_comments`：thread 內留言列數。
- `n_authors`：不同且非空白的 author 數；`[deleted]` 視為有效值。
- ticker 採跨檔案 distinct union。
- `parent_id` 僅供 audit。

## 月份定義

thread 的月份取自第一筆匹配留言的 UTC 月份。

同一 thread 後續出現的所有 ticker 都歸入該月份，因此這不是逐月 contemporaneous mention table。

## 輸出

產生：

- `threads.parquet`
- `thread_ticker.parquet`
- `run_summary.json`

不產生 stock pairs，也不新增任何研究篩選或排除條件。

唯一值統計使用 disk-backed SQLite。只有兩個輸出都成功驗證後才更新 `pipeline_runs.json`；每次執行建立新的 UTC 時間戳目錄，舊輸出保留。

In [1]:
from pathlib import Path
from datetime import datetime, timezone
import json, sqlite3, time, uuid
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from IPython.display import display
ROOT = next(p for p in (Path.cwd(), *Path.cwd().parents) if (p/'Data/process').is_dir())

import sys
sys.path.insert(0,str(ROOT/'Notebook'))
from pipeline_io import new_run, publish, input_run, remove_work_database

POINTER = ROOT/'Data/process/pipeline_runs.json'
MATCH_MANIFEST_PATH = None  # Set an explicit manifest path here to override the pipeline pointer.
if MATCH_MANIFEST_PATH is None:
    MATCH_MANIFEST_PATH = json.loads(POINTER.read_text())['matching_manifest']
MATCH_MANIFEST_PATH = Path(MATCH_MANIFEST_PATH)
MATCH_MANIFEST = json.loads(MATCH_MANIFEST_PATH.read_text())
assert MATCH_MANIFEST['status']=='complete' and MATCH_MANIFEST.get('schema_version')==2
MATCH_DIR = MATCH_MANIFEST_PATH.parent
FILES = sorted(MATCH_DIR.glob('*.comments.parquet'))
assert len(FILES)==len(MATCH_MANIFEST['input_metadata'])
BATCH = 50_000
OUT = new_run(ROOT,'thread')
SOURCE_METADATA = {str(p):[p.stat().st_size,p.stat().st_mtime_ns] for p in FILES}
REQUIRED = ['comment_id','parent_id','thread_id','author','created_datetime_utc','matched_tickers','matched_ticker_count']
for p in FILES: assert set(REQUIRED).issubset(pq.read_schema(p).names)
print('Matching manifest:',MATCH_MANIFEST_PATH)
print('Output:',OUT)
display(pd.DataFrame([{'file':p.name,'rows':pq.read_metadata(p).num_rows} for p in FILES]))

Matching manifest: C:\Users\eagle\RedditStock\Data\process\ticker_matching\20260922T032254Z_98f0008d\manifest.json
Output: C:\Users\eagle\RedditStock\Data\process\03_thread_construction\2026-09-22_03-38-31_UTC

                                            file     rows
0  wallstreetbets_comment_part1.comments.parquet   221516
1  wallstreetbets_comment_part2.comments.parquet   373356
2  wallstreetbets_comment_part3.comments.parquet  1437717
3  wallstreetbets_comment_part4.comments.parquet  2304903
4  wallstreetbets_comment_part5.comments.parquet  2808327
5  wallstreetbets_comment_part6.comments.parquet  1569148

In [2]:
THREAD_SCHEMA = pa.schema([('thread_id', pa.string()), ('first_timestamp', pa.timestamp('ns',tz='UTC')),
    ('last_timestamp', pa.timestamp('ns',tz='UTC')), ('n_comments', pa.int64()), ('n_authors', pa.int64()),
    ('tickers_in_thread', pa.list_(pa.string())), ('n_unique_tickers', pa.int64())])

In [3]:
WORK_DB = OUT/'_work/thread_aggregation.sqlite'
WORK_DB.parent.mkdir()
db = sqlite3.connect(WORK_DB)
db.execute('PRAGMA cache_size=-32768')
db.execute('PRAGMA temp_store=FILE')
db.executescript("""
CREATE TABLE threads(thread_id TEXT PRIMARY KEY, first_ns INTEGER, last_ns INTEGER, n_comments INTEGER) WITHOUT ROWID;
CREATE TABLE thread_authors(thread_id TEXT, author TEXT, PRIMARY KEY(thread_id,author)) WITHOUT ROWID;
CREATE TABLE thread_tickers(thread_id TEXT, ticker TEXT, PRIMARY KEY(thread_id,ticker)) WITHOUT ROWID;
CREATE TABLE file_authors(file TEXT, author TEXT, PRIMARY KEY(file,author)) WITHOUT ROWID;
CREATE TABLE file_threads(file TEXT, thread_id TEXT, PRIMARY KEY(file,thread_id)) WITHOUT ROWID;
""")

def aggregate(frame, file):
    db.executemany('INSERT OR IGNORE INTO file_authors VALUES (?,?)', ((file,a) for a in frame.author.unique() if a != ''))
    valid = frame.loc[frame.thread_id.notna()]
    db.executemany('INSERT OR IGNORE INTO file_threads VALUES (?,?)', ((file,t) for t in valid.thread_id.unique()))
    grouped = valid.groupby('thread_id', sort=False).agg(first=('created_datetime_utc','min'), last=('created_datetime_utc','max'), n=('comment_id','size'))
    rows = ((t, None if pd.isna(f) else f.value, None if pd.isna(l) else l.value, int(k)) for t,f,l,k in grouped.itertuples())
    db.executemany("""INSERT INTO threads VALUES (?,?,?,?) ON CONFLICT(thread_id) DO UPDATE SET
    first_ns = CASE WHEN excluded.first_ns IS NULL THEN threads.first_ns WHEN threads.first_ns IS NULL THEN excluded.first_ns ELSE MIN(threads.first_ns,excluded.first_ns) END,
    last_ns = CASE WHEN excluded.last_ns IS NULL THEN threads.last_ns WHEN threads.last_ns IS NULL THEN excluded.last_ns ELSE MAX(threads.last_ns,excluded.last_ns) END,
    n_comments = threads.n_comments + excluded.n_comments""", rows)
    authors = valid.loc[valid.author.ne(''), ['thread_id','author']].drop_duplicates()
    db.executemany('INSERT OR IGNORE INTO thread_authors VALUES (?,?)', authors.itertuples(index=False,name=None))
    pairs = valid[['thread_id','matched_tickers']].explode('matched_tickers').drop_duplicates()
    db.executemany('INSERT OR IGNORE INTO thread_tickers VALUES (?,?)', pairs.itertuples(index=False,name=None))
    db.commit()

def diagnostics(frame):
    dates = frame.created_datetime_utc
    return {'row_count':len(frame), 'date_min':None if dates.dropna().empty else dates.min().isoformat(),
            'date_max':None if dates.dropna().empty else dates.max().isoformat(),
            'unique_authors':int(frame.loc[frame.author.ne(''),'author'].nunique()),
            'unique_threads':int(frame.thread_id.nunique()),
            'missing_thread_count':int(frame.thread_id.isna().sum()),
            'invalid_timestamp_count':int(dates.isna().sum()),
            'missing_parent_id_count':int(frame.parent_id.eq('').sum()),
            'unusual_thread_format_count':int((frame.thread_id.notna() & ~frame.thread_id.fillna('').str.fullmatch('[a-z0-9]+')).sum())}

## 彙整 6 份 Enriched Comment 檔

每個 batch 保留：

- row 診斷
- date 診斷
- author 診斷
- thread 診斷

原始 comment Parquet 不會被重寫。

In [4]:
started = time.perf_counter()
summaries = []
for source in FILES:
    file_started = time.perf_counter()
    csv_name = source.name.replace('.comments.parquet','.csv')
    totals = {'file':csv_name, 'row_count':0, 'missing_thread_count':0, 'invalid_timestamp_count':0,
              'missing_parent_id_count':0, 'unusual_thread_format_count':0, 'date_min':None, 'date_max':None}
    for batch_no, batch in enumerate(pq.ParquetFile(source).iter_batches(batch_size=BATCH,columns=REQUIRED),1):
            frame = batch.to_pandas()
            assert frame.matched_ticker_count.ge(1).all()
            aggregate(frame, csv_name)
            diag = diagnostics(frame)
            for key in ['row_count','missing_thread_count','invalid_timestamp_count','missing_parent_id_count','unusual_thread_format_count']:
                totals[key] += diag[key]
            for key, op in [('date_min',min),('date_max',max)]:
                values = [v for v in [totals[key],diag[key]] if v is not None]
                totals[key] = op(values) if values else None
            entry = {'file':csv_name, 'batch':batch_no, **diag}
            print(entry, flush=True)
            del frame, batch
    assert pq.read_metadata(source).num_rows == totals['row_count']
    totals['unique_authors'] = db.execute('SELECT COUNT(*) FROM file_authors WHERE file=?',(csv_name,)).fetchone()[0]
    totals['unique_threads'] = db.execute('SELECT COUNT(*) FROM file_threads WHERE file=?',(csv_name,)).fetchone()[0]
    totals['processing_seconds'] = time.perf_counter()-file_started
    summaries.append(totals)
    display(pd.DataFrame([totals]))

{'file': 'wallstreetbets_comment_part1.csv', 'batch': 1, 'row_count': 50000, 'date_min': '2012-04-11T16:46:43+00:00', 'date_max': '2015-06-18T14:32:13+00:00', 'unique_authors': 4601, 'unique_threads': 5196, 'missing_thread_count': 9, 'invalid_timestamp_count': 9, 'missing_parent_id_count': 9, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part1.csv', 'batch': 2, 'row_count': 50000, 'date_min': '2015-06-18T14:35:08+00:00', 'date_max': '2015-10-21T15:14:13+00:00', 'unique_authors': 4129, 'unique_threads': 4613, 'missing_thread_count': 1, 'invalid_timestamp_count': 1, 'missing_parent_id_count': 1, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part1.csv', 'batch': 3, 'row_count': 50000, 'date_min': '2015-10-21T15:14:32+00:00', 'date_max': '2016-01-21T07:30:53+00:00', 'unique_authors': 4597, 'unique_threads': 3931, 'missing_thread_count': 4, 'invalid_timestamp_count': 4, 'missing_parent_id_count': 4, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part1.csv', 'batch': 4, 'row_count': 50000, 'date_min': '2016-01-21T07:32:14+00:00', 'date_max': '2016-04-04T14:25:45+00:00', 'unique_authors': 5258, 'unique_threads': 4185, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part1.csv', 'batch': 5, 'row_count': 21516, 'date_min': '2016-04-04T14:29:22+00:00', 'date_max': '2016-04-25T12:28:09+00:00', 'unique_authors': 3071, 'unique_threads': 1879, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

,file,row_count,missing_thread_count,invalid_timestamp_count,missing_parent_id_count,unusual_thread_format_count,date_min,date_max,unique_authors,unique_threads,processing_seconds
0,wallstreetbets_comment_part1.csv,221516,14,14,14,0,2012-04-11T16:46:43+00:00,2016-04-25T12:28:09+00:00,14439,19409,2.306682

{'file': 'wallstreetbets_comment_part2.csv', 'batch': 1, 'row_count': 50000, 'date_min': '2016-04-25T12:29:23+00:00', 'date_max': '2016-06-24T03:33:53+00:00', 'unique_authors': 5306, 'unique_threads': 4245, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part2.csv', 'batch': 2, 'row_count': 50000, 'date_min': '2016-06-24T03:34:01+00:00', 'date_max': '2016-08-05T15:20:19+00:00', 'unique_authors': 5668, 'unique_threads': 4487, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part2.csv', 'batch': 3, 'row_count': 50000, 'date_min': '2016-08-05T15:20:22+00:00', 'date_max': '2016-09-21T16:50:10+00:00', 'unique_authors': 5901, 'unique_threads': 4873, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part2.csv', 'batch': 4, 'row_count': 50000, 'date_min': '2016-09-21T16:50:47+00:00', 'date_max': '2016-11-14T04:51:00+00:00', 'unique_authors': 6022, 'unique_threads': 4793, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part2.csv', 'batch': 5, 'row_count': 50000, 'date_min': '2016-11-14T04:51:44+00:00', 'date_max': '2017-01-04T02:58:12+00:00', 'unique_authors': 6481, 'unique_threads': 5041, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part2.csv', 'batch': 6, 'row_count': 50000, 'date_min': '2017-01-04T02:58:28+00:00', 'date_max': '2017-02-10T20:51:22+00:00', 'unique_authors': 8709, 'unique_threads': 3746, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part2.csv', 'batch': 7, 'row_count': 50000, 'date_min': '2017-02-10T20:52:17+00:00', 'date_max': '2017-03-15T16:47:09+00:00', 'unique_authors': 6474, 'unique_threads': 3685, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part2.csv', 'batch': 8, 'row_count': 23356, 'date_min': '2017-03-15T16:48:53+00:00', 'date_max': '2017-04-01T06:13:54+00:00', 'unique_authors': 3837, 'unique_threads': 1629, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

,file,row_count,missing_thread_count,invalid_timestamp_count,missing_parent_id_count,unusual_thread_format_count,date_min,date_max,unique_authors,unique_threads,processing_seconds
0,wallstreetbets_comment_part2.csv,373356,0,0,0,0,2016-04-25T12:29:23+00:00,2017-04-01T06:13:54+00:00,25508,31185,3.819426

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 1, 'row_count': 50000, 'date_min': '2017-04-01T05:41:35+00:00', 'date_max': '2017-05-13T03:22:36+00:00', 'unique_authors': 7041, 'unique_threads': 3746, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 2, 'row_count': 50000, 'date_min': '2017-05-13T03:30:05+00:00', 'date_max': '2017-06-24T19:07:19+00:00', 'unique_authors': 6299, 'unique_threads': 3928, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 3, 'row_count': 50000, 'date_min': '2017-06-24T19:08:05+00:00', 'date_max': '2017-07-28T01:41:08+00:00', 'unique_authors': 7328, 'unique_threads': 3456, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 4, 'row_count': 50000, 'date_min': '2017-07-28T01:41:13+00:00', 'date_max': '2017-09-08T15:45:05+00:00', 'unique_authors': 7768, 'unique_threads': 3924, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 5, 'row_count': 50000, 'date_min': '2017-09-08T15:46:30+00:00', 'date_max': '2017-10-19T04:35:53+00:00', 'unique_authors': 7676, 'unique_threads': 4117, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 6, 'row_count': 50000, 'date_min': '2017-10-19T04:37:38+00:00', 'date_max': '2017-11-26T16:16:51+00:00', 'unique_authors': 7611, 'unique_threads': 4054, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 7, 'row_count': 50000, 'date_min': '2017-11-26T16:18:02+00:00', 'date_max': '2018-01-09T18:44:28+00:00', 'unique_authors': 8409, 'unique_threads': 3762, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 8, 'row_count': 50000, 'date_min': '2018-01-09T18:44:48+00:00', 'date_max': '2018-02-07T19:47:37+00:00', 'unique_authors': 7628, 'unique_threads': 4484, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 9, 'row_count': 50000, 'date_min': '2018-02-07T19:47:45+00:00', 'date_max': '2018-03-07T19:17:23+00:00', 'unique_authors': 7586, 'unique_threads': 4287, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 10, 'row_count': 50000, 'date_min': '2018-03-07T19:17:26+00:00', 'date_max': '2018-04-03T22:33:16+00:00', 'unique_authors': 7747, 'unique_threads': 4125, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 11, 'row_count': 50000, 'date_min': '2018-04-03T22:33:33+00:00', 'date_max': '2018-04-27T21:53:46+00:00', 'unique_authors': 7581, 'unique_threads': 3542, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 12, 'row_count': 50000, 'date_min': '2018-04-27T21:54:55+00:00', 'date_max': '2018-05-22T15:05:26+00:00', 'unique_authors': 7098, 'unique_threads': 3947, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 13, 'row_count': 50000, 'date_min': '2018-05-22T15:05:28+00:00', 'date_max': '2018-06-12T16:18:57+00:00', 'unique_authors': 7027, 'unique_threads': 3819, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 14, 'row_count': 50000, 'date_min': '2018-06-12T16:19:02+00:00', 'date_max': '2018-06-28T13:10:37+00:00', 'unique_authors': 7483, 'unique_threads': 4443, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 15, 'row_count': 50000, 'date_min': '2018-06-28T13:10:51+00:00', 'date_max': '2018-07-18T21:18:05+00:00', 'unique_authors': 7648, 'unique_threads': 3720, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 16, 'row_count': 50000, 'date_min': '2018-07-18T21:18:22+00:00', 'date_max': '2018-08-02T14:10:15+00:00', 'unique_authors': 7999, 'unique_threads': 3866, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 17, 'row_count': 50000, 'date_min': '2018-08-02T14:10:17+00:00', 'date_max': '2018-08-17T01:03:25+00:00', 'unique_authors': 8517, 'unique_threads': 3951, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 18, 'row_count': 50000, 'date_min': '2018-08-17T01:04:11+00:00', 'date_max': '2018-08-30T17:56:20+00:00', 'unique_authors': 8895, 'unique_threads': 3410, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 19, 'row_count': 50000, 'date_min': '2018-08-30T17:56:28+00:00', 'date_max': '2018-09-12T22:09:46+00:00', 'unique_authors': 8699, 'unique_threads': 3455, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 20, 'row_count': 50000, 'date_min': '2018-09-12T22:09:56+00:00', 'date_max': '2018-09-23T23:29:48+00:00', 'unique_authors': 8316, 'unique_threads': 3093, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 21, 'row_count': 50000, 'date_min': '2018-09-23T23:29:59+00:00', 'date_max': '2018-10-03T18:00:36+00:00', 'unique_authors': 8747, 'unique_threads': 2801, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 22, 'row_count': 50000, 'date_min': '2018-10-03T18:00:38+00:00', 'date_max': '2018-10-12T22:23:09+00:00', 'unique_authors': 8584, 'unique_threads': 2850, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 23, 'row_count': 50000, 'date_min': '2018-10-12T22:23:35+00:00', 'date_max': '2018-10-24T23:48:41+00:00', 'unique_authors': 8602, 'unique_threads': 2702, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 24, 'row_count': 50000, 'date_min': '2018-10-24T23:48:49+00:00', 'date_max': '2018-11-03T18:33:10+00:00', 'unique_authors': 8070, 'unique_threads': 2275, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 25, 'row_count': 50000, 'date_min': '2018-11-03T18:33:19+00:00', 'date_max': '2018-11-16T20:19:47+00:00', 'unique_authors': 7617, 'unique_threads': 2165, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 26, 'row_count': 50000, 'date_min': '2018-11-16T20:20:07+00:00', 'date_max': '2018-12-01T23:39:02+00:00', 'unique_authors': 7733, 'unique_threads': 2077, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 27, 'row_count': 50000, 'date_min': '2018-12-01T23:39:03+00:00', 'date_max': '2018-12-12T10:24:15+00:00', 'unique_authors': 7782, 'unique_threads': 1752, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 28, 'row_count': 50000, 'date_min': '2018-12-12T10:25:53+00:00', 'date_max': '2018-12-21T18:28:01+00:00', 'unique_authors': 7180, 'unique_threads': 1544, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part3.csv', 'batch': 29, 'row_count': 37717, 'date_min': '2018-12-21T18:28:49+00:00', 'date_max': '2018-12-31T00:05:03+00:00', 'unique_authors': 6277, 'unique_threads': 1617, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

,file,row_count,missing_thread_count,invalid_timestamp_count,missing_parent_id_count,unusual_thread_format_count,date_min,date_max,unique_authors,unique_threads,processing_seconds
0,wallstreetbets_comment_part3.csv,1437717,0,0,0,0,2017-04-01T05:41:35+00:00,2018-12-31T00:05:03+00:00,77224,92081,13.182367

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 1, 'row_count': 50000, 'date_min': '2018-12-31T00:00:33+00:00', 'date_max': '2019-01-10T15:45:20+00:00', 'unique_authors': 7844, 'unique_threads': 1665, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 2, 'row_count': 50000, 'date_min': '2019-01-10T15:45:33+00:00', 'date_max': '2019-01-20T20:02:57+00:00', 'unique_authors': 8680, 'unique_threads': 1615, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 3, 'row_count': 50000, 'date_min': '2019-01-20T20:03:54+00:00', 'date_max': '2019-01-31T01:47:11+00:00', 'unique_authors': 8973, 'unique_threads': 1453, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 4, 'row_count': 50000, 'date_min': '2019-01-31T01:47:14+00:00', 'date_max': '2019-02-11T18:33:01+00:00', 'unique_authors': 8806, 'unique_threads': 1412, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 5, 'row_count': 50000, 'date_min': '2019-02-11T18:33:03+00:00', 'date_max': '2019-02-24T16:07:12+00:00', 'unique_authors': 8190, 'unique_threads': 1524, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 6, 'row_count': 50000, 'date_min': '2019-02-24T16:07:43+00:00', 'date_max': '2019-03-07T17:47:18+00:00', 'unique_authors': 7571, 'unique_threads': 1410, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 7, 'row_count': 50000, 'date_min': '2019-03-07T17:47:26+00:00', 'date_max': '2019-03-19T19:12:15+00:00', 'unique_authors': 7574, 'unique_threads': 1442, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 8, 'row_count': 50000, 'date_min': '2019-03-19T19:12:30+00:00', 'date_max': '2019-03-29T15:41:36+00:00', 'unique_authors': 7525, 'unique_threads': 1233, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 9, 'row_count': 50000, 'date_min': '2019-03-29T15:41:40+00:00', 'date_max': '2019-04-07T21:11:46+00:00', 'unique_authors': 18966, 'unique_threads': 1175, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 10, 'row_count': 50000, 'date_min': '2019-04-07T21:12:18+00:00', 'date_max': '2019-04-17T11:06:41+00:00', 'unique_authors': 7406, 'unique_threads': 1545, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 11, 'row_count': 50000, 'date_min': '2019-04-17T11:06:42+00:00', 'date_max': '2019-04-26T23:17:07+00:00', 'unique_authors': 7909, 'unique_threads': 1672, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 12, 'row_count': 50000, 'date_min': '2019-04-26T23:17:12+00:00', 'date_max': '2019-05-06T00:46:23+00:00', 'unique_authors': 8031, 'unique_threads': 1726, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 13, 'row_count': 50000, 'date_min': '2019-05-06T00:46:28+00:00', 'date_max': '2019-05-13T13:59:31+00:00', 'unique_authors': 7189, 'unique_threads': 1451, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 14, 'row_count': 50000, 'date_min': '2019-05-13T13:59:36+00:00', 'date_max': '2019-05-22T15:32:21+00:00', 'unique_authors': 7093, 'unique_threads': 1305, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 15, 'row_count': 50000, 'date_min': '2019-05-22T15:32:23+00:00', 'date_max': '2019-06-02T04:06:48+00:00', 'unique_authors': 7320, 'unique_threads': 946, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 16, 'row_count': 50000, 'date_min': '2019-06-02T04:06:54+00:00', 'date_max': '2019-06-10T21:02:50+00:00', 'unique_authors': 7470, 'unique_threads': 1043, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 17, 'row_count': 50000, 'date_min': '2019-06-10T21:03:32+00:00', 'date_max': '2019-06-20T15:33:40+00:00', 'unique_authors': 7048, 'unique_threads': 1032, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 18, 'row_count': 50000, 'date_min': '2019-06-20T15:33:49+00:00', 'date_max': '2019-07-01T12:18:57+00:00', 'unique_authors': 8374, 'unique_threads': 1006, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 19, 'row_count': 50000, 'date_min': '2019-07-01T12:19:39+00:00', 'date_max': '2019-07-12T02:56:08+00:00', 'unique_authors': 8911, 'unique_threads': 1081, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 20, 'row_count': 50000, 'date_min': '2019-07-12T02:56:13+00:00', 'date_max': '2019-07-23T02:06:48+00:00', 'unique_authors': 8069, 'unique_threads': 1065, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 21, 'row_count': 50000, 'date_min': '2019-07-23T02:06:55+00:00', 'date_max': '2019-07-31T14:17:44+00:00', 'unique_authors': 8450, 'unique_threads': 1229, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 22, 'row_count': 50000, 'date_min': '2019-07-31T14:17:48+00:00', 'date_max': '2019-08-07T12:59:12+00:00', 'unique_authors': 8140, 'unique_threads': 1144, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 23, 'row_count': 50000, 'date_min': '2019-08-07T12:59:42+00:00', 'date_max': '2019-08-14T03:46:50+00:00', 'unique_authors': 10747, 'unique_threads': 972, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 24, 'row_count': 50000, 'date_min': '2019-08-14T03:46:51+00:00', 'date_max': '2019-08-20T20:39:58+00:00', 'unique_authors': 8680, 'unique_threads': 1161, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 25, 'row_count': 50000, 'date_min': '2019-08-20T20:40:09+00:00', 'date_max': '2019-08-26T22:43:45+00:00', 'unique_authors': 7596, 'unique_threads': 1107, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 26, 'row_count': 50000, 'date_min': '2019-08-26T22:43:48+00:00', 'date_max': '2019-09-03T22:50:06+00:00', 'unique_authors': 6615, 'unique_threads': 900, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 27, 'row_count': 50000, 'date_min': '2019-09-03T22:50:07+00:00', 'date_max': '2019-09-11T19:59:20+00:00', 'unique_authors': 7176, 'unique_threads': 870, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 28, 'row_count': 50000, 'date_min': '2019-09-11T19:59:24+00:00', 'date_max': '2019-09-19T15:55:56+00:00', 'unique_authors': 8088, 'unique_threads': 946, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 29, 'row_count': 50000, 'date_min': '2019-09-19T15:56:01+00:00', 'date_max': '2019-09-27T04:55:05+00:00', 'unique_authors': 6984, 'unique_threads': 824, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 30, 'row_count': 50000, 'date_min': '2019-09-27T04:55:48+00:00', 'date_max': '2019-10-05T15:40:29+00:00', 'unique_authors': 7135, 'unique_threads': 867, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 31, 'row_count': 50000, 'date_min': '2019-10-05T15:40:47+00:00', 'date_max': '2019-10-14T02:36:46+00:00', 'unique_authors': 6364, 'unique_threads': 757, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 32, 'row_count': 50000, 'date_min': '2019-10-14T02:36:51+00:00', 'date_max': '2019-10-22T17:01:45+00:00', 'unique_authors': 6367, 'unique_threads': 803, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 33, 'row_count': 50000, 'date_min': '2019-10-22T17:02:02+00:00', 'date_max': '2019-10-29T20:06:10+00:00', 'unique_authors': 8050, 'unique_threads': 915, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 34, 'row_count': 50000, 'date_min': '2019-10-29T20:06:11+00:00', 'date_max': '2019-11-05T19:11:32+00:00', 'unique_authors': 9337, 'unique_threads': 981, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 35, 'row_count': 50000, 'date_min': '2019-11-05T19:11:33+00:00', 'date_max': '2019-11-12T22:32:04+00:00', 'unique_authors': 9759, 'unique_threads': 1109, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 36, 'row_count': 50000, 'date_min': '2019-11-12T22:32:24+00:00', 'date_max': '2019-11-20T14:55:43+00:00', 'unique_authors': 8502, 'unique_threads': 990, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 37, 'row_count': 50000, 'date_min': '2019-11-20T14:56:08+00:00', 'date_max': '2019-11-28T05:36:23+00:00', 'unique_authors': 9595, 'unique_threads': 1043, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 38, 'row_count': 50000, 'date_min': '2019-11-28T05:36:28+00:00', 'date_max': '2019-12-07T02:40:47+00:00', 'unique_authors': 8625, 'unique_threads': 1101, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 39, 'row_count': 50000, 'date_min': '2019-12-07T02:41:23+00:00', 'date_max': '2019-12-17T03:28:31+00:00', 'unique_authors': 7583, 'unique_threads': 1046, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 40, 'row_count': 50000, 'date_min': '2019-12-17T03:28:35+00:00', 'date_max': '2019-12-27T19:00:24+00:00', 'unique_authors': 8639, 'unique_threads': 1039, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 41, 'row_count': 50000, 'date_min': '2019-12-27T19:00:35+00:00', 'date_max': '2020-01-06T15:22:03+00:00', 'unique_authors': 8183, 'unique_threads': 1085, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 42, 'row_count': 50000, 'date_min': '2020-01-06T15:22:11+00:00', 'date_max': '2020-01-12T15:41:21+00:00', 'unique_authors': 7333, 'unique_threads': 1081, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 43, 'row_count': 50000, 'date_min': '2020-01-12T15:41:45+00:00', 'date_max': '2020-01-17T14:34:29+00:00', 'unique_authors': 7425, 'unique_threads': 1063, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 44, 'row_count': 50000, 'date_min': '2020-01-17T14:34:39+00:00', 'date_max': '2020-01-23T16:54:56+00:00', 'unique_authors': 8001, 'unique_threads': 1093, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 45, 'row_count': 50000, 'date_min': '2020-01-23T16:54:58+00:00', 'date_max': '2020-01-28T14:36:15+00:00', 'unique_authors': 7446, 'unique_threads': 1014, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 46, 'row_count': 50000, 'date_min': '2020-01-28T14:36:20+00:00', 'date_max': '2020-01-31T18:50:15+00:00', 'unique_authors': 7702, 'unique_threads': 912, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part4.csv', 'batch': 47, 'row_count': 4903, 'date_min': '2020-01-31T18:50:23+00:00', 'date_max': '2020-02-01T00:00:15+00:00', 'unique_authors': 1776, 'unique_threads': 166, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

,file,row_count,missing_thread_count,invalid_timestamp_count,missing_parent_id_count,unusual_thread_format_count,date_min,date_max,unique_authors,unique_threads,processing_seconds
0,wallstreetbets_comment_part4.csv,2304903,0,0,0,0,2018-12-31T00:00:33+00:00,2020-02-01T00:00:15+00:00,116851,45685,15.48309

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 1, 'row_count': 50000, 'date_min': '2020-02-01T00:00:02+00:00', 'date_max': '2020-02-04T21:03:18+00:00', 'unique_authors': 8571, 'unique_threads': 1115, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 2, 'row_count': 50000, 'date_min': '2020-02-04T21:03:19+00:00', 'date_max': '2020-02-07T10:35:00+00:00', 'unique_authors': 10348, 'unique_threads': 938, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 3, 'row_count': 50000, 'date_min': '2020-02-07T10:35:02+00:00', 'date_max': '2020-02-11T03:27:34+00:00', 'unique_authors': 10269, 'unique_threads': 916, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 4, 'row_count': 50000, 'date_min': '2020-02-11T03:27:35+00:00', 'date_max': '2020-02-13T20:04:44+00:00', 'unique_authors': 9888, 'unique_threads': 1048, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 5, 'row_count': 50000, 'date_min': '2020-02-13T20:04:47+00:00', 'date_max': '2020-02-18T13:44:16+00:00', 'unique_authors': 9692, 'unique_threads': 1057, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 6, 'row_count': 50000, 'date_min': '2020-02-18T13:44:22+00:00', 'date_max': '2020-02-20T21:10:13+00:00', 'unique_authors': 10386, 'unique_threads': 1114, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 7, 'row_count': 50000, 'date_min': '2020-02-20T21:10:14+00:00', 'date_max': '2020-02-24T12:50:05+00:00', 'unique_authors': 10398, 'unique_threads': 1076, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 8, 'row_count': 50000, 'date_min': '2020-02-24T12:50:06+00:00', 'date_max': '2020-02-26T17:52:11+00:00', 'unique_authors': 9755, 'unique_threads': 1004, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 9, 'row_count': 50000, 'date_min': '2020-02-26T17:52:14+00:00', 'date_max': '2020-02-28T12:34:33+00:00', 'unique_authors': 9927, 'unique_threads': 1097, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 10, 'row_count': 50000, 'date_min': '2020-02-28T12:34:36+00:00', 'date_max': '2020-03-01T19:05:20+00:00', 'unique_authors': 10054, 'unique_threads': 1109, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 11, 'row_count': 50000, 'date_min': '2020-03-01T19:05:21+00:00', 'date_max': '2020-03-03T18:36:32+00:00', 'unique_authors': 10940, 'unique_threads': 989, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 12, 'row_count': 50000, 'date_min': '2020-03-03T18:36:35+00:00', 'date_max': '2020-03-05T20:19:36+00:00', 'unique_authors': 9892, 'unique_threads': 856, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 13, 'row_count': 50000, 'date_min': '2020-03-05T20:19:37+00:00', 'date_max': '2020-03-08T01:37:25+00:00', 'unique_authors': 10135, 'unique_threads': 935, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 14, 'row_count': 50000, 'date_min': '2020-03-08T01:37:28+00:00', 'date_max': '2020-03-10T00:57:35+00:00', 'unique_authors': 11076, 'unique_threads': 1001, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 15, 'row_count': 50000, 'date_min': '2020-03-10T00:57:37+00:00', 'date_max': '2020-03-11T19:30:47+00:00', 'unique_authors': 10714, 'unique_threads': 888, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 16, 'row_count': 50000, 'date_min': '2020-03-11T19:30:48+00:00', 'date_max': '2020-03-13T03:27:53+00:00', 'unique_authors': 12355, 'unique_threads': 1212, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 17, 'row_count': 50000, 'date_min': '2020-03-13T03:27:54+00:00', 'date_max': '2020-03-14T18:04:35+00:00', 'unique_authors': 12442, 'unique_threads': 1156, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 18, 'row_count': 50000, 'date_min': '2020-03-14T18:04:36+00:00', 'date_max': '2020-03-16T13:00:12+00:00', 'unique_authors': 13981, 'unique_threads': 1708, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 19, 'row_count': 50000, 'date_min': '2020-03-16T13:00:15+00:00', 'date_max': '2020-03-17T21:34:37+00:00', 'unique_authors': 13547, 'unique_threads': 1129, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 20, 'row_count': 50000, 'date_min': '2020-03-17T21:34:38+00:00', 'date_max': '2020-03-19T05:41:00+00:00', 'unique_authors': 13262, 'unique_threads': 1148, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 21, 'row_count': 50000, 'date_min': '2020-03-19T05:41:05+00:00', 'date_max': '2020-03-20T17:21:49+00:00', 'unique_authors': 12899, 'unique_threads': 1072, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 22, 'row_count': 50000, 'date_min': '2020-03-20T17:21:52+00:00', 'date_max': '2020-03-22T19:37:01+00:00', 'unique_authors': 12400, 'unique_threads': 1007, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 23, 'row_count': 50000, 'date_min': '2020-03-22T19:37:02+00:00', 'date_max': '2020-03-24T09:25:52+00:00', 'unique_authors': 12846, 'unique_threads': 865, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 24, 'row_count': 50000, 'date_min': '2020-03-24T09:26:06+00:00', 'date_max': '2020-03-25T19:52:36+00:00', 'unique_authors': 12863, 'unique_threads': 963, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 25, 'row_count': 50000, 'date_min': '2020-03-25T19:52:38+00:00', 'date_max': '2020-03-27T06:11:48+00:00', 'unique_authors': 13433, 'unique_threads': 979, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 26, 'row_count': 50000, 'date_min': '2020-03-27T06:11:51+00:00', 'date_max': '2020-03-29T14:24:00+00:00', 'unique_authors': 13037, 'unique_threads': 874, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 27, 'row_count': 50000, 'date_min': '2020-03-29T14:24:02+00:00', 'date_max': '2020-03-31T14:55:35+00:00', 'unique_authors': 12787, 'unique_threads': 826, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 28, 'row_count': 50000, 'date_min': '2020-03-31T14:55:37+00:00', 'date_max': '2020-04-02T12:54:41+00:00', 'unique_authors': 12301, 'unique_threads': 804, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 29, 'row_count': 50000, 'date_min': '2020-04-02T12:54:42+00:00', 'date_max': '2020-04-04T15:30:20+00:00', 'unique_authors': 11681, 'unique_threads': 903, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 30, 'row_count': 50000, 'date_min': '2020-04-04T15:30:24+00:00', 'date_max': '2020-04-07T00:40:48+00:00', 'unique_authors': 11283, 'unique_threads': 796, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 31, 'row_count': 50000, 'date_min': '2020-04-07T00:40:51+00:00', 'date_max': '2020-04-09T11:09:51+00:00', 'unique_authors': 12103, 'unique_threads': 947, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 32, 'row_count': 50000, 'date_min': '2020-04-09T11:09:52+00:00', 'date_max': '2020-04-11T16:18:22+00:00', 'unique_authors': 13763, 'unique_threads': 1186, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 33, 'row_count': 50000, 'date_min': '2020-04-11T16:18:27+00:00', 'date_max': '2020-04-14T02:12:21+00:00', 'unique_authors': 11582, 'unique_threads': 952, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 34, 'row_count': 50000, 'date_min': '2020-04-14T02:12:26+00:00', 'date_max': '2020-04-15T21:38:25+00:00', 'unique_authors': 12032, 'unique_threads': 1042, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 35, 'row_count': 50000, 'date_min': '2020-04-15T21:38:28+00:00', 'date_max': '2020-04-17T14:09:13+00:00', 'unique_authors': 11803, 'unique_threads': 946, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 36, 'row_count': 50000, 'date_min': '2020-04-17T14:09:14+00:00', 'date_max': '2020-04-20T00:07:50+00:00', 'unique_authors': 12753, 'unique_threads': 966, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 37, 'row_count': 50000, 'date_min': '2020-04-20T00:07:52+00:00', 'date_max': '2020-04-21T15:27:03+00:00', 'unique_authors': 13676, 'unique_threads': 1209, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 38, 'row_count': 50000, 'date_min': '2020-04-21T15:27:07+00:00', 'date_max': '2020-04-23T03:54:00+00:00', 'unique_authors': 12385, 'unique_threads': 1472, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 39, 'row_count': 50000, 'date_min': '2020-04-23T03:54:03+00:00', 'date_max': '2020-04-24T22:51:51+00:00', 'unique_authors': 12126, 'unique_threads': 1539, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 40, 'row_count': 50000, 'date_min': '2020-04-24T22:51:52+00:00', 'date_max': '2020-04-27T18:08:39+00:00', 'unique_authors': 12056, 'unique_threads': 1511, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 41, 'row_count': 50000, 'date_min': '2020-04-27T18:08:41+00:00', 'date_max': '2020-04-29T14:08:21+00:00', 'unique_authors': 11639, 'unique_threads': 1443, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 42, 'row_count': 50000, 'date_min': '2020-04-29T14:08:22+00:00', 'date_max': '2020-05-01T04:37:51+00:00', 'unique_authors': 11893, 'unique_threads': 1552, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 43, 'row_count': 50000, 'date_min': '2020-05-01T04:37:55+00:00', 'date_max': '2020-05-03T15:25:49+00:00', 'unique_authors': 12131, 'unique_threads': 1529, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 44, 'row_count': 50000, 'date_min': '2020-05-03T15:25:54+00:00', 'date_max': '2020-05-05T17:05:55+00:00', 'unique_authors': 10627, 'unique_threads': 1199, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 45, 'row_count': 50000, 'date_min': '2020-05-05T17:05:56+00:00', 'date_max': '2020-05-07T14:18:40+00:00', 'unique_authors': 10976, 'unique_threads': 1449, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 46, 'row_count': 50000, 'date_min': '2020-05-07T14:18:41+00:00', 'date_max': '2020-05-09T13:50:40+00:00', 'unique_authors': 10730, 'unique_threads': 1527, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 47, 'row_count': 50000, 'date_min': '2020-05-09T13:51:07+00:00', 'date_max': '2020-05-12T00:38:32+00:00', 'unique_authors': 10710, 'unique_threads': 1231, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 48, 'row_count': 50000, 'date_min': '2020-05-12T00:38:39+00:00', 'date_max': '2020-05-13T20:18:13+00:00', 'unique_authors': 11118, 'unique_threads': 1338, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 49, 'row_count': 50000, 'date_min': '2020-05-13T20:18:14+00:00', 'date_max': '2020-05-15T17:25:46+00:00', 'unique_authors': 10474, 'unique_threads': 1292, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 50, 'row_count': 50000, 'date_min': '2020-05-15T17:25:50+00:00', 'date_max': '2020-05-18T13:32:03+00:00', 'unique_authors': 10565, 'unique_threads': 1326, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 51, 'row_count': 50000, 'date_min': '2020-05-18T13:32:06+00:00', 'date_max': '2020-05-20T08:29:07+00:00', 'unique_authors': 10493, 'unique_threads': 1479, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 52, 'row_count': 50000, 'date_min': '2020-05-20T08:29:10+00:00', 'date_max': '2020-05-22T04:16:38+00:00', 'unique_authors': 9915, 'unique_threads': 1449, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 53, 'row_count': 50000, 'date_min': '2020-05-22T04:16:42+00:00', 'date_max': '2020-05-25T04:50:18+00:00', 'unique_authors': 9803, 'unique_threads': 1385, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 54, 'row_count': 50000, 'date_min': '2020-05-25T04:50:23+00:00', 'date_max': '2020-05-27T13:43:07+00:00', 'unique_authors': 10484, 'unique_threads': 1270, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 55, 'row_count': 50000, 'date_min': '2020-05-27T13:43:10+00:00', 'date_max': '2020-05-29T06:01:08+00:00', 'unique_authors': 10357, 'unique_threads': 1413, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 56, 'row_count': 50000, 'date_min': '2020-05-29T06:01:09+00:00', 'date_max': '2020-05-31T16:01:02+00:00', 'unique_authors': 10010, 'unique_threads': 1266, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part5.csv', 'batch': 57, 'row_count': 8327, 'date_min': '2020-05-31T16:01:04+00:00', 'date_max': '2020-06-01T00:00:07+00:00', 'unique_authors': 2766, 'unique_threads': 288, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

,file,row_count,missing_thread_count,invalid_timestamp_count,missing_parent_id_count,unusual_thread_format_count,date_min,date_max,unique_authors,unique_threads,processing_seconds
0,wallstreetbets_comment_part5.csv,2808327,0,0,0,0,2020-02-01T00:00:02+00:00,2020-06-01T00:00:07+00:00,128468,49828,19.053757

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 1, 'row_count': 50000, 'date_min': '2020-06-01T00:00:04+00:00', 'date_max': '2020-06-02T20:46:47+00:00', 'unique_authors': 9575, 'unique_threads': 1339, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 2, 'row_count': 50000, 'date_min': '2020-06-02T20:46:50+00:00', 'date_max': '2020-06-04T18:17:10+00:00', 'unique_authors': 10020, 'unique_threads': 861, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 3, 'row_count': 50000, 'date_min': '2020-06-04T18:17:11+00:00', 'date_max': '2020-06-06T19:52:25+00:00', 'unique_authors': 9953, 'unique_threads': 611, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 4, 'row_count': 50000, 'date_min': '2020-06-06T19:52:40+00:00', 'date_max': '2020-06-08T23:42:42+00:00', 'unique_authors': 9457, 'unique_threads': 577, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 5, 'row_count': 50000, 'date_min': '2020-06-08T23:42:45+00:00', 'date_max': '2020-06-10T15:30:49+00:00', 'unique_authors': 10636, 'unique_threads': 599, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 6, 'row_count': 50000, 'date_min': '2020-06-10T15:30:53+00:00', 'date_max': '2020-06-11T23:07:50+00:00', 'unique_authors': 11614, 'unique_threads': 1201, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 7, 'row_count': 50000, 'date_min': '2020-06-11T23:07:51+00:00', 'date_max': '2020-06-13T19:29:37+00:00', 'unique_authors': 11183, 'unique_threads': 1181, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 8, 'row_count': 50000, 'date_min': '2020-06-13T19:29:40+00:00', 'date_max': '2020-06-15T18:26:38+00:00', 'unique_authors': 9743, 'unique_threads': 908, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 9, 'row_count': 50000, 'date_min': '2020-06-15T18:26:41+00:00', 'date_max': '2020-06-17T08:05:25+00:00', 'unique_authors': 10431, 'unique_threads': 942, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 10, 'row_count': 50000, 'date_min': '2020-06-17T08:05:32+00:00', 'date_max': '2020-06-19T01:10:02+00:00', 'unique_authors': 10550, 'unique_threads': 1014, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 11, 'row_count': 50000, 'date_min': '2020-06-19T01:10:05+00:00', 'date_max': '2020-06-21T12:10:15+00:00', 'unique_authors': 10419, 'unique_threads': 1045, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 12, 'row_count': 50000, 'date_min': '2020-06-21T12:10:50+00:00', 'date_max': '2020-06-23T16:28:55+00:00', 'unique_authors': 10171, 'unique_threads': 892, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 13, 'row_count': 50000, 'date_min': '2020-06-23T16:28:57+00:00', 'date_max': '2020-06-25T14:24:24+00:00', 'unique_authors': 9785, 'unique_threads': 855, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 14, 'row_count': 50000, 'date_min': '2020-06-25T14:24:29+00:00', 'date_max': '2020-06-27T14:28:45+00:00', 'unique_authors': 10195, 'unique_threads': 962, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 15, 'row_count': 50000, 'date_min': '2020-06-27T14:28:47+00:00', 'date_max': '2020-06-30T01:20:34+00:00', 'unique_authors': 9460, 'unique_threads': 870, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 16, 'row_count': 50000, 'date_min': '2020-06-30T01:20:36+00:00', 'date_max': '2020-07-02T04:48:51+00:00', 'unique_authors': 9726, 'unique_threads': 958, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 17, 'row_count': 50000, 'date_min': '2020-07-02T04:48:52+00:00', 'date_max': '2020-07-05T11:42:45+00:00', 'unique_authors': 10164, 'unique_threads': 966, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 18, 'row_count': 50000, 'date_min': '2020-07-05T11:42:46+00:00', 'date_max': '2020-07-07T17:54:23+00:00', 'unique_authors': 9707, 'unique_threads': 875, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 19, 'row_count': 50000, 'date_min': '2020-07-07T17:54:25+00:00', 'date_max': '2020-07-09T16:14:06+00:00', 'unique_authors': 9471, 'unique_threads': 919, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 20, 'row_count': 50000, 'date_min': '2020-07-09T16:14:09+00:00', 'date_max': '2020-07-11T20:09:50+00:00', 'unique_authors': 9584, 'unique_threads': 1063, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 21, 'row_count': 50000, 'date_min': '2020-07-11T20:09:51+00:00', 'date_max': '2020-07-14T01:35:34+00:00', 'unique_authors': 9858, 'unique_threads': 985, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 22, 'row_count': 50000, 'date_min': '2020-07-14T01:35:40+00:00', 'date_max': '2020-07-15T19:55:51+00:00', 'unique_authors': 12073, 'unique_threads': 806, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 23, 'row_count': 50000, 'date_min': '2020-07-15T19:55:54+00:00', 'date_max': '2020-07-17T17:05:36+00:00', 'unique_authors': 11834, 'unique_threads': 928, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 24, 'row_count': 50000, 'date_min': '2020-07-17T17:05:39+00:00', 'date_max': '2020-07-20T16:44:12+00:00', 'unique_authors': 9754, 'unique_threads': 1015, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 25, 'row_count': 50000, 'date_min': '2020-07-20T16:44:14+00:00', 'date_max': '2020-07-22T16:52:06+00:00', 'unique_authors': 10008, 'unique_threads': 937, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 26, 'row_count': 50000, 'date_min': '2020-07-22T16:52:07+00:00', 'date_max': '2020-07-24T15:30:31+00:00', 'unique_authors': 10239, 'unique_threads': 999, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 27, 'row_count': 50000, 'date_min': '2020-07-24T15:30:34+00:00', 'date_max': '2020-07-27T17:41:53+00:00', 'unique_authors': 9996, 'unique_threads': 927, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 28, 'row_count': 50000, 'date_min': '2020-07-27T17:41:54+00:00', 'date_max': '2020-07-29T19:14:17+00:00', 'unique_authors': 10216, 'unique_threads': 990, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 29, 'row_count': 50000, 'date_min': '2020-07-29T19:14:18+00:00', 'date_max': '2020-07-31T16:04:58+00:00', 'unique_authors': 10748, 'unique_threads': 1049, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 30, 'row_count': 50000, 'date_min': '2020-07-31T16:05:00+00:00', 'date_max': '2020-08-03T14:43:49+00:00', 'unique_authors': 10310, 'unique_threads': 1141, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 31, 'row_count': 50000, 'date_min': '2020-08-03T14:43:51+00:00', 'date_max': '2020-08-05T11:55:26+00:00', 'unique_authors': 10334, 'unique_threads': 1143, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

{'file': 'wallstreetbets_comment_part6.csv', 'batch': 32, 'row_count': 19148, 'date_min': '2020-08-05T11:55:27+00:00', 'date_max': '2020-08-06T01:41:18+00:00', 'unique_authors': 5926, 'unique_threads': 595, 'missing_thread_count': 0, 'invalid_timestamp_count': 0, 'missing_parent_id_count': 0, 'unusual_thread_format_count': 0}

,file,row_count,missing_thread_count,invalid_timestamp_count,missing_parent_id_count,unusual_thread_format_count,date_min,date_max,unique_authors,unique_threads,processing_seconds
0,wallstreetbets_comment_part6.csv,1569148,0,0,0,0,2020-06-01T00:00:04+00:00,2020-08-06T01:41:18+00:00,79292,22840,9.529878

## 分批匯出全域 Thread Table

使用排序後的 SQLite cursor，逐一串流每個 thread 的唯一 ticker，並整理為排序後的 ticker 清單。

- Thread table 僅由「成功匹配且具有非空白標準化 `thread_id`」的留言建立。
- 聚合過程不使用 `parent_id`。

In [5]:
query = """SELECT t.thread_id,t.first_ns,t.last_ns,t.n_comments,
    (SELECT COUNT(*) FROM thread_authors a WHERE a.thread_id=t.thread_id)
    FROM threads t ORDER BY t.thread_id"""
ticker_cursor = iter(db.execute('SELECT thread_id,ticker FROM thread_tickers ORDER BY thread_id,ticker'))
next_ticker = next(ticker_cursor,None)
thread_cursor = db.execute(query)
thread_dest = OUT/'threads.parquet'
thread_partial = thread_dest.with_suffix('.parquet.partial')
thread_rows = grouped_comments = 0
with pq.ParquetWriter(thread_partial, THREAD_SCHEMA, compression='zstd') as writer:
    while True:
        rows = thread_cursor.fetchmany(5000)
        if not rows: break
        records = []
        for thread, first, last, count, authors in rows:
            tickers = []
            while next_ticker is not None and next_ticker[0] == thread:
                tickers.append(next_ticker[1])
                next_ticker = next(ticker_cursor,None)
            assert tickers and (first is None or last >= first)
            records.append({'thread_id':thread,'first_timestamp':first,'last_timestamp':last,
                            'n_comments':count,'n_authors':authors,'tickers_in_thread':tickers,'n_unique_tickers':len(tickers)})
            grouped_comments += count
        writer.write_table(pa.Table.from_pylist(records, schema=THREAD_SCHEMA))
        thread_rows += len(records)
assert next_ticker is None
assert pq.read_metadata(thread_partial).num_rows == thread_rows
thread_partial.replace(thread_dest)
print({'thread_rows':thread_rows, 'represented_matched_comments':grouped_comments})

{'thread_rows': 258609, 'represented_matched_comments': 8714953}

## 最終診斷與一致性檢查

- Comment 總列數不得改變。
- 所有 thread 的 `n_comments` 加總，應等於 matched comments 減去缺少 `thread_id` 的列數。
- Author 與 thread 數量以全資料的唯一值聯集計算，不直接加總各檔案結果。
- 比對來源 CSV 的檔案大小與修改時間，確認原始資料未被變更。

In [6]:
overall = {'file':'ALL_FILES'}
for key in ['row_count','missing_thread_count','invalid_timestamp_count','missing_parent_id_count','unusual_thread_format_count']:
    overall[key] = sum(s[key] for s in summaries)
for key, op in [('date_min',min),('date_max',max)]:
    values = [s[key] for s in summaries if s[key] is not None]
    overall[key] = op(values) if values else None
overall['unique_authors'] = db.execute('SELECT COUNT(DISTINCT author) FROM file_authors').fetchone()[0]
overall['unique_threads'] = thread_rows
overall['processing_seconds'] = time.perf_counter()-started
assert grouped_comments == overall['row_count']-overall['missing_thread_count']
assert thread_rows == db.execute('SELECT COUNT(*) FROM threads').fetchone()[0]
assert overall['row_count'] == (MATCH_MANIFEST if 'overall' in MATCH_MANIFEST else json.loads((MATCH_DIR/'summary.json').read_text()))['overall']['matched_comment_count']
assert SOURCE_METADATA == {p:[Path(p).stat().st_size,Path(p).stat().st_mtime_ns] for p in SOURCE_METADATA}
table = pd.DataFrame(summaries+[overall])
display(table)
db.close()
remove_work_database(WORK_DB)
display(next(pq.ParquetFile(FILES[0]).iter_batches(batch_size=3)).to_pandas())
display(next(pq.ParquetFile(thread_dest).iter_batches(batch_size=3)).to_pandas())
print('Thread aggregation finished:', OUT)

,file,row_count,missing_thread_count,invalid_timestamp_count,missing_parent_id_count,unusual_thread_format_count,date_min,date_max,unique_authors,unique_threads,processing_seconds
0,wallstreetbets_comment_part1.csv,221516,14,14,14,0,2012-04-11T16:46:43+00:00,2016-04-25T12:28:09+00:00,14439,19409,2.306682
1,wallstreetbets_comment_part2.csv,373356,0,0,0,0,2016-04-25T12:29:23+00:00,2017-04-01T06:13:54+00:00,25508,31185,3.819426
2,wallstreetbets_comment_part3.csv,1437717,0,0,0,0,2017-04-01T05:41:35+00:00,2018-12-31T00:05:03+00:00,77224,92081,13.182367
3,wallstreetbets_comment_part4.csv,2304903,0,0,0,0,2018-12-31T00:00:33+00:00,2020-02-01T00:00:15+00:00,116851,45685,15.483090
4,wallstreetbets_comment_part5.csv,2808327,0,0,0,0,2020-02-01T00:00:02+00:00,2020-06-01T00:00:07+00:00,128468,49828,19.053757
5,wallstreetbets_comment_part6.csv,1569148,0,0,0,0,2020-06-01T00:00:04+00:00,2020-08-06T01:41:18+00:00,79292,22840,9.529878
6,ALL_FILES,8714967,14,14,14,0,2012-04-11T16:46:43+00:00,2020-08-06T01:41:18+00:00,309073,258609,69.279034

,comment_id,author,created_utc,link_id,body,matched_tickers,matched_ticker_count,source_file,source_row,id,parent_id,thread_id,created_datetime_utc,created_date,year_month
0,c4b0pvu,secondhandsondek,1334162803.0,t3_s4jw1,This is a fantastic idea Ill toss mine up in a...,"[BIT, BMO, JPM]",3,wallstreetbets_comment_part1.csv,1,c4b0pvu,t3_s4jw1,s4jw1,2012-04-11 16:46:43+00:00,2012-04-11,2012-04
1,c4b1fpf,glorysk87,1334165948.0,t3_s4jw1,INTC is on 417,[INTC],1,wallstreetbets_comment_part1.csv,2,c4b1fpf,t3_s4jw1,s4jw1,2012-04-11 17:39:08+00:00,2012-04-11,2012-04
2,c4b1rmm,entsportsjunkie,1334167351.0,t3_s4jw1,straddle call straddle put put put straddle ca...,"[CALL, FOR, MORE, ONE, TECH]",5,wallstreetbets_comment_part1.csv,3,c4b1rmm,t3_s4jw1,s4jw1,2012-04-11 18:02:31+00:00,2012-04-11,2012-04

,thread_id,first_timestamp,last_timestamp,n_comments,n_authors,tickers_in_thread,n_unique_tickers
0,100w1h,2012-09-17 20:19:16+00:00,2012-10-09 21:26:37+00:00,5,4,"[FOR, GOOD, NOW, RUN, WELL]",5
1,10378k,2012-09-18 17:44:13+00:00,2012-10-08 22:12:49+00:00,10,9,"[AGO, ALL, AMD, ANY, APU, ATI, CAP, FOR, FULL,...",26
2,1056p3,2012-09-19 23:55:06+00:00,2012-10-04 16:47:59+00:00,15,5,"[ALL, ANY, APDN, ARE, FAST, FOR, GAIN, GOOD, G...",28

Thread aggregation finished: C:\Users\eagle\RedditStock\Data\process\03_thread_construction\2026-09-22_03-38-31_UTC

## 匯出 Thread-Ticker

將每個 thread 的唯一 ticker 指派至該 thread「首次匹配留言」所在的 UTC 月份。

- 若 thread 缺少首次匹配時間，停止匯出，不自行補月份。
- 輸出僅包含三欄：`thread_id`、`ticker`、`year_month`。
- 此表不包含 author 資訊。

In [7]:
RUN = OUT
SOURCE = OUT/'threads.parquet'
DEST = OUT/'thread_ticker.parquet'
PARTIAL = DEST.with_suffix('.parquet.partial')
SCHEMA = pa.schema([('thread_id',pa.string()),('thread_month',pa.string()),('ticker',pa.string())])
source_stat = (SOURCE.stat().st_size,SOURCE.stat().st_mtime_ns)
started=time.perf_counter()
rows=threads=cross_month=0
month_counts={}
diagnostics=[]
previous_thread=None
all_tickers=set()  # bounded by the upstream ticker dictionary, not comment count
with pq.ParquetWriter(PARTIAL,SCHEMA,compression='zstd') as writer:
    for batch_no,batch in enumerate(pq.ParquetFile(SOURCE).iter_batches(batch_size=5000),1):
        frame=batch.to_pandas()
        assert frame.thread_id.notna().all() and frame.thread_id.ne('').all()
        assert frame.thread_id.is_monotonic_increasing and frame.thread_id.is_unique
        if previous_thread is not None: assert previous_thread < frame.thread_id.iloc[0]
        previous_thread=frame.thread_id.iloc[-1]
        first=pd.to_datetime(frame.first_timestamp,utc=True)
        last=pd.to_datetime(frame.last_timestamp,utc=True)
        assert first.notna().all(), 'Cannot assign thread month without a valid first timestamp'
        assert (last>=first).all()
        assert all(list(ts)==sorted(set(ts)) and len(ts)==count and count>0
                   for ts,count in zip(frame.tickers_in_thread,frame.n_unique_tickers))
        frame['thread_month']=first.dt.strftime('%Y-%m')
        cross_month+=int(frame.thread_month.ne(last.dt.strftime('%Y-%m')).sum())
        output=frame[['thread_id','thread_month','tickers_in_thread']].explode('tickers_in_thread').rename(columns={'tickers_in_thread':'ticker'})
        assert len(output)==int(frame.n_unique_tickers.sum())
        assert not output.duplicated().any()
        writer.write_table(pa.Table.from_pandas(output,schema=SCHEMA,preserve_index=False),row_group_size=50000)
        rows+=len(output)
        threads+=len(frame)
        all_tickers.update(output.ticker.unique())
        for month,count in output.groupby('thread_month').size().items():
            month_counts[month]=month_counts.get(month,0)+int(count)
        diag={'batch':batch_no,'input_thread_rows':len(frame),'output_rows':len(output),
              'date_min':first.min().isoformat(),'date_max':first.max().isoformat(),
              'unique_threads':int(output.thread_id.nunique()),'unique_tickers':int(output.ticker.nunique()),
              'unique_authors':'N/A: no author column'}
        diagnostics.append(diag)
        print(diag,flush=True)
assert pq.read_metadata(PARTIAL).num_rows==rows
assert threads==pq.read_metadata(SOURCE).num_rows
assert source_stat==(SOURCE.stat().st_size,SOURCE.stat().st_mtime_ns)
PARTIAL.replace(DEST)
summary={'source':str(SOURCE),'output':str(DEST),'rows':rows,'unique_threads':threads,
         'unique_tickers':len(all_tickers),'unique_authors':'N/A: no author column',
         'date_min':min(d['date_min'] for d in diagnostics),'date_max':max(d['date_max'] for d in diagnostics),
         'thread_month_min':min(month_counts),'thread_month_max':max(month_counts),
         'threads_spanning_months':cross_month,'processing_seconds':time.perf_counter()-started,
         'thread_month_definition':'UTC month of first matched comment; all thread tickers assigned to that month',
         'validation':'unique sorted source threads, unique tickers per thread, exact explode counts and output footer checked'}
display(pd.DataFrame([summary]))
display(pd.DataFrame(sorted(month_counts.items()),columns=['thread_month','ticker_rows']))
display(next(pq.ParquetFile(DEST).iter_batches(batch_size=10)).to_pandas())

{'batch': 1, 'input_thread_rows': 5000, 'output_rows': 91371, 'date_min': '2012-09-17T20:19:16+00:00', 'date_max': '2015-08-11T02:19:13+00:00', 'unique_threads': 5000, 'unique_tickers': 1584, 'unique_authors': 'N/A: no author column'}

{'batch': 2, 'input_thread_rows': 5000, 'output_rows': 90707, 'date_min': '2015-06-27T15:32:41+00:00', 'date_max': '2016-02-01T08:45:52+00:00', 'unique_threads': 5000, 'unique_tickers': 1546, 'unique_authors': 'N/A: no author column'}

{'batch': 3, 'input_thread_rows': 5000, 'output_rows': 96517, 'date_min': '2015-11-05T13:50:23+00:00', 'date_max': '2016-07-19T19:29:06+00:00', 'unique_threads': 5000, 'unique_tickers': 1606, 'unique_authors': 'N/A: no author column'}

{'batch': 4, 'input_thread_rows': 5000, 'output_rows': 88912, 'date_min': '2016-02-25T17:49:11+00:00', 'date_max': '2016-05-20T17:20:26+00:00', 'unique_threads': 5000, 'unique_tickers': 1617, 'unique_authors': 'N/A: no author column'}

{'batch': 5, 'input_thread_rows': 5000, 'output_rows': 86029, 'date_min': '2016-05-09T16:51:37+00:00', 'date_max': '2017-02-11T23:37:18+00:00', 'unique_threads': 5000, 'unique_tickers': 1556, 'unique_authors': 'N/A: no author column'}

{'batch': 6, 'input_thread_rows': 5000, 'output_rows': 80420, 'date_min': '2016-07-14T03:01:21+00:00', 'date_max': '2017-01-25T04:38:10+00:00', 'unique_threads': 5000, 'unique_tickers': 1484, 'unique_authors': 'N/A: no author column'}

{'batch': 7, 'input_thread_rows': 5000, 'output_rows': 77181, 'date_min': '2016-08-31T14:03:00+00:00', 'date_max': '2017-02-27T15:24:47+00:00', 'unique_threads': 5000, 'unique_tickers': 1403, 'unique_authors': 'N/A: no author column'}

{'batch': 8, 'input_thread_rows': 5000, 'output_rows': 71241, 'date_min': '2016-10-25T16:17:32+00:00', 'date_max': '2016-12-17T03:09:28+00:00', 'unique_threads': 5000, 'unique_tickers': 1435, 'unique_authors': 'N/A: no author column'}

{'batch': 9, 'input_thread_rows': 5000, 'output_rows': 82162, 'date_min': '2016-12-14T18:11:21+00:00', 'date_max': '2017-03-27T17:47:00+00:00', 'unique_threads': 5000, 'unique_tickers': 1626, 'unique_authors': 'N/A: no author column'}

{'batch': 10, 'input_thread_rows': 5000, 'output_rows': 96144, 'date_min': '2017-02-09T22:06:37+00:00', 'date_max': '2017-04-15T17:48:36+00:00', 'unique_threads': 5000, 'unique_tickers': 1567, 'unique_authors': 'N/A: no author column'}

{'batch': 11, 'input_thread_rows': 5000, 'output_rows': 90463, 'date_min': '2017-04-03T00:08:17+00:00', 'date_max': '2017-09-03T07:49:06+00:00', 'unique_threads': 5000, 'unique_tickers': 1492, 'unique_authors': 'N/A: no author column'}

{'batch': 12, 'input_thread_rows': 5000, 'output_rows': 92037, 'date_min': '2017-06-02T04:46:33+00:00', 'date_max': '2017-08-04T18:53:37+00:00', 'unique_threads': 5000, 'unique_tickers': 1460, 'unique_authors': 'N/A: no author column'}

{'batch': 13, 'input_thread_rows': 5000, 'output_rows': 84813, 'date_min': '2017-07-24T19:16:07+00:00', 'date_max': '2017-09-15T17:07:47+00:00', 'unique_threads': 5000, 'unique_tickers': 1628, 'unique_authors': 'N/A: no author column'}

{'batch': 14, 'input_thread_rows': 5000, 'output_rows': 82626, 'date_min': '2017-09-15T14:50:24+00:00', 'date_max': '2017-12-23T23:47:04+00:00', 'unique_threads': 5000, 'unique_tickers': 1536, 'unique_authors': 'N/A: no author column'}

{'batch': 15, 'input_thread_rows': 5000, 'output_rows': 82366, 'date_min': '2017-11-02T14:55:04+00:00', 'date_max': '2018-05-18T18:24:59+00:00', 'unique_threads': 5000, 'unique_tickers': 1463, 'unique_authors': 'N/A: no author column'}

{'batch': 16, 'input_thread_rows': 5000, 'output_rows': 77364, 'date_min': '2017-12-28T21:13:07+00:00', 'date_max': '2018-03-16T01:17:42+00:00', 'unique_threads': 5000, 'unique_tickers': 1411, 'unique_authors': 'N/A: no author column'}

{'batch': 17, 'input_thread_rows': 5000, 'output_rows': 75561, 'date_min': '2018-02-06T18:10:55+00:00', 'date_max': '2018-03-31T20:53:04+00:00', 'unique_threads': 5000, 'unique_tickers': 1365, 'unique_authors': 'N/A: no author column'}

{'batch': 18, 'input_thread_rows': 5000, 'output_rows': 83364, 'date_min': '2018-03-12T13:46:24+00:00', 'date_max': '2020-06-12T02:11:10+00:00', 'unique_threads': 5000, 'unique_tickers': 1360, 'unique_authors': 'N/A: no author column'}

{'batch': 19, 'input_thread_rows': 5000, 'output_rows': 86074, 'date_min': '2018-04-15T02:50:22+00:00', 'date_max': '2018-05-18T19:23:24+00:00', 'unique_threads': 5000, 'unique_tickers': 1339, 'unique_authors': 'N/A: no author column'}

{'batch': 20, 'input_thread_rows': 5000, 'output_rows': 82881, 'date_min': '2018-05-18T03:44:23+00:00', 'date_max': '2018-10-12T20:43:15+00:00', 'unique_threads': 5000, 'unique_tickers': 1369, 'unique_authors': 'N/A: no author column'}

{'batch': 21, 'input_thread_rows': 5000, 'output_rows': 79410, 'date_min': '2018-06-14T22:53:35+00:00', 'date_max': '2018-08-13T14:44:36+00:00', 'unique_threads': 5000, 'unique_tickers': 1334, 'unique_authors': 'N/A: no author column'}

{'batch': 22, 'input_thread_rows': 5000, 'output_rows': 85163, 'date_min': '2018-07-07T14:52:06+00:00', 'date_max': '2018-09-18T05:51:48+00:00', 'unique_threads': 5000, 'unique_tickers': 1329, 'unique_authors': 'N/A: no author column'}

{'batch': 23, 'input_thread_rows': 5000, 'output_rows': 80976, 'date_min': '2018-07-31T02:47:32+00:00', 'date_max': '2018-10-03T12:22:36+00:00', 'unique_threads': 5000, 'unique_tickers': 1386, 'unique_authors': 'N/A: no author column'}

{'batch': 24, 'input_thread_rows': 5000, 'output_rows': 81565, 'date_min': '2018-08-20T02:55:15+00:00', 'date_max': '2018-12-20T18:23:04+00:00', 'unique_threads': 5000, 'unique_tickers': 1448, 'unique_authors': 'N/A: no author column'}

{'batch': 25, 'input_thread_rows': 5000, 'output_rows': 80872, 'date_min': '2018-09-09T13:16:44+00:00', 'date_max': '2018-10-03T22:46:36+00:00', 'unique_threads': 5000, 'unique_tickers': 1492, 'unique_authors': 'N/A: no author column'}

{'batch': 26, 'input_thread_rows': 5000, 'output_rows': 79430, 'date_min': '2018-09-28T15:36:32+00:00', 'date_max': '2018-12-13T23:38:52+00:00', 'unique_threads': 5000, 'unique_tickers': 1494, 'unique_authors': 'N/A: no author column'}

{'batch': 27, 'input_thread_rows': 5000, 'output_rows': 87232, 'date_min': '2018-10-18T15:42:53+00:00', 'date_max': '2019-04-11T18:41:01+00:00', 'unique_threads': 5000, 'unique_tickers': 1607, 'unique_authors': 'N/A: no author column'}

{'batch': 28, 'input_thread_rows': 5000, 'output_rows': 97668, 'date_min': '2018-11-14T14:49:52+00:00', 'date_max': '2018-12-19T21:34:23+00:00', 'unique_threads': 5000, 'unique_tickers': 1685, 'unique_authors': 'N/A: no author column'}

{'batch': 29, 'input_thread_rows': 5000, 'output_rows': 95940, 'date_min': '2018-12-19T20:30:10+00:00', 'date_max': '2019-01-23T00:49:38+00:00', 'unique_threads': 5000, 'unique_tickers': 1658, 'unique_authors': 'N/A: no author column'}

{'batch': 30, 'input_thread_rows': 5000, 'output_rows': 111063, 'date_min': '2019-01-22T22:20:00+00:00', 'date_max': '2019-04-16T04:09:27+00:00', 'unique_threads': 5000, 'unique_tickers': 2137, 'unique_authors': 'N/A: no author column'}

{'batch': 31, 'input_thread_rows': 5000, 'output_rows': 109273, 'date_min': '2019-03-08T01:43:29+00:00', 'date_max': '2019-05-03T23:11:26+00:00', 'unique_threads': 5000, 'unique_tickers': 1927, 'unique_authors': 'N/A: no author column'}

{'batch': 32, 'input_thread_rows': 5000, 'output_rows': 97195, 'date_min': '2019-04-18T17:51:34+00:00', 'date_max': '2019-08-06T03:04:39+00:00', 'unique_threads': 5000, 'unique_tickers': 1780, 'unique_authors': 'N/A: no author column'}

{'batch': 33, 'input_thread_rows': 5000, 'output_rows': 143389, 'date_min': '2019-05-20T00:49:46+00:00', 'date_max': '2019-09-28T03:25:50+00:00', 'unique_threads': 5000, 'unique_tickers': 2178, 'unique_authors': 'N/A: no author column'}

{'batch': 34, 'input_thread_rows': 5000, 'output_rows': 128408, 'date_min': '2019-07-16T16:03:17+00:00', 'date_max': '2019-10-25T01:08:03+00:00', 'unique_threads': 5000, 'unique_tickers': 2051, 'unique_authors': 'N/A: no author column'}

{'batch': 35, 'input_thread_rows': 5000, 'output_rows': 156189, 'date_min': '2019-08-23T20:00:50+00:00', 'date_max': '2020-01-10T21:32:29+00:00', 'unique_threads': 5000, 'unique_tickers': 2253, 'unique_authors': 'N/A: no author column'}

{'batch': 36, 'input_thread_rows': 5000, 'output_rows': 153997, 'date_min': '2019-10-18T09:32:02+00:00', 'date_max': '2020-04-22T07:37:46+00:00', 'unique_threads': 5000, 'unique_tickers': 2348, 'unique_authors': 'N/A: no author column'}

{'batch': 37, 'input_thread_rows': 5000, 'output_rows': 145731, 'date_min': '2019-12-04T20:37:27+00:00', 'date_max': '2020-07-03T23:39:21+00:00', 'unique_threads': 5000, 'unique_tickers': 2277, 'unique_authors': 'N/A: no author column'}

{'batch': 38, 'input_thread_rows': 5000, 'output_rows': 124030, 'date_min': '2020-01-20T05:24:31+00:00', 'date_max': '2020-06-16T16:12:54+00:00', 'unique_threads': 5000, 'unique_tickers': 2006, 'unique_authors': 'N/A: no author column'}

{'batch': 39, 'input_thread_rows': 5000, 'output_rows': 121273, 'date_min': '2020-02-12T18:18:07+00:00', 'date_max': '2020-07-05T21:01:56+00:00', 'unique_threads': 5000, 'unique_tickers': 1985, 'unique_authors': 'N/A: no author column'}

{'batch': 40, 'input_thread_rows': 5000, 'output_rows': 124982, 'date_min': '2020-02-29T13:28:46+00:00', 'date_max': '2020-07-13T02:59:15+00:00', 'unique_threads': 5000, 'unique_tickers': 1930, 'unique_authors': 'N/A: no author column'}

{'batch': 41, 'input_thread_rows': 5000, 'output_rows': 106782, 'date_min': '2020-03-13T05:03:21+00:00', 'date_max': '2020-07-16T05:19:48+00:00', 'unique_threads': 5000, 'unique_tickers': 1806, 'unique_authors': 'N/A: no author column'}

{'batch': 42, 'input_thread_rows': 5000, 'output_rows': 145393, 'date_min': '2020-03-21T01:22:03+00:00', 'date_max': '2020-08-06T00:42:01+00:00', 'unique_threads': 5000, 'unique_tickers': 1978, 'unique_authors': 'N/A: no author column'}

{'batch': 43, 'input_thread_rows': 5000, 'output_rows': 138614, 'date_min': '2020-04-05T01:55:11+00:00', 'date_max': '2020-07-24T01:21:29+00:00', 'unique_threads': 5000, 'unique_tickers': 2064, 'unique_authors': 'N/A: no author column'}

{'batch': 44, 'input_thread_rows': 5000, 'output_rows': 91435, 'date_min': '2020-04-20T19:46:40+00:00', 'date_max': '2020-07-13T12:59:08+00:00', 'unique_threads': 5000, 'unique_tickers': 1956, 'unique_authors': 'N/A: no author column'}

{'batch': 45, 'input_thread_rows': 5000, 'output_rows': 88601, 'date_min': '2020-04-29T00:51:24+00:00', 'date_max': '2020-06-15T02:20:16+00:00', 'unique_threads': 5000, 'unique_tickers': 1971, 'unique_authors': 'N/A: no author column'}

{'batch': 46, 'input_thread_rows': 5000, 'output_rows': 94229, 'date_min': '2020-05-07T20:43:38+00:00', 'date_max': '2020-05-22T19:33:21+00:00', 'unique_threads': 5000, 'unique_tickers': 2180, 'unique_authors': 'N/A: no author column'}

{'batch': 47, 'input_thread_rows': 5000, 'output_rows': 89658, 'date_min': '2020-05-18T15:47:23+00:00', 'date_max': '2020-05-30T22:41:35+00:00', 'unique_threads': 5000, 'unique_tickers': 2083, 'unique_authors': 'N/A: no author column'}

{'batch': 48, 'input_thread_rows': 5000, 'output_rows': 99944, 'date_min': '2020-05-28T17:38:54+00:00', 'date_max': '2020-08-01T01:41:29+00:00', 'unique_threads': 5000, 'unique_tickers': 2440, 'unique_authors': 'N/A: no author column'}

{'batch': 49, 'input_thread_rows': 5000, 'output_rows': 103997, 'date_min': '2020-06-11T23:00:44+00:00', 'date_max': '2020-07-12T18:52:02+00:00', 'unique_threads': 5000, 'unique_tickers': 2267, 'unique_authors': 'N/A: no author column'}

{'batch': 50, 'input_thread_rows': 5000, 'output_rows': 114143, 'date_min': '2020-06-25T04:43:49+00:00', 'date_max': '2020-07-12T21:17:37+00:00', 'unique_threads': 5000, 'unique_tickers': 2408, 'unique_authors': 'N/A: no author column'}

{'batch': 51, 'input_thread_rows': 5000, 'output_rows': 115406, 'date_min': '2020-07-12T05:37:57+00:00', 'date_max': '2020-07-31T02:35:33+00:00', 'unique_threads': 5000, 'unique_tickers': 2523, 'unique_authors': 'N/A: no author column'}

{'batch': 52, 'input_thread_rows': 3609, 'output_rows': 76314, 'date_min': '2012-04-11T16:46:43+00:00', 'date_max': '2020-08-06T01:21:55+00:00', 'unique_threads': 3609, 'unique_tickers': 2086, 'unique_authors': 'N/A: no author column'}

,source,output,rows,unique_threads,unique_tickers,unique_authors,date_min,date_max,thread_month_min,thread_month_max,threads_spanning_months,processing_seconds,thread_month_definition,validation
0,C:\Users\eagle\RedditStock\Data\process\03_thr...,C:\Users\eagle\RedditStock\Data\process\03_thr...,5146535,258609,5682,N/A: no author column,2012-04-11T16:46:43+00:00,2020-08-06T01:21:55+00:00,2012-04,2020-08,13148,5.919108,UTC month of first matched comment; all thread...,"unique sorted source threads, unique tickers p..."

    thread_month  ticker_rows
0        2012-04          359
1        2012-05         2439
2        2012-06         1336
3        2012-07         1269
4        2012-08         1450
..           ...          ...
96       2020-04       285991
97       2020-05       275796
98       2020-06       216889
99       2020-07       221440
100      2020-08        38464

[101 rows x 2 columns]

  thread_id thread_month ticker
0    100w1h      2012-09    FOR
1    100w1h      2012-09   GOOD
2    100w1h      2012-09    NOW
3    100w1h      2012-09    RUN
4    100w1h      2012-09   WELL
5    10378k      2012-09    AGO
6    10378k      2012-09    ALL
7    10378k      2012-09    AMD
8    10378k      2012-09    ANY
9    10378k      2012-09    APU

In [8]:
pointer_state=json.loads(POINTER.read_text()) if POINTER.exists() else {}
assert pointer_state.get('matching_manifest')==str(MATCH_MANIFEST_PATH), 'Upstream pointer changed'
publish(ROOT,'thread',OUT,{'matching_input':str(MATCH_DIR),'batch_size':BATCH,
    'source_metadata':SOURCE_METADATA,'timezone':'UTC','files':summaries,'overall':overall,
    'thread_table_rows':thread_rows,'thread_table_n_comments_sum':grouped_comments,
    'thread_ticker':summary,'month_counts':month_counts,
    'missing_thread_policy':'retain comments; exclude from thread table',
    'invalid_date_policy':'retain comments; null derived dates'})
print('COMPLETE:',OUT)

COMPLETE: C:\Users\eagle\RedditStock\Data\process\03_thread_construction\2026-09-22_03-38-31_UTC