# t04_1：人工排除 ticker 後的診斷統計

## 定義與假設
- 只依已審核 CSV 的 `exclude=1` 排除；未填 reason 仍接受並統計，不新增自動高頻詞或人工猜測規則。
- 使用審核 run_summary 指定的 03 threads.parquet，以確保前後比較與審核資料一致。
- **mention 定義：**一個 thread 中一支 unique ticker 計一次；不是原始留言詞次或 comment–ticker 次數。
- 有效 thread 定義為至少一支 ticker。原始 thread 全部保留於診斷，包括排除後為零者；不直接產生新的清理資料。
- 主分布、門檻比例及 pair 分布以全部原始 threads 為母體，包含零值。另提供僅有效 threads 的 ticker 數分布。門檻比例的分母固定為原始 thread 數。
- 百分位數採 NumPy linear interpolation；同分 ticker 按字母排序，前 20 threads 同分按 thread_id 降冪排序。
- potential_pairs 是各 thread 的 n*(n-1)//2；同一股票 pair 出現在不同 thread 會重複貢獻，不等於全域 unique edges，也不是 rolling network。
- 分批讀取，只在 RAM 保留 ticker 計數、每個 thread 的整數統計及前 20 名資料，不建立 pair 明細。
- 作者不在此分析投影中，unique authors 標為 N/A；日期為 thread 的 first_timestamp，使用 UTC。
- 新 run 只輸出簡潔比較表與一份完整 JSON 報告。既有審核表、03 輸出及 pipeline 指向均不改動。


## ???after ??
- before ?????? threads?after ? ticker ????????? potential pair ????????? ticker ? ?1 ? threads?`population_threads` ???????`tickers_*` ?????????
- after ???? ticker ?? 0????????????????? ticker ????? impact ? `zero_ticker_threads_after`?
- ?????????? ?2 ?? <2?? thread ??????????? threads????????????mentions ? pair ???????? before ??????

In [1]:
from pathlib import Path
from datetime import datetime, timezone
from collections import Counter
import json, hashlib, heapq, time, csv, io
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
from IPython.display import display
ROOT=next(p for p in (Path.cwd(),*Path.cwd().parents) if (p/'Data/process').is_dir())
REVIEW_FILE=ROOT/'Data/process/t_04_ticker_review/2026-09-22_09-42-10_UTC/top200_ticker_review.csv'
review_bytes=REVIEW_FILE.read_bytes()
parsed=list(csv.reader(io.StringIO(review_bytes.decode('utf-8-sig')),strict=True))
header=parsed[0]
review_records=[]
trailing_empty_repairs=[]
for line,row in enumerate(parsed[1:],2):
    if len(row)>len(header) and all(value=='' for value in row[len(header):]):
        trailing_empty_repairs.append(line)
        row=row[:len(header)]
    assert len(row)==len(header), ('Unexpected review CSV fields',line)
    review_records.append(row)
review=pd.DataFrame(review_records,columns=header)
review_meta=json.loads((REVIEW_FILE.parent/'run_summary.json').read_text(encoding='utf-8'))
assert review.ticker.is_unique and review.exclude.str.strip().isin(['0','1']).all()
assert set(review.ticker)=={r['ticker'] for r in review_meta['candidates']}, '審核 ticker 名單與原始候選不同'
assert review.ticker.eq(review.ticker.str.strip().str.upper()).all()
excluded_rows=review.loc[review.exclude.str.strip().eq('1')].copy()
EXCLUDED=set(excluded_rows.ticker)
assert EXCLUDED, '沒有 exclude=1 的 ticker，請先人工標記'
SOURCE=Path(review_meta['source'])
source_stat=[SOURCE.stat().st_size,SOURCE.stat().st_mtime_ns]
assert source_stat==review_meta['source_size_mtime'], '03 來源已變更，應重新審核'
OUT=ROOT/'Data/process/t04_1_ticker_exclusion_diagnostics'/datetime.now(timezone.utc).strftime('%Y-%m-%d_%H-%M-%S_UTC')
OUT.mkdir(parents=True,exist_ok=False)
print('來源：',SOURCE)
print('排除 ticker 數：',len(EXCLUDED),'；未填理由數：',int(excluded_rows.reason.str.strip().eq('').sum()))
print('輸出：',OUT)

來源： C:\Users\eagle\RedditStock\Data\process\03_thread_construction\2026-09-22_03-56-59_UTC\threads.parquet
排除 ticker 數： 180 ；未填理由數： 177
輸出： C:\Users\eagle\RedditStock\Data\process\t04_1_ticker_exclusion_diagnostics\2026-09-22_10-06-32_UTC

## 1. 分批比較 thread ticker 集合
每個 thread 先去重，再移除人工指定 ticker。保留全體 before/after 數量與前 20 名完整 ticker 清單。

In [2]:
started=time.perf_counter()
before_frequency=Counter();after_frequency=Counter()
before_counts=[];after_counts=[]
top_before=[];top_after=[]
previous=None
date_min=date_max=None
def retain_top(heap, count, thread, first, tickers):
    item=(count,thread,first,tickers)
    if len(heap)<20: heapq.heappush(heap,item)
    elif item[:2]>heap[0][:2]: heapq.heapreplace(heap,item)
for batch_no,batch in enumerate(pq.ParquetFile(SOURCE).iter_batches(batch_size=5000,columns=['thread_id','first_timestamp','tickers_in_thread']),1):
    dates=[];batch_before=0;batch_after=0
    for row in batch.to_pylist():
        thread=row['thread_id']
        assert thread and (previous is None or previous<thread), '輸入需為03已排序、唯一的thread表'
        previous=thread
        before=sorted(set(row['tickers_in_thread']))
        after=[t for t in before if t not in EXCLUDED]
        before_frequency.update(before);after_frequency.update(after)
        before_counts.append(len(before));after_counts.append(len(after))
        batch_before+=len(before);batch_after+=len(after)
        first=row['first_timestamp'].isoformat() if row['first_timestamp'] is not None else None
        if first: dates.append(first)
        retain_top(top_before,len(before),thread,first,before)
        if after: retain_top(top_after,len(after),thread,first,after)
    if dates:
        date_min=min(date_min,min(dates)) if date_min else min(dates)
        date_max=max(date_max,max(dates)) if date_max else max(dates)
    print({'batch':batch_no,'row_count':batch.num_rows,'unique_threads':batch.num_rows,'unique_authors':'N/A',
           'date_min':min(dates) if dates else None,'date_max':max(dates) if dates else None,
           'mentions_before':batch_before,'mentions_after':batch_after})
before=np.asarray(before_counts,dtype=np.int64);after=np.asarray(after_counts,dtype=np.int64)
assert len(before)==pq.read_metadata(SOURCE).num_rows and len(before)>0
assert np.all(after<=before) and set(after_frequency).isdisjoint(EXCLUDED)
removed=before-after
pairs_before=before*(before-1)//2;pairs_after=after*(after-1)//2
assert int(before.sum())==sum(before_frequency.values())
assert int(after.sum())==sum(after_frequency.values())

{'batch': 1, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2012-09-17T20:19:16+00:00', 'date_max': '2015-08-11T02:19:13+00:00', 'mentions_before': 91371, 'mentions_after': 11812}
{'batch': 2, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2015-06-27T15:32:41+00:00', 'date_max': '2016-02-01T08:45:52+00:00', 'mentions_before': 90707, 'mentions_after': 12473}

{'batch': 3, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2015-11-05T13:50:23+00:00', 'date_max': '2016-07-19T19:29:06+00:00', 'mentions_before': 96517, 'mentions_after': 12833}
{'batch': 4, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2016-02-25T17:49:11+00:00', 'date_max': '2016-05-20T17:20:26+00:00', 'mentions_before': 88912, 'mentions_after': 12417}

{'batch': 5, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2016-05-09T16:51:37+00:00', 'date_max': '2017-02-11T23:37:18+00:00', 'mentions_before': 86029, 'mentions_after': 12296}
{'batch': 6, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2016-07-14T03:01:21+00:00', 'date_max': '2017-01-25T04:38:10+00:00', 'mentions_before': 80420, 'mentions_after': 12236}

{'batch': 7, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2016-08-31T14:03:00+00:00', 'date_max': '2017-02-27T15:24:47+00:00', 'mentions_before': 77181, 'mentions_after': 10301}
{'batch': 8, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2016-10-25T16:17:32+00:00', 'date_max': '2016-12-17T03:09:28+00:00', 'mentions_before': 71241, 'mentions_after': 10025}

{'batch': 9, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2016-12-14T18:11:21+00:00', 'date_max': '2017-03-27T17:47:00+00:00', 'mentions_before': 82162, 'mentions_after': 11652}
{'batch': 10, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2017-02-09T22:06:37+00:00', 'date_max': '2017-04-15T17:48:36+00:00', 'mentions_before': 96144, 'mentions_after': 13535}

{'batch': 11, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2017-04-03T00:08:17+00:00', 'date_max': '2017-09-03T07:49:06+00:00', 'mentions_before': 90463, 'mentions_after': 12749}
{'batch': 12, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2017-06-02T04:46:33+00:00', 'date_max': '2017-08-04T18:53:37+00:00', 'mentions_before': 92037, 'mentions_after': 12926}

{'batch': 13, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2017-07-24T19:16:07+00:00', 'date_max': '2017-09-15T17:07:47+00:00', 'mentions_before': 84813, 'mentions_after': 12441}
{'batch': 14, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2017-09-15T14:50:24+00:00', 'date_max': '2017-12-23T23:47:04+00:00', 'mentions_before': 82626, 'mentions_after': 12542}

{'batch': 15, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2017-11-02T14:55:04+00:00', 'date_max': '2018-05-18T18:24:59+00:00', 'mentions_before': 82366, 'mentions_after': 11778}
{'batch': 16, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2017-12-28T21:13:07+00:00', 'date_max': '2018-03-16T01:17:42+00:00', 'mentions_before': 77364, 'mentions_after': 11452}

{'batch': 17, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-02-06T18:10:55+00:00', 'date_max': '2018-03-31T20:53:04+00:00', 'mentions_before': 75561, 'mentions_after': 10529}
{'batch': 18, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-03-12T13:46:24+00:00', 'date_max': '2020-06-12T02:11:10+00:00', 'mentions_before': 83364, 'mentions_after': 11521}

{'batch': 19, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-04-15T02:50:22+00:00', 'date_max': '2018-05-18T19:23:24+00:00', 'mentions_before': 86074, 'mentions_after': 13053}
{'batch': 20, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-05-18T03:44:23+00:00', 'date_max': '2018-10-12T20:43:15+00:00', 'mentions_before': 82881, 'mentions_after': 11921}

{'batch': 21, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-06-14T22:53:35+00:00', 'date_max': '2018-08-13T14:44:36+00:00', 'mentions_before': 79410, 'mentions_after': 10976}
{'batch': 22, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-07-07T14:52:06+00:00', 'date_max': '2018-09-18T05:51:48+00:00', 'mentions_before': 85163, 'mentions_after': 12870}

{'batch': 23, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-07-31T02:47:32+00:00', 'date_max': '2018-10-03T12:22:36+00:00', 'mentions_before': 80976, 'mentions_after': 11874}
{'batch': 24, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-08-20T02:55:15+00:00', 'date_max': '2018-12-20T18:23:04+00:00', 'mentions_before': 81565, 'mentions_after': 13376}

{'batch': 25, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-09-09T13:16:44+00:00', 'date_max': '2018-10-03T22:46:36+00:00', 'mentions_before': 80872, 'mentions_after': 13414}
{'batch': 26, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-09-28T15:36:32+00:00', 'date_max': '2018-12-13T23:38:52+00:00', 'mentions_before': 79430, 'mentions_after': 13369}

{'batch': 27, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-10-18T15:42:53+00:00', 'date_max': '2019-04-11T18:41:01+00:00', 'mentions_before': 87232, 'mentions_after': 15634}

{'batch': 28, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-11-14T14:49:52+00:00', 'date_max': '2018-12-19T21:34:23+00:00', 'mentions_before': 97668, 'mentions_after': 18128}

{'batch': 29, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2018-12-19T20:30:10+00:00', 'date_max': '2019-01-23T00:49:38+00:00', 'mentions_before': 95940, 'mentions_after': 17626}

{'batch': 30, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2019-01-22T22:20:00+00:00', 'date_max': '2019-04-16T04:09:27+00:00', 'mentions_before': 111063, 'mentions_after': 25052}

{'batch': 31, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2019-03-08T01:43:29+00:00', 'date_max': '2019-05-03T23:11:26+00:00', 'mentions_before': 109273, 'mentions_after': 23961}

{'batch': 32, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2019-04-18T17:51:34+00:00', 'date_max': '2019-08-06T03:04:39+00:00', 'mentions_before': 97195, 'mentions_after': 20552}

{'batch': 33, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2019-05-20T00:49:46+00:00', 'date_max': '2019-09-28T03:25:50+00:00', 'mentions_before': 143389, 'mentions_after': 34115}

{'batch': 34, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2019-07-16T16:03:17+00:00', 'date_max': '2019-10-25T01:08:03+00:00', 'mentions_before': 128408, 'mentions_after': 28834}

{'batch': 35, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2019-08-23T20:00:50+00:00', 'date_max': '2020-01-10T21:32:29+00:00', 'mentions_before': 156189, 'mentions_after': 36067}

{'batch': 36, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2019-10-18T09:32:02+00:00', 'date_max': '2020-04-22T07:37:46+00:00', 'mentions_before': 153997, 'mentions_after': 35765}

{'batch': 37, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2019-12-04T20:37:27+00:00', 'date_max': '2020-07-03T23:39:21+00:00', 'mentions_before': 145731, 'mentions_after': 33835}

{'batch': 38, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-01-20T05:24:31+00:00', 'date_max': '2020-06-16T16:12:54+00:00', 'mentions_before': 124030, 'mentions_after': 28395}

{'batch': 39, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-02-12T18:18:07+00:00', 'date_max': '2020-07-05T21:01:56+00:00', 'mentions_before': 121273, 'mentions_after': 26925}

{'batch': 40, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-02-29T13:28:46+00:00', 'date_max': '2020-07-13T02:59:15+00:00', 'mentions_before': 124982, 'mentions_after': 24272}

{'batch': 41, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-03-13T05:03:21+00:00', 'date_max': '2020-07-16T05:19:48+00:00', 'mentions_before': 106782, 'mentions_after': 18206}

{'batch': 42, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-03-21T01:22:03+00:00', 'date_max': '2020-08-06T00:42:01+00:00', 'mentions_before': 145393, 'mentions_after': 27265}

{'batch': 43, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-04-05T01:55:11+00:00', 'date_max': '2020-07-24T01:21:29+00:00', 'mentions_before': 138614, 'mentions_after': 27829}
{'batch': 44, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-04-20T19:46:40+00:00', 'date_max': '2020-07-13T12:59:08+00:00', 'mentions_before': 91435, 'mentions_after': 18429}

{'batch': 45, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-04-29T00:51:24+00:00', 'date_max': '2020-06-15T02:20:16+00:00', 'mentions_before': 88601, 'mentions_after': 17777}

{'batch': 46, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-05-07T20:43:38+00:00', 'date_max': '2020-05-22T19:33:21+00:00', 'mentions_before': 94229, 'mentions_after': 19812}

{'batch': 47, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-05-18T15:47:23+00:00', 'date_max': '2020-05-30T22:41:35+00:00', 'mentions_before': 89658, 'mentions_after': 19026}

{'batch': 48, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-05-28T17:38:54+00:00', 'date_max': '2020-08-01T01:41:29+00:00', 'mentions_before': 99944, 'mentions_after': 24773}

{'batch': 49, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-06-11T23:00:44+00:00', 'date_max': '2020-07-12T18:52:02+00:00', 'mentions_before': 103997, 'mentions_after': 22725}

{'batch': 50, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-06-25T04:43:49+00:00', 'date_max': '2020-07-12T21:17:37+00:00', 'mentions_before': 114143, 'mentions_after': 27014}

{'batch': 51, 'row_count': 5000, 'unique_threads': 5000, 'unique_authors': 'N/A', 'date_min': '2020-07-12T05:37:57+00:00', 'date_max': '2020-07-31T02:35:33+00:00', 'mentions_before': 115406, 'mentions_after': 28077}
{'batch': 52, 'row_count': 3609, 'unique_threads': 3609, 'unique_authors': 'N/A', 'date_min': '2012-04-11T16:46:43+00:00', 'date_max': '2020-08-06T01:21:55+00:00', 'mentions_before': 76314, 'mentions_after': 16737}

## 2. Before / after 比較與污染影響
分布包含零 ticker thread；另列有效 threads 的分布。所有 ratio 為 0～1，delta 為 after 減 before。

In [3]:
def distribution(values):
    if not len(values): return dict.fromkeys(['min','max','mean','median','P75','P90','P95','P99'])
    return {'min':int(values.min()),'max':int(values.max()),'mean':float(values.mean()),
            'median':float(np.median(values)),**{f'P{p}':float(np.percentile(values,p,method='linear')) for p in [75,90,95,99]}}
def thread_metrics(values):
    result={'population_threads':len(values),'valid_threads':int((values>0).sum()),
            **{'tickers_'+k:v for k,v in distribution(values).items()},
            **{'valid_threads_tickers_'+k:v for k,v in distribution(values[values>0]).items()}}
    for name,mask in [('zero',values==0),('one',values==1),('ge2',values>=2),('ge5',values>=5),('ge10',values>=10),('ge20',values>=20)]:
        result[name+'_threads']=int(mask.sum());result[name+'_ratio']=float(mask.mean()) if len(values) else None
    return result
left={'unique_tickers':len(before_frequency),'ticker_mentions':int(before.sum()),**thread_metrics(before),
      'potential_pairs_total':int(pairs_before.sum()),**{'potential_pairs_'+k:v for k,v in distribution(pairs_before).items()}}
after_valid=after[after>=1]
pairs_after_valid=pairs_after[after>=1]
right={'unique_tickers':len(after_frequency),'ticker_mentions':int(after.sum()),**thread_metrics(after_valid),
       'potential_pairs_total':int(pairs_after.sum()),**{'potential_pairs_'+k:v for k,v in distribution(pairs_after_valid).items()}}
summary=pd.DataFrame([{'metric':k,'before':left[k],'after':right[k],
                       'delta':right[k]-left[k] if left[k] is not None and right[k] is not None else None} for k in left])
removed_mentions=sum(before_frequency[t] for t in EXCLUDED)
assert removed_mentions==int(removed.sum())
impact={'flagged_tickers':len(EXCLUDED),'excluded_tickers_present':len(EXCLUDED & set(before_frequency)),
        'excluded_tickers_absent':sorted(EXCLUDED-set(before_frequency)),
        'removed_mentions':removed_mentions,
        'removed_mention_ratio':removed_mentions/int(before.sum()) if before.sum() else None,
        'mentions_change_ratio':(int(after.sum())-int(before.sum()))/int(before.sum()) if before.sum() else None,
        'threads_became_zero':int(((before>0)&(after==0)).sum()),
        'threads_ge2_became_lt2':int(((before>=2)&(after<2)).sum()),
        'removed_tickers_per_thread':distribution(removed),
        'impact_population_threads':len(before),
        'zero_ticker_threads_before':int((before==0).sum()),
        'zero_ticker_threads_after':int((after==0).sum()),
        'potential_pairs_reduction_ratio':1-int(pairs_after.sum())/int(pairs_before.sum()) if pairs_before.sum() else None}
with pd.option_context('display.max_rows',None): display(summary)
display(pd.DataFrame([impact]))

assert right["population_threads"]==int((after>=1).sum())
assert right["one_threads"]+right["ge2_threads"]==right["population_threads"]
assert int(pairs_after_valid.sum())==int(pairs_after.sum())

                          metric        before         after         delta
0                 unique_tickers  5.682000e+03  5.502000e+03 -1.800000e+02
1                ticker_mentions  5.146535e+06  9.532020e+05 -4.193333e+06
2             population_threads  2.586090e+05  1.600580e+05 -9.855100e+04
3                  valid_threads  2.586090e+05  1.600580e+05 -9.855100e+04
4                    tickers_min  1.000000e+00  1.000000e+00  0.000000e+00
5                    tickers_max  1.052000e+03  8.720000e+02 -1.800000e+02
6                   tickers_mean  1.990083e+01  5.955354e+00 -1.394548e+01
7                 tickers_median  1.100000e+01  2.000000e+00 -9.000000e+00
8                    tickers_P75  2.400000e+01  5.000000e+00 -1.900000e+01
9                    tickers_P90  4.300000e+01  1.000000e+01 -3.300000e+01
10                   tickers_P95  6.000000e+01  1.500000e+01 -4.500000e+01
11                   tickers_P99  1.190000e+02  4.700000e+01 -7.200000e+01
12     valid_threads_tickers_min  1.000000e+00  1.000000e+00  0.000000e+00
13     valid_threads_tickers_max  1.052000e+03  8.720000e+02 -1.800000e+02
14    valid_threads_tickers_mean  1.990083e+01  5.955354e+00 -1.394548e+01
15  valid_threads_tickers_median  1.100000e+01  2.000000e+00 -9.000000e+00
16     valid_threads_tickers_P75  2.400000e+01  5.000000e+00 -1.900000e+01
17     valid_threads_tickers_P90  4.300000e+01  1.000000e+01 -3.300000e+01
18     valid_threads_tickers_P95  6.000000e+01  1.500000e+01 -4.500000e+01
19     valid_threads_tickers_P99  1.190000e+02  4.700000e+01 -7.200000e+01
20                  zero_threads  0.000000e+00  0.000000e+00  0.000000e+00
21                    zero_ratio  0.000000e+00  0.000000e+00  0.000000e+00
22                   one_threads  1.537300e+04  5.277200e+04  3.739900e+04
23                     one_ratio  5.944495e-02  3.297055e-01  2.702605e-01
24                   ge2_threads  2.432360e+05  1.072860e+05 -1.359500e+05
25                     ge2_ratio  9.405550e-01  6.702945e-01 -2.702605e-01
26                   ge5_threads  1.969330e+05  4.281700e+04 -1.541160e+05
27                     ge5_ratio  7.615087e-01  2.675093e-01 -4.939994e-01
28                  ge10_threads  1.421520e+05  1.603000e+04 -1.261220e+05
29                    ge10_ratio  5.496792e-01  1.001512e-01 -4.495281e-01
30                  ge20_threads  8.194200e+04  5.376000e+03 -7.656600e+04
31                    ge20_ratio  3.168567e-01  3.358782e-02 -2.832689e-01
32         potential_pairs_total  2.072108e+08  5.052247e+07 -1.566883e+08
33           potential_pairs_min  0.000000e+00  0.000000e+00  0.000000e+00
34           potential_pairs_max  5.528260e+05  3.797560e+05 -1.730700e+05
35          potential_pairs_mean  8.012513e+02  3.156510e+02 -4.856003e+02
36        potential_pairs_median  5.500000e+01  1.000000e+00 -5.400000e+01
37           potential_pairs_P75  2.760000e+02  1.000000e+01 -2.660000e+02
38           potential_pairs_P90  9.030000e+02  4.500000e+01 -8.580000e+02
39           potential_pairs_P95  1.770000e+03  1.050000e+02 -1.665000e+03
40           potential_pairs_P99  7.021000e+03  1.081000e+03 -5.940000e+03

,flagged_tickers,excluded_tickers_present,excluded_tickers_absent,removed_mentions,removed_mention_ratio,mentions_change_ratio,threads_became_zero,threads_ge2_became_lt2,removed_tickers_per_thread,impact_population_threads,zero_ticker_threads_before,zero_ticker_threads_after,potential_pairs_reduction_ratio
0,180,180,[],4193333,0.814788,-0.814788,98551,135950,"{'min': 0, 'max': 180, 'mean': 16.214953849247...",258609,0,98551,0.756178

## 3. 排除清單、前 50 名 ticker 與前 20 個 threads
兩個版本各自重新排名；thread 清單中附完整 ticker list，方便觀察大型 thread 是否仍集中大量 ticker。

In [4]:
def top_tickers(counter):
    return [{'rank':i,'ticker':t,'mention_frequency':count} for i,(t,count) in enumerate(sorted(counter.items(),key=lambda item:(-item[1],item[0]))[:50],1)]
def top_threads(heap):
    return [{'rank':i,'thread_id':t,'first_timestamp_utc':first,'unique_tickers':count,
             'potential_pairs':count*(count-1)//2,'tickers':tickers}
            for i,(count,t,first,tickers) in enumerate(sorted(heap,reverse=True),1)]
excluded_report=[{'ticker':row.ticker,'mention_frequency_before':before_frequency[row.ticker],'reason':row.reason}
                 for row in excluded_rows.sort_values('ticker').itertuples(index=False)]
rankings={'top50_tickers_before':top_tickers(before_frequency),'top50_tickers_after':top_tickers(after_frequency),
          'top20_threads_before':top_threads(top_before),'top20_threads_after':top_threads(top_after)}
print('被排除 ticker：')
with pd.option_context('display.max_rows',None): display(pd.DataFrame(excluded_report))
for label,records in rankings.items():
    print(label)
    with pd.option_context('display.max_rows',50,'display.max_colwidth',None): display(pd.DataFrame(records))
assert SOURCE.stat().st_size==source_stat[0] and SOURCE.stat().st_mtime_ns==source_stat[1]
assert REVIEW_FILE.read_bytes()==review_bytes
summary.to_csv(OUT/'before_after_summary.csv',index=False,encoding='utf-8-sig')
report={'status':'complete','source':str(SOURCE),'source_size_mtime':source_stat,'review_file':str(REVIEW_FILE),
        'review_sha256':hashlib.sha256(review_bytes).hexdigest(),'review_trailing_empty_fields_ignored_at_records':trailing_empty_repairs,
        'mention_definition':'one unique ticker per thread','ratio_denominator':{'before':'all original threads','after':'threads with at least one ticker after exclusion','impact':'all original threads; reduction ratios use before totals'},
        'date_min':date_min,'date_max':date_max,'unique_authors':None,
        'before':left,'after':right,'impact':impact,'excluded_tickers':excluded_report,**rankings,
        'processing_seconds':time.perf_counter()-started,'pairs_materialized':False}
(OUT/'diagnostic_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print('完成：',OUT)

被排除 ticker：

    ticker  mention_frequency_before     reason
0      ACT                      6718
1      AGE                      7267
2      AGO                     35426
3      AIR                      5295
4      ALL                    120858
5     ALOT                      4361
6      ANY                     87992
7      APP                     12496
8      ARE                    142391
9      ATH                      6165
10    AUTO                      4451
11     AVG                      4285
12    BABY                     11991
13    BASE                      6492
14    BEAR                     17128
15    BEAT                     16258
16    BEER                      5402
17     BID                      5295
18     BIG                     54272
19    BILL                      7328
20     BIT                     28634
21    BODY                      4592
22    BOOM                      4611
23     BOX                      6364
24     BRO                     26588
25    CALL                     51731
26     CAP                     10982
27     CAR                     11071
28    CARE                     18196
29    CARS                      7302
30    CASH                     33218
31     CAT                      4988
32   CHINA                     18776
33    CLUB                      4263
34    COLD                      4185
35    COOL                     15887
36    COST                     21540
37     CRY                      4658
38     CUZ                      8828
39    DATA                     15340
40    DEEP                     14121
41    DOOR                      4212
42     DOW                      5801  dow-jones
43    DRUG                      6372
44    EASY                     20298
45     EAT                     12861
46    EDIT                     24456
47    ELSE                     28407
48     EOD                      5767
49    EVER                     34879
50     EXP                      5872
51     EYE                      5900
52    EYES                      5524
53    FACT                     19073
54     FAM                      6772
55    FAST                     12751
56     FAT                      8083
57     FIT                      6044
58    FIVE                      5065
59     FIX                      5748
60    FLOW                      5511
61     FOR                    176048
62    FORM                      6884
63    FOUR                      4591
64    FREE                     31301
65    FULL                     22772
66     FUN                     17355
67    FUND                     12783
68    GAIN                     20328
69   GAINZ                      8374
70    GAME                     17804
71    GLAD                     11971
72    GOLD                     16619
73    GOOD                     95276
74    GRAB                      5103
75    GROW                      8487
76     HAS                    100678
77    HEAR                     14039
78     HES                     24828
79    HOME                     15985
80    HOOD                      4183
81    HOPE                     36383
82    HOUR                     11946
83    HUGE                     25000
84    INFO                     12105
85    IRON                      5304
86    JACK                      4628
87     JAN                     10379
88     JOB                     20886
89     KEY                      6050
90    KIDS                     11019
91    KIND                     23773
92    LAND                      5374
93     LAW                      5820
94    LAZY                      4927
95     LEG                      4724
96    LINK                     16462
97    LIVE                     19112
98    LMAO                     26642
99    LOAN                      7811
100   LOVE                     30112
101    LOW                     36242
102   MAIN                      7576
103    MAN                     46624
104    MAX                      9714
105   MEET                      5984
106    MEN                      4585
107    MIN                      4276
108   MIND                     16712
109    MOD                      6651
110   MORE                    110962
111   MOVE                     32284
112    NET                     11015
113    NEW                     48811
114   NEXT                     58621
115    NOW                    101664
116   ONCE                     31416
117    ONE                     93341
118   ONES                     16722
119   ONTO                      7458
120   OPEN                     34877
121    OUT                    114703
122   OVER                     65851
123    PAY                     31703
124   PAYS                      5540
125   PEAK                      8458
126    PER                     19968
127   PLAN                     17908
128   PLAY                     42316
129   POST                     86393
130    PRE                      5848
131    PRO                      4676
132   PUMP                     16171
133   RIDE                     17065
134   ROAD                      4557
135   ROCK                      4848
136    RUN                     29902
137   SAFE                     12977
138   SAVE                     13251
139    SEE                     80206
140   SELF                      7896
141   SHIP                      6117
142   SHOP                      6113
143   SICK                      7653
144   SIDE                     17827
145   SITE                      6125
146    SIX                      4393
147   SNAP                      8969
148   SOLD                     45248
149    SON                      8965
150   SPOT                      6772
151    SPY                     33291        ETF
152   STAY                     19417
153   STEP                      7951
154   TALK                     15882
155   TEAM                      6671
156   TECH                     16420
157   TELL                     35606
158    TEN                      4531
159   TEST                      7552
160    THO                     20441     though
161    TIL                      8233
162   TIME                     88103
163    TIP                      5547
164   TONS                      6483
165   TOWN                      4168
166   TRUE                     28778
167    TWO                     38126
168   TYPE                     12146
169    USA                      5722
170   USER                      6906
171   VERY                     45546
172    VIA                      6431
173   VIEW                      6009
174   WELL                     73277
175   WINS                      6129
176   WISH                     18061
177   WORK                     40752
178    WOW                     17507
179    YOU                    202685

top50_tickers_before

    rank ticker  mention_frequency
0      1    YOU             202685
1      2    FOR             176048
2      3    ARE             142391
3      4    ALL             120858
4      5    OUT             114703
5      6   MORE             110962
6      7    NOW             101664
7      8    HAS             100678
8      9   GOOD              95276
9     10    ONE              93341
10    11   TIME              88103
11    12    ANY              87992
12    13   POST              86393
13    14    SEE              80206
14    15   WELL              73277
15    16   OVER              65851
16    17   NEXT              58621
17    18    BIG              54272
18    19   CALL              51731
19    20    NEW              48811
20    21    MAN              46624
21    22   VERY              45546
22    23   SOLD              45248
23    24   PLAY              42316
24    25   WORK              40752
25    26    TWO              38126
26    27   HOPE              36383
27    28    LOW              36242
28    29   TELL              35606
29    30    AGO              35426
30    31   EVER              34879
31    32   OPEN              34877
32    33    SPY              33291
33    34   CASH              33218
34    35   MOVE              32284
35    36    PAY              31703
36    37   ONCE              31416
37    38   FREE              31301
38    39   LOVE              30112
39    40    RUN              29902
40    41   TRUE              28778
41    42    BIT              28634
42    43   ELSE              28407
43    44   LMAO              26642
44    45    BRO              26588
45    46   HUGE              25000
46    47    HES              24828
47    48   EDIT              24456
48    49   KIND              23773
49    50   FULL              22772

top50_tickers_after

    rank ticker  mention_frequency
0      1    AMD              19996
1      2   TSLA              17018
2      3    AMP              14560
3      4    IMO              12969
4      5   AAPL              11325
5      6    FDS              11216
6      7   AMZN              10388
7      8   MSFT               9457
8      9   ELON               9184
9     10   NVDA               8697
10    11    DIS               6136
11    12    QQQ               5931
12    13   NFLX               5409
13    14   BABA               5259
14    15    PPL               5184
15    16    BOI               4677
16    17    AIN               4614
17    18   FORD               4352
18    19   COKE               4273
19    20   UBER               4222
20    21   CORE               4112
21    22    BAC               4108
22    23    PIC               3860
23    24    GDP               3840
24    25   COIN               3832
25    26   SPCE               3713
26    27    SKY               3702
27    28    MET               3688
28    29   CHIP               3670
29    30   RARE               3570
30    31   CENT               3556
31    32   RACE               3532
32    33    USO               3528
33    34   HIRE               3522
34    35   CALM               3497
35    36    UPS               3494
36    37    NOV               3483
37    38    ADS               3459
38    39   TRIP               3428
39    40   LAWS               3326
40    41   TQQQ               3288
41    42   ATVI               3274
42    43    GUT               3260
43    44   EPIC               3243
44    45    PDT               3200
45    46   WAGE               3143
46    47   FILE               3132
47    48   ALLY               3123
48    49   EAST               3123
49    50   DARE               3080

top20_threads_before

,rank,thread_id,first_timestamp_utc,unique_tickers,potential_pairs,tickers
0,1,gxbzbj,2020-06-05T20:07:29+00:00,1052,552826,"[AAL, AAPL, AAXN, ABB, ABBV, ABC, ABT, ACB, ACRE, ACT, ADBE, ADS, ADSK, ADT, AEG, AER, AERI, AGE, AGNC, AGO, AHH, AIG, AIM, AIN, AIR, ALE, ALEX, ALGN, ALGT, ALK, ALL, ALLY, ALOT, ALT, ALTA, AMAT, AMC, AMD, AMG, AMGN, AMID, AMN, AMP, AMZN, ANY, AOBC, APA, APEX, APHA, APP, APPN, APPS, APR, APT, APY, AQST, AQUA, ARCH, ARE, ASH, ATEC, ATH, ATVI, ATX, AUD, AUG, AURA, AUS, AUTO, AUY, AVG, AWH, AXE, AXP, AZZ, BABA, BABY, BAC, BAH, BAM, BAND, BARE, BARK, BAS, BASE, BBBY, BBQ, BBVA, BBW, BBY, BDAY, BEAM, BEAR, BEAT, BEER, BEN, BENE, BFB, BFS, BGG, ...]"
1,2,hgeyf9,2020-06-26T20:07:36+00:00,951,451725,"[AAL, AAPL, ABBV, ABC, ABT, ACB, ACC, ACH, ACI, ACT, ADBE, ADM, ADS, ADV, AGE, AGO, AGS, AHH, AHPI, AHS, AIG, AIM, AIN, AIR, AKAM, AKS, ALE, ALEX, ALK, ALL, ALLY, ALOT, ALT, ALTO, AMC, AMD, AMG, AMID, AMP, AMT, AMZN, ANDS, ANET, ANY, APDN, APEX, APHA, APP, APPS, APR, APT, ARC, ARDS, ARE, ASRT, ATH, ATHX, ATVI, AUD, AUG, AUS, AUTO, AUY, AVG, AVID, AWH, AXE, AXO, AXP, BABA, BABY, BAC, BAH, BAM, BANC, BAND, BARE, BAS, BASE, BBBY, BBCP, BBG, BBQ, BBW, BBY, BDAY, BEAM, BEAR, BEAT, BEER, BEN, BFS, BID, BIG, BILL, BIO, BIRD, BIT, BITE, BLK, ...]"
2,3,h7s30c,2020-06-12T20:07:30+00:00,930,431985,"[AAL, AAPL, AAXN, ABBV, ABC, ABT, ACB, ACC, ACH, ACRE, ACT, ACTT, ADBE, ADS, AFG, AFIB, AGE, AGO, AHH, AIG, AIKI, AIM, AIN, AIR, ALEX, ALK, ALL, ALLY, ALOT, ALT, AMC, AMD, AMG, AMID, AMP, AMZN, ANDS, ANY, APC, APEX, APHA, APM, APP, APPS, APT, AQUA, ARC, ARCH, ARE, ARKR, ARMK, ARW, ASH, ASPN, ATA, ATH, ATVI, AUD, AUG, AURA, AUS, AUTO, AVCT, AVG, AVID, AXE, AXON, AXP, AZEK, BABA, BABY, BAC, BAH, BAM, BAND, BAP, BARE, BARK, BASE, BBG, BBL, BBQ, BBW, BBY, BDAY, BDC, BEAM, BEAR, BEAT, BEER, BEN, BFS, BHP, BID, BIG, BILL, BIO, BIOX, BIRD, BIT, ...]"
3,4,gt08v2,2020-05-29T20:07:15+00:00,921,423660,"[AAL, AAPL, AAXN, ABBV, ABC, ABT, ACAT, ACB, ACC, ACER, ACH, ACT, ADBE, ADI, ADS, ADSK, AEO, AEP, AES, AGE, AGEN, AGO, AHH, AIG, AIM, AIN, AIR, AJRD, ALE, ALEX, ALK, ALL, ALLY, ALOT, ALT, AMC, AMD, AMG, AMID, AMP, AMZN, ANY, AOBC, APAC, APEX, APHA, APO, APOG, APP, APPS, APT, ARC, ARCH, ARE, AREX, ARI, ARLO, ARWR, ARYA, ASH, ATH, ATVI, AUG, AURA, AUTO, AUY, AVEO, AVG, AVGO, AXON, AXP, AYTU, AZZ, BABA, BABY, BAC, BAH, BAM, BAND, BARE, BARK, BAS, BASE, BBQ, BBY, BDAY, BEAM, BEAR, BEAT, BEEM, BEER, BEN, BFB, BFS, BGG, BID, BIG, BILL, BIO, BIRD, ...]"
4,5,how5ir,2020-07-10T20:07:32+00:00,907,410871,"[AAL, AAPL, ABBV, ABT, ACAT, ACC, ACH, ACLS, ACRE, ACT, ADS, ADT, AGE, AGO, AHH, AIM, AIN, AIR, ALE, ALEX, ALL, ALLY, ALOT, ALT, AMC, AMCS, AMD, AMG, AMID, AMP, AMT, AMZN, ANGO, ANY, APA, APEX, APHA, APP, APPS, APPX, APR, APRN, APT, APY, ARA, ARC, ARCE, ARCH, ARDX, ARE, ARMK, ARYA, ASA, ATH, ATVI, AUG, AUS, AUTO, AUY, AVG, AVID, AVXL, AWH, AXE, AXP, AXU, AZZ, BABA, BABY, BAC, BAH, BAM, BAND, BARE, BARK, BASE, BBBY, BBQ, BBW, BBY, BCRX, BDAY, BDN, BEAM, BEAR, BEAT, BEER, BEN, BFS, BGG, BID, BIER, BIG, BILL, BIO, BIOS, BIRD, BIT, BITE, BKK, ...]"
5,6,hc7rvq,2020-06-19T20:07:30+00:00,906,409965,"[AAL, AAPL, ABC, ABT, ACB, ACC, ACER, ACRE, ACT, ACTT, ADBE, ADNT, ADS, AFL, AGE, AGO, AGS, AHH, AIM, AIN, AIR, ALE, ALEX, ALF, ALL, ALLT, ALLY, ALOT, ALT, AMAT, AMC, AMD, AMED, AMID, AMN, AMP, AMS, AMZN, ANF, ANY, APEX, APHA, APP, APPS, APT, APTV, ARC, ARCH, ARE, ARMK, ASA, ASH, ATA, ATH, ATR, ATVI, AUG, AUTO, AVA, AVG, AWK, AXE, AXP, AYX, AZZ, BABA, BABY, BAC, BAH, BAM, BAND, BARE, BARK, BAS, BASE, BBD, BBG, BBQ, BBW, BBY, BDAY, BEAM, BEAR, BEAT, BEER, BEN, BID, BIG, BILI, BILL, BIO, BIOS, BIP, BIRD, BIT, BITE, BLOG, BLVD, BMO, BMY, ...]"
6,7,ht2v2k,2020-07-17T20:07:40+00:00,897,401856,"[AAL, AAME, AAP, AAPL, ABBV, ABT, ACB, ACC, ACHV, ACI, ACRE, ACT, ADBE, ADS, ADT, AEO, AFMD, AGE, AGO, AGRX, AHH, AIG, AIM, AIMT, AIN, AIR, AIRS, AKAM, ALC, ALE, ALEX, ALL, ALLY, ALOT, ALT, AMC, AMD, AMID, AMP, AMT, AMZN, ANDA, ANGI, ANY, APEX, APHA, APP, APPS, APR, APRN, APT, APY, ARC, ARDS, ARE, ARKR, ASA, ATC, ATH, ATHX, ATOM, ATR, ATVI, AUG, AUTO, AUY, AVG, AVID, AVTR, AWK, AXON, AXP, AXSM, AYTU, AZZ, BABA, BABY, BAC, BAH, BAM, BAND, BARE, BARK, BASE, BBBY, BBG, BCC, BDAY, BEAM, BEAR, BEAT, BEER, BEN, BID, BIG, BILL, BIO, BIOS, BIRD, BIT, ...]"
7,8,goqr4v,2020-05-22T20:07:33+00:00,895,400065,"[AAL, AAPL, ABC, ABT, ACA, ACB, ACC, ACER, ACP, ACT, ADBE, ADPT, ADS, ADSK, ADVM, AEM, AGE, AGI, AGO, AHH, AIM, AIN, AIR, AIT, AJRD, ALB, ALC, ALEX, ALGN, ALK, ALL, ALLY, ALOT, ALT, AMAT, AMC, AMD, AME, AMGN, AMID, AMP, AMPS, AMT, AMZN, ANY, AOBC, APHA, APP, APPS, APR, APT, AQUA, ARDS, ARE, ASA, ATH, ATR, ATVI, AUG, AUS, AUTO, AUY, AVG, AVID, AXE, AXP, AYTU, AZO, BABA, BABY, BAC, BAM, BAND, BARE, BARK, BASE, BBBY, BBQ, BBY, BDAY, BDR, BEAM, BEAR, BEAT, BEER, BFS, BHP, BID, BIG, BILI, BILL, BIO, BIRD, BIT, BITE, BKNG, BLOG, BME, BMI, BODY, ...]"
8,9,i1ejxp,2020-07-31T20:07:53+00:00,894,399171,"[AAL, AAMC, AAPL, AAWW, ABC, ABT, ACB, ACC, ACT, ACTI, ADC, ADMA, ADS, ADT, ADV, AEM, AGE, AGO, AHH, AIG, AIM, AIN, AIR, AKER, ALC, ALE, ALEX, ALF, ALK, ALL, ALLY, ALOT, ALT, ALXN, AMC, AMCR, AMD, AMID, AMP, AMZN, ANDA, ANY, APEX, APHA, APP, APPS, APR, APRN, APT, ARCH, ARE, ASH, ATH, ATHX, ATNM, ATVI, ATX, AUG, AURA, AUTO, AUY, AVD, AVG, AXP, AYX, AZZ, BABA, BABY, BAC, BAH, BAM, BAND, BARE, BAS, BASE, BAX, BBCP, BBL, BBQ, BBY, BDN, BDX, BEAR, BEAT, BEER, BFS, BHAT, BID, BIG, BIGC, BILL, BIO, BIOS, BIRD, BIT, BITE, BLDP, BLNK, BLOG, BMI, ...]"
9,10,gkggr4,2020-05-15T20:07:22+00:00,888,393828,"[AAL, AAPL, ABC, ABT, ACB, ACRE, ACT, ACTT, ADBE, ADP, ADPT, ADS, ADX, AGE, AGG, AGO, AHH, AIM, AIN, AIR, AIRS, ALE, ALEX, ALGN, ALK, ALL, ALLY, ALOT, ALT, ALTA, ALTO, AMAT, AMC, AMD, AMID, AMP, AMZN, ANDS, ANY, AOBC, APDN, APHA, APP, APPF, APPN, APPS, APR, APT, APY, ARC, ARCH, ARD, ARE, ARWR, ASM, ATH, ATVI, AUG, AUS, AUTO, AUY, AVG, AVID, AWH, AXE, AXP, AYX, AZZ, BABA, BABY, BAC, BAM, BAND, BARE, BARK, BAS, BASE, BBBY, BBQ, BBY, BDAY, BEAR, BEAT, BEER, BEN, BFS, BID, BIG, BIIB, BILI, BILL, BIO, BIRD, BIT, BITE, BKNG, BLOG, BLVD, BMI, BODY, ...]"
10,11,gg0k2r,2020-05-08T20:08:25+00:00,887,392941,"[AAL, AAN, AAP, AAPL, ABB, ABBV, ABC, ABT, ACB, ACC, ACH, ACRE, ACT, ADBE, ADS, ADSK, AGC, AGE, AGO, AHH, AIM, AIMT, AIN, AIR, AJRD, ALE, ALEX, ALGS, ALK, ALL, ALLY, ALNA, ALOT, ALT, ALTO, AMAT, AMC, AMD, AMG, AMID, AMP, AMPS, AMRX, AMZN, ANY, AOBC, APD, APEX, APHA, APM, APP, APPN, APPS, APR, APT, APY, AQN, ARC, ARCH, ARE, ARMK, ARWR, ASA, ASH, ATH, ATVI, AUG, AUPH, AUS, AUTO, AVG, AVID, AVYA, AXE, AXON, AXP, AYTU, AYX, BABA, BABY, BAC, BAM, BAND, BARE, BARK, BAS, BASE, BBBY, BBD, BBQ, BBW, BBY, BCRX, BDAY, BEAM, BEAR, BEAT, BEER, BEN, BID, ...]"
11,12,hx90gx,2020-07-24T20:07:43+00:00,858,367653,"[AAL, AAPL, AAXN, ABBV, ABC, ABT, ABUS, ACA, ACB, ACC, ACI, ACT, ADBE, ADS, ADSK, AEO, AESE, AGE, AGO, AHH, AHS, AIM, AIN, AIR, AIT, AJRD, AKAM, ALE, ALEX, ALF, ALK, ALL, ALLY, ALOT, ALT, ALXN, AMAT, AMC, AMD, AME, AMID, AMKR, AMP, AMT, AMZN, ANTM, ANY, AOBC, APA, APC, APH, APHA, APP, APPS, APR, APRN, APT, APY, ARC, ARDS, ARE, ASM, ASNA, ATH, ATNM, ATVI, AUD, AUG, AUS, AUTO, AUY, AVG, AXP, BABA, BABY, BAC, BAM, BAND, BARE, BASE, BBBY, BBQ, BBY, BCOV, BCRX, BDAY, BEAR, BEAT, BEER, BEN, BENE, BFS, BHC, BID, BIG, BILL, BIO, BIRD, BIT, BITE, ...]"
12,13,hkpyve,2020-07-03T20:08:01+00:00,840,352380,"[AAL, AAPL, ABBV, ABC, ABER, ACB, ACC, ACH, ACRE, ACT, ADP, ADS, ADX, AGE, AGN, AGO, AHH, AHT, AIM, AIN, AIR, AIRS, AKAM, ALEX, ALL, ALLY, ALOT, ALT, ALTO, AMAT, AMC, AMD, AMG, AMGN, AMID, AMP, AMZN, ANGI, ANY, APEX, APHA, APP, APPS, APR, APT, ARC, ARCH, ARDS, ARE, ARI, ARMK, ATH, ATVI, AUD, AUG, AURA, AUTO, AUY, AVG, AVID, AWH, AXDX, AXL, BABA, BABY, BAC, BAM, BAND, BARE, BASE, BBBY, BBG, BBK, BBQ, BBW, BBY, BEAM, BEAR, BEAT, BEER, BEN, BFS, BID, BIG, BILI, BILL, BIO, BIRD, BIT, BITE, BKS, BLDP, BLK, BLL, BLNK, BLOG, BODY, BOI, BOLD, BON, ...]"
13,14,gu5xww,2020-05-31T20:08:12+00:00,830,344035,"[AAL, AAPL, AAXN, ABBV, ABC, ABCO, ABT, ACA, ACB, ACC, ACH, ACRE, ACT, ADMA, ADN, ADS, ADSK, ADT, AESE, AGC, AGE, AGEN, AGM, AGO, AHH, AHS, AIG, AIM, AIN, AIR, AJRD, ALE, ALK, ALL, ALLE, ALLY, ALOT, ALT, AMBA, AMC, AMD, AMID, AMP, AMRS, AMS, AMT, AMZN, ANY, AOBC, APEX, APHA, APOG, APP, APPS, APRN, APT, APY, ARC, ARCH, ARCO, ARE, ARWR, ARYA, ASH, ATH, ATVI, AUD, AUG, AUTO, AUY, AVG, AVGO, AXE, AXON, AXP, AZZ, BABA, BABY, BAC, BAM, BAND, BARK, BASE, BBQ, BBY, BDAY, BEAR, BEAT, BEER, BEN, BFS, BGC, BID, BIG, BILL, BIO, BIRD, BIT, BITE, BKNG, ...]"
14,15,gbpcs2,2020-05-01T20:09:09+00:00,829,343206,"[AAL, AAMC, AAPL, ABBV, ABC, ABT, ACAT, ACB, ACC, ACRE, ACT, ADP, ADS, ADX, AER, AFB, AGE, AGO, AGR, AHH, AIG, AIM, AIMT, AIN, AIR, AKER, ALEC, ALEX, ALGT, ALK, ALL, ALLY, ALOT, ALSK, ALT, AMC, AMD, AME, AMG, AMID, AMP, AMZN, ANDS, ANF, ANY, AOBC, APEX, APHA, APP, APPS, APRN, APRS, APT, APY, ARCH, ARE, ARW, ATH, ATVI, AUG, AUS, AUTO, AVG, AWK, AXE, AXP, AYR, AYX, BABA, BABY, BAC, BAM, BAND, BARE, BARK, BAS, BASE, BBG, BBQ, BBY, BCH, BCRX, BDAY, BEAM, BEAR, BEAT, BEER, BEN, BFS, BID, BIG, BIIB, BILL, BIO, BIOS, BIRD, BIT, BITE, BKNG, BLK, ...]"
15,16,fi5jtz,2020-03-13T19:47:11+00:00,825,339900,"[AAL, AAN, AAPL, ABBV, ABC, ABM, ABT, ACB, ACC, ACH, ACT, ADBE, ADM, ADS, AEO, AFB, AGE, AGO, AHH, AIG, AIM, AIN, AIR, AJRD, ALEX, ALK, ALL, ALLY, ALOT, ALR, ALT, ALTA, ALTO, AMC, AMD, AMID, AMP, AMWD, AMZN, ANY, AOBC, APAC, APEX, APHA, APP, APPS, APR, APT, APU, APY, ARC, ARCH, ARDS, ARE, ARMK, ASA, ATH, ATX, AUD, AUG, AUS, AUTO, AVG, AWK, AXP, BABA, BABY, BAC, BAH, BAM, BAND, BARE, BARK, BASE, BBQ, BBY, BCC, BDAY, BEAR, BEAT, BEER, BEN, BFS, BID, BIG, BILI, BILL, BIO, BIRD, BIT, BITE, BKNG, BKS, BMI, BODY, BOE, BOH, BOI, BOLD, BOLT, ...]"
16,17,g7fkq6,2020-04-24T20:08:10+00:00,818,334153,"[AAL, AAPL, ABBV, ABC, ABT, ACB, ACC, ACT, ADBE, ADS, AEO, AGE, AGG, AGO, AHH, AHS, AIM, AIMT, AIN, AIR, AKRX, ALEX, ALK, ALL, ALLY, ALOT, AMC, AMD, AMGN, AMID, AMP, AMZN, ANY, APA, APEX, APP, APPS, APR, APU, ARC, ARCH, ARE, ARES, ARWR, ASH, ASNA, ATH, ATVI, AUG, AURA, AUS, AUTO, AUY, AVG, AVID, AXE, AXP, AYTU, BABA, BABY, BAC, BAM, BAND, BARE, BAS, BASE, BBG, BBQ, BBW, BBY, BDAY, BEAM, BEAR, BEAT, BEER, BEN, BFS, BID, BIG, BILL, BIO, BIRD, BIT, BITE, BKNG, BLOG, BLVD, BODY, BOI, BOLD, BOOM, BOOT, BOWL, BOX, BRAG, BRO, BROS, BULK, BYD, BYND, ...]"
17,18,hrorfa,2020-07-15T14:42:05+00:00,816,332520,"[AAL, AAPL, AAXN, ABB, ABT, ACB, ACC, ACER, ACHV, ACRE, ACT, ADS, AEZS, AGE, AGO, AHH, AHT, AIM, AIN, AIR, AKTS, ALDX, ALEX, ALK, ALL, ALLY, ALNA, ALOT, ALPP, ALT, AMAT, AMC, AMCX, AMD, AMP, AMPE, AMSC, AMTX, AMZN, ANDS, ANY, APHA, APO, APP, APPS, APT, ARA, ARE, ARW, ARWR, ASM, ASMB, ASNA, ATNM, ATOM, ATVI, AUG, AUS, AUTO, AVB, AVG, AVID, AWH, AXAS, AXE, AXON, AXP, AYTU, AZZ, BABA, BABY, BAC, BAH, BAND, BARK, BASE, BAX, BBQ, BBW, BCC, BEAR, BEAT, BEER, BEN, BFA, BGG, BID, BIG, BIIB, BILL, BIMI, BIO, BIP, BIT, BITE, BKI, BKNG, BKYI, BLDP, BLNK, ...]"
18,19,g39g3g,2020-04-17T20:08:08+00:00,813,330078,"[AAL, AAP, AAPL, ABBV, ABC, ABT, ACB, ACC, ACH, ACRE, ACT, ADS, AER, AGE, AGG, AGI, AGO, AGS, AHH, AIM, AIMT, AIN, AIO, AIR, AIRS, ALEX, ALL, ALLY, ALOT, ALT, ALTO, AMC, AMD, AMID, AMP, AMT, AMTD, AMZN, ANET, ANF, ANTM, ANY, APEX, APHA, APP, APPS, APR, APRN, APU, ARC, ARCH, ARE, ARW, ARWR, ATC, ATH, ATVI, AUG, AUTO, AUY, AVB, AVG, AVGO, AVID, AXP, AYTU, BABA, BABY, BAC, BAM, BAND, BAP, BARE, BASE, BBBY, BBL, BBW, BBY, BDAY, BEAR, BEAT, BEER, BEN, BID, BIG, BILI, BILL, BIO, BIRD, BIT, BITE, BLOG, BLU, BOAS, BODY, BOI, BOLD, BOOM, BOWL, BOX, ...]"
19,20,fm1mgt,2020-03-20T20:00:19+00:00,804,322806,"[AAL, AAPL, ABBV, ABC, ABT, ACB, ACC, ACER, ACH, ACRE, ACT, ADBE, ADP, ADS, AEM, AEO, AGE, AGI, AGO, AGR, AHH, AHT, AIG, AIM, AIMT, AIN, AIR, ALEX, ALL, ALLY, ALOT, ALT, ALTA, AMC, AMD, AMID, AMP, AMRX, AMZN, ANF, ANTM, ANY, AOBC, APC, APCS, APEX, APHA, APP, APPS, APR, APRN, APT, APY, ARC, ARDS, ARE, ARMK, ARW, ATA, ATC, ATH, ATVI, AUG, AUS, AUTO, AVB, AVG, AWH, AXE, AXP, AYTU, AZO, BABA, BABY, BAC, BAH, BAM, BAND, BARE, BARK, BAS, BASE, BBY, BDAY, BDX, BEAM, BEAR, BEAT, BEER, BEN, BFS, BID, BIG, BILL, BIO, BIRD, BIT, BITE, BITI, BLK, ...]"

top20_threads_after

,rank,thread_id,first_timestamp_utc,unique_tickers,potential_pairs,tickers
0,1,gxbzbj,2020-06-05T20:07:29+00:00,872,379756,"[AAL, AAPL, AAXN, ABB, ABBV, ABC, ABT, ACB, ACRE, ADBE, ADS, ADSK, ADT, AEG, AER, AERI, AGNC, AHH, AIG, AIM, AIN, ALE, ALEX, ALGN, ALGT, ALK, ALLY, ALT, ALTA, AMAT, AMC, AMD, AMG, AMGN, AMID, AMN, AMP, AMZN, AOBC, APA, APEX, APHA, APPN, APPS, APR, APT, APY, AQST, AQUA, ARCH, ASH, ATEC, ATVI, ATX, AUD, AUG, AURA, AUS, AUY, AWH, AXE, AXP, AZZ, BABA, BAC, BAH, BAM, BAND, BARE, BARK, BAS, BBBY, BBQ, BBVA, BBW, BBY, BDAY, BEAM, BEN, BENE, BFB, BFS, BGG, BIO, BIRD, BITE, BKNG, BKR, BLK, BLMN, BLOG, BLU, BMO, BOI, BOLD, BOLT, BOOT, BORR, BOWL, BRAG, ...]"
1,2,hgeyf9,2020-06-26T20:07:36+00:00,771,296835,"[AAL, AAPL, ABBV, ABC, ABT, ACB, ACC, ACH, ACI, ADBE, ADM, ADS, ADV, AGS, AHH, AHPI, AHS, AIG, AIM, AIN, AKAM, AKS, ALE, ALEX, ALK, ALLY, ALT, ALTO, AMC, AMD, AMG, AMID, AMP, AMT, AMZN, ANDS, ANET, APDN, APEX, APHA, APPS, APR, APT, ARC, ARDS, ASRT, ATHX, ATVI, AUD, AUG, AUS, AUY, AVID, AWH, AXE, AXO, AXP, BABA, BAC, BAH, BAM, BANC, BAND, BARE, BAS, BBBY, BBCP, BBG, BBQ, BBW, BBY, BDAY, BEAM, BEN, BFS, BIO, BIRD, BITE, BLK, BLMN, BLNK, BLOG, BMRG, BMY, BOI, BOLD, BOLT, BOOT, BOWL, BRAG, BREW, BRKA, BRKS, BROS, BSX, BULK, BURL, BYND, CAG, CAKE, ...]"
2,3,h7s30c,2020-06-12T20:07:30+00:00,750,280875,"[AAL, AAPL, AAXN, ABBV, ABC, ABT, ACB, ACC, ACH, ACRE, ACTT, ADBE, ADS, AFG, AFIB, AHH, AIG, AIKI, AIM, AIN, ALEX, ALK, ALLY, ALT, AMC, AMD, AMG, AMID, AMP, AMZN, ANDS, APC, APEX, APHA, APM, APPS, APT, AQUA, ARC, ARCH, ARKR, ARMK, ARW, ASH, ASPN, ATA, ATVI, AUD, AUG, AURA, AUS, AVCT, AVID, AXE, AXON, AXP, AZEK, BABA, BAC, BAH, BAM, BAND, BAP, BARE, BARK, BBG, BBL, BBQ, BBW, BBY, BDAY, BDC, BEAM, BEN, BFS, BHP, BIO, BIOX, BIRD, BITE, BLDP, BLMN, BLOG, BMI, BMO, BOAS, BOI, BOLD, BON, BOOT, BOWL, BRAG, BREW, BRKA, BROS, BSN, BULK, BYND, CAKE, CAL, ...]"
3,4,gt08v2,2020-05-29T20:07:15+00:00,741,274170,"[AAL, AAPL, AAXN, ABBV, ABC, ABT, ACAT, ACB, ACC, ACER, ACH, ADBE, ADI, ADS, ADSK, AEO, AEP, AES, AGEN, AHH, AIG, AIM, AIN, AJRD, ALE, ALEX, ALK, ALLY, ALT, AMC, AMD, AMG, AMID, AMP, AMZN, AOBC, APAC, APEX, APHA, APO, APOG, APPS, APT, ARC, ARCH, AREX, ARI, ARLO, ARWR, ARYA, ASH, ATVI, AUG, AURA, AUY, AVEO, AVGO, AXON, AXP, AYTU, AZZ, BABA, BAC, BAH, BAM, BAND, BARE, BARK, BAS, BBQ, BBY, BDAY, BEAM, BEEM, BEN, BFB, BFS, BGG, BIO, BIRD, BITE, BLE, BLK, BLOG, BLU, BMCH, BMI, BOI, BOLD, BOLT, BOOT, BOWL, BRAG, BREW, BRKA, BROS, BTI, BULK, BWC, BYD, ...]"
4,5,how5ir,2020-07-10T20:07:32+00:00,727,263901,"[AAL, AAPL, ABBV, ABT, ACAT, ACC, ACH, ACLS, ACRE, ADS, ADT, AHH, AIM, AIN, ALE, ALEX, ALLY, ALT, AMC, AMCS, AMD, AMG, AMID, AMP, AMT, AMZN, ANGO, APA, APEX, APHA, APPS, APPX, APR, APRN, APT, APY, ARA, ARC, ARCE, ARCH, ARDX, ARMK, ARYA, ASA, ATVI, AUG, AUS, AUY, AVID, AVXL, AWH, AXE, AXP, AXU, AZZ, BABA, BAC, BAH, BAM, BAND, BARE, BARK, BBBY, BBQ, BBW, BBY, BCRX, BDAY, BDN, BEAM, BEN, BFS, BGG, BIER, BIO, BIOS, BIRD, BITE, BKK, BKR, BLMN, BLNK, BLOG, BLVD, BMO, BMY, BNGO, BOI, BOLD, BOLT, BOOT, BOWL, BOXL, BRAG, BREW, BRKA, BROS, BULK, BURL, BYND, ...]"
5,6,hc7rvq,2020-06-19T20:07:30+00:00,726,263175,"[AAL, AAPL, ABC, ABT, ACB, ACC, ACER, ACRE, ACTT, ADBE, ADNT, ADS, AFL, AGS, AHH, AIM, AIN, ALE, ALEX, ALF, ALLT, ALLY, ALT, AMAT, AMC, AMD, AMED, AMID, AMN, AMP, AMS, AMZN, ANF, APEX, APHA, APPS, APT, APTV, ARC, ARCH, ARMK, ASA, ASH, ATA, ATR, ATVI, AUG, AVA, AWK, AXE, AXP, AYX, AZZ, BABA, BAC, BAH, BAM, BAND, BARE, BARK, BAS, BBD, BBG, BBQ, BBW, BBY, BDAY, BEAM, BEN, BILI, BIO, BIOS, BIP, BIRD, BITE, BLOG, BLVD, BMO, BMY, BOI, BOLD, BOLT, BON, BOOT, BOWL, BRAG, BREW, BRKA, BROS, BSX, BTU, BULK, BYFC, BYND, CAB, CAH, CAKE, CAL, CALC, CALI, ...]"
6,7,ht2v2k,2020-07-17T20:07:40+00:00,717,256686,"[AAL, AAME, AAP, AAPL, ABBV, ABT, ACB, ACC, ACHV, ACI, ACRE, ADBE, ADS, ADT, AEO, AFMD, AGRX, AHH, AIG, AIM, AIMT, AIN, AIRS, AKAM, ALC, ALE, ALEX, ALLY, ALT, AMC, AMD, AMID, AMP, AMT, AMZN, ANDA, ANGI, APEX, APHA, APPS, APR, APRN, APT, APY, ARC, ARDS, ARKR, ASA, ATC, ATHX, ATOM, ATR, ATVI, AUG, AUY, AVID, AVTR, AWK, AXON, AXP, AXSM, AYTU, AZZ, BABA, BAC, BAH, BAM, BAND, BARE, BARK, BBBY, BBG, BCC, BDAY, BEAM, BEN, BIO, BIOS, BIRD, BITE, BLDP, BLI, BLK, BLMN, BLNK, BLOG, BLU, BLVD, BMI, BMRA, BMRG, BMY, BOI, BOLD, BOLT, BOOT, BOWL, BOXL, BRAG, BREW, ...]"
7,8,goqr4v,2020-05-22T20:07:33+00:00,715,255255,"[AAL, AAPL, ABC, ABT, ACA, ACB, ACC, ACER, ACP, ADBE, ADPT, ADS, ADSK, ADVM, AEM, AGI, AHH, AIM, AIN, AIT, AJRD, ALB, ALC, ALEX, ALGN, ALK, ALLY, ALT, AMAT, AMC, AMD, AME, AMGN, AMID, AMP, AMPS, AMT, AMZN, AOBC, APHA, APPS, APR, APT, AQUA, ARDS, ASA, ATR, ATVI, AUG, AUS, AUY, AVID, AXE, AXP, AYTU, AZO, BABA, BAC, BAM, BAND, BARE, BARK, BBBY, BBQ, BBY, BDAY, BDR, BEAM, BFS, BHP, BILI, BIO, BIRD, BITE, BKNG, BLOG, BME, BMI, BOI, BOKF, BOLD, BOOT, BOWL, BRAG, BREW, BRKA, BROS, BULK, BURL, BYD, BYND, CAB, CAC, CAKE, CALA, CALC, CALI, CALM, CAM, CAMP, ...]"
8,9,i1ejxp,2020-07-31T20:07:53+00:00,714,254541,"[AAL, AAMC, AAPL, AAWW, ABC, ABT, ACB, ACC, ACTI, ADC, ADMA, ADS, ADT, ADV, AEM, AHH, AIG, AIM, AIN, AKER, ALC, ALE, ALEX, ALF, ALK, ALLY, ALT, ALXN, AMC, AMCR, AMD, AMID, AMP, AMZN, ANDA, APEX, APHA, APPS, APR, APRN, APT, ARCH, ASH, ATHX, ATNM, ATVI, ATX, AUG, AURA, AUY, AVD, AXP, AYX, AZZ, BABA, BAC, BAH, BAM, BAND, BARE, BAS, BAX, BBCP, BBL, BBQ, BBY, BDN, BDX, BFS, BHAT, BIGC, BIO, BIOS, BIRD, BITE, BLDP, BLNK, BLOG, BMI, BMY, BNGO, BOI, BOLD, BOOT, BOWL, BRAG, BREW, BRKA, BROS, BST, BULK, BWMX, BYD, BYND, CAB, CAKE, CAL, CALI, CALM, CAM, ...]"
9,10,gkggr4,2020-05-15T20:07:22+00:00,708,250278,"[AAL, AAPL, ABC, ABT, ACB, ACRE, ACTT, ADBE, ADP, ADPT, ADS, ADX, AGG, AHH, AIM, AIN, AIRS, ALE, ALEX, ALGN, ALK, ALLY, ALT, ALTA, ALTO, AMAT, AMC, AMD, AMID, AMP, AMZN, ANDS, AOBC, APDN, APHA, APPF, APPN, APPS, APR, APT, APY, ARC, ARCH, ARD, ARWR, ASM, ATVI, AUG, AUS, AUY, AVID, AWH, AXE, AXP, AYX, AZZ, BABA, BAC, BAM, BAND, BARE, BARK, BAS, BBBY, BBQ, BBY, BDAY, BEN, BFS, BIIB, BILI, BIO, BIRD, BITE, BKNG, BLOG, BLVD, BMI, BOE, BOI, BOLD, BON, BOOT, BOWL, BRAG, BREW, BRKA, BRKS, BROS, BTE, BTU, BULK, BWC, BYND, CAB, CAKE, CAL, CALC, CALI, CALM, ...]"
10,11,gg0k2r,2020-05-08T20:08:25+00:00,707,249571,"[AAL, AAN, AAP, AAPL, ABB, ABBV, ABC, ABT, ACB, ACC, ACH, ACRE, ADBE, ADS, ADSK, AGC, AHH, AIM, AIMT, AIN, AJRD, ALE, ALEX, ALGS, ALK, ALLY, ALNA, ALT, ALTO, AMAT, AMC, AMD, AMG, AMID, AMP, AMPS, AMRX, AMZN, AOBC, APD, APEX, APHA, APM, APPN, APPS, APR, APT, APY, AQN, ARC, ARCH, ARMK, ARWR, ASA, ASH, ATVI, AUG, AUPH, AUS, AVID, AVYA, AXE, AXON, AXP, AYTU, AYX, BABA, BAC, BAM, BAND, BARE, BARK, BAS, BBBY, BBD, BBQ, BBW, BBY, BCRX, BDAY, BEAM, BEN, BILI, BIO, BIRD, BITE, BKNG, BLMN, BLOG, BLU, BMI, BMO, BMY, BOI, BOLD, BOLT, BOOT, BOWL, BRAG, BREW, ...]"
11,12,hx90gx,2020-07-24T20:07:43+00:00,678,229503,"[AAL, AAPL, AAXN, ABBV, ABC, ABT, ABUS, ACA, ACB, ACC, ACI, ADBE, ADS, ADSK, AEO, AESE, AHH, AHS, AIM, AIN, AIT, AJRD, AKAM, ALE, ALEX, ALF, ALK, ALLY, ALT, ALXN, AMAT, AMC, AMD, AME, AMID, AMKR, AMP, AMT, AMZN, ANTM, AOBC, APA, APC, APH, APHA, APPS, APR, APRN, APT, APY, ARC, ARDS, ASM, ASNA, ATNM, ATVI, AUD, AUG, AUS, AUY, AXP, BABA, BAC, BAM, BAND, BARE, BBBY, BBQ, BBY, BCOV, BCRX, BDAY, BEN, BENE, BFS, BHC, BIO, BIRD, BITE, BKNG, BLDP, BLOG, BLU, BLVD, BMO, BOI, BOLD, BON, BOOT, BOSA, BOWL, BRAG, BREW, BRKA, BROS, BSET, BULK, BXMT, BYND, CAKE, ...]"
12,13,hkpyve,2020-07-03T20:08:01+00:00,660,217470,"[AAL, AAPL, ABBV, ABC, ABER, ACB, ACC, ACH, ACRE, ADP, ADS, ADX, AGN, AHH, AHT, AIM, AIN, AIRS, AKAM, ALEX, ALLY, ALT, ALTO, AMAT, AMC, AMD, AMG, AMGN, AMID, AMP, AMZN, ANGI, APEX, APHA, APPS, APR, APT, ARC, ARCH, ARDS, ARI, ARMK, ATVI, AUD, AUG, AURA, AUY, AVID, AWH, AXDX, AXL, BABA, BAC, BAM, BAND, BARE, BBBY, BBG, BBK, BBQ, BBW, BBY, BEAM, BEN, BFS, BILI, BIO, BIRD, BITE, BKS, BLDP, BLK, BLL, BLNK, BLOG, BOI, BOLD, BON, BOOT, BOWL, BRAG, BREW, BRKA, BROS, BRW, BTB, BULK, BUR, BYD, BYND, CAB, CAKE, CAL, CALI, CALM, CAM, CAMP, CAPS, CARA, CARB, ...]"
13,14,gu5xww,2020-05-31T20:08:12+00:00,650,210925,"[AAL, AAPL, AAXN, ABBV, ABC, ABCO, ABT, ACA, ACB, ACC, ACH, ACRE, ADMA, ADN, ADS, ADSK, ADT, AESE, AGC, AGEN, AGM, AHH, AHS, AIG, AIM, AIN, AJRD, ALE, ALK, ALLE, ALLY, ALT, AMBA, AMC, AMD, AMID, AMP, AMRS, AMS, AMT, AMZN, AOBC, APEX, APHA, APOG, APPS, APRN, APT, APY, ARC, ARCH, ARCO, ARWR, ARYA, ASH, ATVI, AUD, AUG, AUY, AVGO, AXE, AXON, AXP, AZZ, BABA, BAC, BAM, BAND, BARK, BBQ, BBY, BDAY, BEN, BFS, BGC, BIO, BIRD, BITE, BKNG, BLOG, BMO, BOI, BOLD, BOOT, BRAG, BROS, BTG, BULK, BUR, BYD, BYND, CAKE, CAL, CALC, CALI, CALM, CAMP, CAPS, CART, CATS, ...]"
14,15,gbpcs2,2020-05-01T20:09:09+00:00,649,210276,"[AAL, AAMC, AAPL, ABBV, ABC, ABT, ACAT, ACB, ACC, ACRE, ADP, ADS, ADX, AER, AFB, AGR, AHH, AIG, AIM, AIMT, AIN, AKER, ALEC, ALEX, ALGT, ALK, ALLY, ALSK, ALT, AMC, AMD, AME, AMG, AMID, AMP, AMZN, ANDS, ANF, AOBC, APEX, APHA, APPS, APRN, APRS, APT, APY, ARCH, ARW, ATVI, AUG, AUS, AWK, AXE, AXP, AYR, AYX, BABA, BAC, BAM, BAND, BARE, BARK, BAS, BBG, BBQ, BBY, BCH, BCRX, BDAY, BEAM, BEN, BFS, BIIB, BIO, BIOS, BIRD, BITE, BKNG, BLK, BLMN, BLOG, BMY, BOI, BOLD, BOLT, BON, BOOT, BOWL, BRAG, BREW, BRKA, BRKS, BROS, BTB, BULK, BYD, BYND, CAB, CAKE, CALA, ...]"
15,16,fi5jtz,2020-03-13T19:47:11+00:00,645,207690,"[AAL, AAN, AAPL, ABBV, ABC, ABM, ABT, ACB, ACC, ACH, ADBE, ADM, ADS, AEO, AFB, AHH, AIG, AIM, AIN, AJRD, ALEX, ALK, ALLY, ALR, ALT, ALTA, ALTO, AMC, AMD, AMID, AMP, AMWD, AMZN, AOBC, APAC, APEX, APHA, APPS, APR, APT, APU, APY, ARC, ARCH, ARDS, ARMK, ASA, ATX, AUD, AUG, AUS, AWK, AXP, BABA, BAC, BAH, BAM, BAND, BARE, BARK, BBQ, BBY, BCC, BDAY, BEN, BFS, BILI, BIO, BIRD, BITE, BKNG, BKS, BMI, BOE, BOH, BOI, BOLD, BOLT, BON, BOOT, BOWL, BRAG, BREW, BRKA, BROS, BULK, BYND, CABO, CAC, CAH, CAKE, CAL, CALI, CALM, CAM, CAMD, CAMP, CAPS, CART, CATS, ...]"
16,17,hrorfa,2020-07-15T14:42:05+00:00,639,203841,"[AAL, AAPL, AAXN, ABB, ABT, ACB, ACC, ACER, ACHV, ACRE, ADS, AEZS, AHH, AHT, AIM, AIN, AKTS, ALDX, ALEX, ALK, ALLY, ALNA, ALPP, ALT, AMAT, AMC, AMCX, AMD, AMP, AMPE, AMSC, AMTX, AMZN, ANDS, APHA, APO, APPS, APT, ARA, ARW, ARWR, ASM, ASMB, ASNA, ATNM, ATOM, ATVI, AUG, AUS, AVB, AVID, AWH, AXAS, AXE, AXON, AXP, AYTU, AZZ, BABA, BAC, BAH, BAND, BARK, BAX, BBQ, BBW, BCC, BEN, BFA, BGG, BIIB, BIMI, BIO, BIP, BITE, BKI, BKNG, BKYI, BLDP, BLNK, BLU, BMRA, BNED, BNGO, BNS, BOI, BOLD, BOOT, BOXL, BRAG, BRFS, BRKA, BRMK, BRQS, BST, BSX, BTO, BYND, CAKE, CAMP, ...]"
17,18,g7fkq6,2020-04-24T20:08:10+00:00,638,203203,"[AAL, AAPL, ABBV, ABC, ABT, ACB, ACC, ADBE, ADS, AEO, AGG, AHH, AHS, AIM, AIMT, AIN, AKRX, ALEX, ALK, ALLY, AMC, AMD, AMGN, AMID, AMP, AMZN, APA, APEX, APPS, APR, APU, ARC, ARCH, ARES, ARWR, ASH, ASNA, ATVI, AUG, AURA, AUS, AUY, AVID, AXE, AXP, AYTU, BABA, BAC, BAM, BAND, BARE, BAS, BBG, BBQ, BBW, BBY, BDAY, BEAM, BEN, BFS, BIO, BIRD, BITE, BKNG, BLOG, BLVD, BOI, BOLD, BOOT, BOWL, BRAG, BROS, BULK, BYD, BYND, CACC, CAKE, CAL, CALI, CALM, CAM, CAMP, CAPS, CARR, CART, CAS, CATS, CBOE, CBS, CCJ, CCL, CCN, CCS, CDS, CEMI, CENT, CFR, CHA, CHEF, CHGG, ...]"
18,19,g39g3g,2020-04-17T20:08:08+00:00,633,200028,"[AAL, AAP, AAPL, ABBV, ABC, ABT, ACB, ACC, ACH, ACRE, ADS, AER, AGG, AGI, AGS, AHH, AIM, AIMT, AIN, AIO, AIRS, ALEX, ALLY, ALT, ALTO, AMC, AMD, AMID, AMP, AMT, AMTD, AMZN, ANET, ANF, ANTM, APEX, APHA, APPS, APR, APRN, APU, ARC, ARCH, ARW, ARWR, ATC, ATVI, AUG, AUY, AVB, AVGO, AVID, AXP, AYTU, BABA, BAC, BAM, BAND, BAP, BARE, BBBY, BBL, BBW, BBY, BDAY, BEN, BILI, BIO, BIRD, BITE, BLOG, BLU, BOAS, BOI, BOLD, BOWL, BRAG, BREW, BRKA, BROS, BULK, BYND, CAB, CACC, CAH, CAKE, CALC, CALI, CALM, CAM, CAMP, CAPS, CART, CAS, CASA, CATS, CBOE, CBS, CBT, CCI, ...]"
19,20,fm1mgt,2020-03-20T20:00:19+00:00,624,194376,"[AAL, AAPL, ABBV, ABC, ABT, ACB, ACC, ACER, ACH, ACRE, ADBE, ADP, ADS, AEM, AEO, AGI, AGR, AHH, AHT, AIG, AIM, AIMT, AIN, ALEX, ALLY, ALT, ALTA, AMC, AMD, AMID, AMP, AMRX, AMZN, ANF, ANTM, AOBC, APC, APCS, APEX, APHA, APPS, APR, APRN, APT, APY, ARC, ARDS, ARMK, ARW, ATA, ATC, ATVI, AUG, AUS, AVB, AWH, AXE, AXP, AYTU, AZO, BABA, BAC, BAH, BAM, BAND, BARE, BARK, BAS, BBY, BDAY, BDX, BEAM, BEN, BFS, BIO, BIRD, BITE, BITI, BLK, BLOG, BLU, BLVD, BMY, BOI, BOLD, BON, BOOT, BOWL, BRAG, BREW, BRKA, BROS, BSL, BULK, BURL, BYD, BYND, CAB, CAC, CACC, ...]"

完成： C:\Users\eagle\RedditStock\Data\process\t04_1_ticker_exclusion_diagnostics\2026-09-22_10-06-32_UTC